### ISSUE TITLE
Specify value for --proto_path?

### ISSUE THREAD

**Issue by codespear** [google/protobuf-gradle-plugin#105]
I have been given a .proto file (file X) that imports another .proto file (file Y).  Unfortunately, file X and file Y are not in the same directory.  From the command line I provide the *--proto_path* argument to *protoc* to fix this when generating the source for file X. 

How can I tell the protobuf-gradle-plugin about this path?

**Comment by ejona86** [comment]
Why don't you just build the directory tree in `src/main/proto`?

Assuming you have, `src/main/proto/my/package1/messages.proto`, then in `src/main/proto/my/package2/messages2.proto` you would `import "my/package1/messages.proto"`.

**Comment by ejona86** [comment]
If you are using proto's across projects, a compile dependency should automatically make them available.

**Comment by codespear** [comment]
@ejona86:  Thank you for the help.

The root cause of my problem is that the proto files I am given as input to my build have a tree structure that makes things difficult.   

Because of this (and other problems), I decided to implement an [incremental custom task type](https://docs.gradle.org/current/userguide/custom_tasks.html) that calls *protoc* directly.  This approach is obviously not ideal.

I hope in the future to have a closer look at the *protobuf-gradle-plugin* and try your suggestions.
