### ISSUE TITLE
Import in proto seems broken

### ISSUE THREAD

**Issue by Gericop** [google/protobuf-gradle-plugin#107]
I have the following structure of proto files in my Android module:
```
src/main/proto
- mobile
   - coordinator.proto
   - player.proto
   - data.proto
   - tasktypes.proto
- mobile.proto
```
The `mobile.proto` imports the other four in that folder. The individual files under the `mobile` folder don't import anything, yet it compiles in Node.js.
I tried to copy the same structure to the given directory in Android and there's no way of compiling it successfully. It seems like the "import" system is just messed up.

First of all I had to add the imports of `data` and `tasktypes` to `coordinator` to even find the message types. Then the `mobile` folder was added to the source set, otherwise it was complaining about not finding the files in `coordinator.proto` (because the imports were relative as they _should_ be). Now it complains that the messages in `data.proto` were already defined in `data.proto`. This seriously needs to be fixed. Is there any way to let the system know that I only want `mobile.proto` to be included and then use the imports in that and stop trying to compile each and every `.proto` in that `/proto` folder? Or the imports should be relative to the current file's path. Now I cannot share the .proto files with the Node.js project because the Node throws an error if I include `mobile/` in the import path, but if I don't do that, the Android project can't compile...

**UPDATE**: Okay, so it seems like the plugin respects folders for the "import" statements, but when it gets to the compiler, the folders are no longer there (see in the `extracted-include-protos` folder), yet the import statements call for the given folders. This is not a desirable behavior and should be fixed.

**Comment by zhangkun83** [comment]
Please provide the following information:
 1. The import lines of the proto files in question;
 2. The directory structure of `extracted-include-protos`;
 2. The output of `./gradlew clean build --info | grep 'protoc[^ ]*\.exe'`

**Comment by rocketraman** [comment]
Same issue here. @zhangkun83 , you can simply reproduce it with a directory structure and files as follows:

```
src/main/proto
├── foo
│   └── bar.proto
└── foo.proto
```

```
$ cat src/main/proto/foo.proto
syntax = "proto3";

package foo;

import "foo/bar.proto";

message Foo {
  Bar bar = 1;
}
```

```
$ cat src/main/proto/bar/bar.proto
syntax = "proto3";

package foo.bar;

message Bar {
  string b = 1;
}
```

**Comment by Gericop** [comment]
Any news regarding this issue?

**Comment by zhangkun83** [comment]
@rocketraman I don't think it's simply the case. Please take a look at the `exampleProject`. Its protos have imports from different directories, and it compiles (try `../gradlew build`). It will be helpful if you could provide me a standalone project to demonstrate the issue.

**Comment by rocketraman** [comment]
@zhangkun83 Indeed, it does seem to work correctly. I believe the issue was that the package declarations in the `.proto` files did not match the path in the `src/main/proto` directory. So, using my original example, it works if it is changed to something like:

```
src/main/proto
└── foo
    ├── bar
    │   └── bar.proto
    └── foo.proto

```

```
$ cat src/main/proto/foo/foo.proto
syntax = "proto3";

// matches directory foo
package foo;

import "foo/bar/bar.proto";

message Foo {
  Bar bar = 1;
}
```

```
$ cat src/main/proto/foo/bar/bar.proto
syntax = "proto3";

// matches directory foo/bar
package foo.bar;

message Bar {
  string b = 1;
}
```

**Comment by zhangkun83** [comment]
I was not aware protoc had such requirement. Anyway, it doesn't seem to be an issue of the plugin.
