### ISSUE TITLE
generated files should be added to gradle sources

### ISSUE THREAD

**Issue by TomDePauw** [google/protobuf-gradle-plugin#109]
now we need a hack to get things working in eclipse or intellij, same when publishing to maven (-sources.jar files).
for eclipse, maven-publish, .. i use in my project:

```
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}
```

It would be handy if the plugin added these files to the sources.

**Comment by zhangkun83** [comment]
The directories of generated sources can be altered by the configurations in the `protobuf` block, which takes effect **after** the evaluation phase, I am not sure whether IDE will pick up the changes. Have you tried the tips from the **IntelliJ IDEA** section in the README?

**Comment by TomDePauw** [comment]
yes i used that to make a similar thing for eclipse

```
eclipse{
     classpath {
         file {
             withXml {
                 def node = it.asNode()
                 node.appendNode('classpathentry', [kind: 'src', path: "build/generated/source/proto/main/grpc"])
                 node.appendNode('classpathentry', [kind: 'src', path: "build/generated/source/proto/main/java"])
            }
         }
     }
 }
```
 
But what i want to do is publish the project to a local maven repo. That also works, but if i want the sources to also publish to the repo, they need to be available. So i need a similar 'hack' for that, or the java files need to be added to the gradle sources. Like the example i gave in my first post. Doing that fixes the IDEA/eclipse and maven publishing issue.

My thought is that the protobuf-gradle-plugin should add it to the sources. So it works out of the box.

**Comment by naugler** [comment]
I have this same issue. Explicitly adding the generated sources seems like a far simpler way to get the IDEs to understand. Tom's [first comment](https://github.com/google/protobuf-gradle-plugin/issues/109?_pjax=%23js-repo-pjax-container#issue-192565917) resolves issues in eclipse AND netbeans. 

If the IDEs are parsing build.gradle to understand project structure I'm not sure how the protobuf-gradle-plugin will reliably add sources for code completion, etc.

**Comment by manderson23** [comment]
I also added the following entry alongside withXml to prevent duplicate entries for the generated source if the eclipse tasks is run multiple times

`beforeMerged {
        classpath -> classpath.entries.removeAll { entry -> entry.kind == 'src' }
      }`

**Comment by noel-yap** [comment]
I'm running into the same issue. After some consideration, since the build itself works from the command line (ie the compilation knows about the generated sources), I'm suspecting the IDE's themselves aren't parsing correctly the Gradle files.

Anyway, explicitly adding the Java sources works around the problem in both IDEA and Eclipse and should work for any IDE.

**Comment by vorburger** [comment]
Over in https://github.com/grpc/grpc-java/pull/3598, @oehme [advised that](https://github.com/grpc/grpc-java/pull/3598#issuecomment-338927408): _"The protobuf plugin should add its proto source directory set to the "allSource" source directory set. That's what the IDEs query."_. If this issue (eventually) implements that, then there should be no need to put anything into the build.gradle and it will "just work", out of the box.

**Comment by jcornaz** [comment]
Any update on this?

**Comment by marcellodesales** [comment]
Still looking for updates @jcornaz

**Comment by jamesward** [comment]
BTW, for those using `build.gradle.kts` the syntax that works for me is:
```
sourceSets {
    val main by getting { }
    main.java.srcDirs("build/generated/source/proto/main/java")
    main.java.srcDirs("build/generated/source/proto/main/grpc")
}
```

**Comment by jamesward** [comment]
Looking further into this it seems that setting up the src dirs automatically requires the `idea` plugin.  That shouldn't be needed as IntelliJ can import Gradle projects without that plugin.  Can we remove that requirement?  Here is a tester project:
https://github.com/jamesward/proto-gradle-bork-idea

Without the `idea` plugin I get:
![image](https://user-images.githubusercontent.com/65043/174648532-18142dfb-2014-4601-b6ef-e0fec5d2fcac.png)

**Comment by SayakMukhopadhyay** [comment]
> Looking further into this it seems that setting up the src dirs automatically requires the `idea` plugin. That shouldn't be needed as IntelliJ can import Gradle projects without that plugin. Can we remove that requirement? Here is a tester project: https://github.com/jamesward/proto-gradle-bork-idea
> 
> Without the `idea` plugin I get: ![image](https://user-images.githubusercontent.com/65043/174648532-18142dfb-2014-4601-b6ef-e0fec5d2fcac.png)

I was looking at the source code of the plugin and this is the line where the check is made https://github.com/google/protobuf-gradle-plugin/blob/56b9800b341fca5cc43ec5aab1a96c3a2d87d8c9/src/main/groovy/com/google/protobuf/gradle/Utils.groovy#L112

I have experienced weird issues when the idea plugin is not applied. Sometimes it would work and othertimes it wont.

**Comment by ejona86** [comment]
This issue is a mix of things, but I'm going to call this fixed by #601 and say -sources.jar should now be fixed. IDE support is strange because they tend to need the folders to exist, so just having the directories in the source sets in insufficient. Intellij and Eclipse will continue to need you to apply their respective plugins, but with #590 now they should both be working if you apply the plugin.

**Comment by jamesward** [comment]
Looking forward to trying this.  @ejona86 Are you saying that the `idea` plugin will still be required for this to work in IntelliJ?

**Comment by ejona86** [comment]
From start to finish, yes idea plugin would still be required. If you have already done a build and then open with IntelliJ, it'd probably work without the plugin.

I do hope to remove some usages of the intellij plugin API, but we'd still be triggering code to create the folders based on it. We don't want to do that in all cases because it prevents task configuration avoidance.
