### ISSUE TITLE
IntelliJ: generateProto task not executed when building from the IDE

### ISSUE THREAD

**Issue by NachoSoto** [google/protobuf-gradle-plugin#111]
I reproduced this in `exampleProject`: running `gradle build` runs the `generateProto` task, because that's a dependency:
```
$ gradle build --dry-run
:extractIncludeProto SKIPPED
:extractProto SKIPPED
:generateProto SKIPPED
:compileJava SKIPPED
:processResources SKIPPED
:classes SKIPPED
:jar SKIPPED
:assemble SKIPPED
:extractIncludeTestProto SKIPPED
:extractTestProto SKIPPED
:generateTestProto SKIPPED
:compileTestJava SKIPPED
:processTestResources SKIPPED
:testClasses SKIPPED
:test SKIPPED
:check SKIPPED
:build SKIPPED

BUILD SUCCESSFUL

Total time: 1.115 secs
```

However, a simple run configuration defined in IntelliJ like this:
<img width="974" alt="screen shot 2016-12-29 at 3 25 50 pm" src="https://cloud.githubusercontent.com/assets/685609/21557028/5de1f4e4-cddb-11e6-9591-45f5c4d0c118.png">

Does not automatically generate them.

I'm not familiar enough with Gradle to understand why, but [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin) does work automatically: no matter what type of run configuration you have, `apt` will run. I'd love to be able to set up `protobuf` in similar way, so I'd appreciate any pointers.

Thanks.

**Comment by NachoSoto** [comment]
Update: in fact I can't make this work now. This is my flow:
- Clean everything.
- Build in IntelliJ.
  - Protobuf classes aren't generated (like I showed).
- Run `./gradlew generateProto`.
  - Classes are generated in the correct folder.
  - IntellIJ shows that my `import corsac.message.Responses;` is correct (not red).
  - Despite that, IntelliJ shows the following build error: `Error:(18, 22) java: package corsac.message does not exist`

<img width="239" alt="screen shot 2017-01-02 at 2 51 04 pm" src="https://cloud.githubusercontent.com/assets/685609/21597171/f5d2650a-d0fa-11e6-9881-202d787bb21d.png">
<img width="304" alt="screen shot 2017-01-02 at 2 51 27 pm" src="https://cloud.githubusercontent.com/assets/685609/21597172/f5eefd3c-d0fa-11e6-90b1-c807dd77cbf2.png">

So I have no idea what's going on, but I'm guessing there's something about how `./gradlew` builds from the command line that doesn't match IntelliJ.
Running `./gradlew build` instead leads to the following error:
```
$ ./gradlew build
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
:compileJava
An exception has occurred in the compiler (1.8.0_101). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:892)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
```

**Comment by NachoSoto** [comment]
This is my gradle config:
```groovy
idea {
    module {
        generatedSourceDirs = [ file("src/main/generated") ]

        sourceDirs += file("src/main/java")
        sourceDirs += file("src/main/generated")
    }
}


sourceSets {
    main {
        output.generatedSourcesDir = 'src/main/generated'
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.1.0"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    outputSubDir = 'generated'
                }
            }
        }
    }

    generatedFilesBaseDir = "${projectDir}/src/"
}

clean {
    delete 'src/main/generated'
}
```

**Comment by NachoSoto** [comment]
Another data point: if I remove the `import` to get it to compile successfully, I can see that the `generated` sources created by Protobuf do not end up in the `build` directory (those generated by `ant` do, however):

<img width="235" alt="screen shot 2017-01-03 at 2 12 10 pm" src="https://cloud.githubusercontent.com/assets/685609/21625049/a280ac12-d1be-11e6-9e2a-dbc683dcebd9.png">

<img width="188" alt="screen shot 2017-01-03 at 2 12 29 pm" src="https://cloud.githubusercontent.com/assets/685609/21625053/ada94234-d1be-11e6-8e36-2d26954e9288.png">

I feel like I'm close to the source of the issue, but I can't figure it out. What would make these sources different from ones generated by `ant`? They're both part of the `generated` sources dir, marked as sources, and they have no compilation issues...

**Comment by NachoSoto** [comment]
Okay I've fixed all the issues and managed to get this back to a point where it _works_ by moving `generated` back to the `build` directory. I'm not sure why that matters, but it's fine for me.
The main issue still stands: I need to manually run `./gradlew generateProto` from the command line, but I'd love to be able to have these generated automatically when building from the IDE.

**Comment by alfasapy** [comment]
I would also like to see this issue resolved.

As a temporary workaround:
Open Gradle view
Find generateProto task
Right click and mark task to "Run before make"

Every time you press Make you will be running the generateProto task

Other options:
Setup protoc locally (for OS X you can use HomeBrew) and configure the proto plugin in IDEA.
I believe there is also an option for Make to delegate to Gradle in IDEA configuration.

**Comment by zpencer** [comment]
According to the README for https://github.com/tbroyer/gradle-apt-plugin , the preferred way for Intellij to build things is by delegating to gradle: https://www.jetbrains.com/idea/whatsnew/#v2016-3-gradle

I tested this out with the exampleProject and it it worked:
1. import the example project's `build.gradle` as an intellij project
2. run `../gradle clean` and verify that the `build` directory is gone
3.  Enable the "delegate to gradle" setting for the project: https://www.jetbrains.com/idea/whatsnew/#v2016-3-gradle
4. Open up `FooTest.java`, right click on it and select `Run`, verify that all protos are generated.

At the moment, the java files that are created by the GenerateProtoTask under `build/generated/source` are not automatically registered in intellij. I think that's a separate issue that is worth us looking into.

**Comment by magJ** [comment]
Taking @alfasapy 's approach, and combining it with the [gradle idea-ext plugin](https://github.com/JetBrains/gradle-idea-ext-plugin), you can create a solution that does not require manual IDE configuration.  
Example:
```groovy
apply plugin: 'java'
apply plugin: 'com.google.protobuf'
apply plugin: 'idea'
apply plugin: 'org.jetbrains.gradle.plugin.idea-ext'

dependencies {
    compile 'com.google.protobuf:protobuf-java:3.0.0'
    compile 'io.grpc:grpc-protobuf:1.17.1'
    compile 'io.grpc:grpc-stub:1.17.1'
    compileOnly 'javax.annotation:javax.annotation-api:1.2'
}

protobuf {

    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.8.0"
        }
    }
    
    generateProtoTasks {
        def genProtoTasks = ofSourceSet('main')
        genProtoTasks*.plugins {
            grpc {}
        }
        rootProject.extensions.idea.project.settings {
            taskTriggers {
                beforeBuild(genProtoTasks as Task[])
            }
        }
    }
}
```
Ideally, the jetbrains guys would come up with a better solution for configuring source generation tasks, but this seems to work well enough for now.
