### ISSUE TITLE
Add some more information on how to add this source to gradle

### ISSUE THREAD

**Issue by newnexus** [google/protobuf-gradle-plugin#114]
Would like a more in depth explanation on which files i should put and where, when using android studio + gradle.  when i open up studio directory I only see Android Studio\gradle\gradle-2.8 in that case should i duplicate directory for previous gradle version?

**Comment by zhangkun83** [comment]
I don't understand your question. Are you asking where to put your `.proto` files?

**Comment by newnexus** [comment]
nope, I know how to compile .proto files to jave class, but thing is in examplary "adress book" project some of methods are not found, for example com.google.protobuf.ExtensionRegistryLite registry)("cannot resolve symbol 'protobuf')  so my guess was that i put source from plugin in wrong place,  correct me if i'm wrong please.

**Comment by zhangkun83** [comment]
`com.google.protobuf.ExtensionRegistryLite` is from the protobuf jar. Do you have `com.google.protobuf:protobuf-java:<the protobuf version you are using>` in your `compile` dependencies?

**Comment by newnexus** [comment]
yes, i followed manual and compiled a protobuf-java-3.0.0.jar and dropped it in libs directory, protoc --version > libprotoc 3.0.0. but some other changes have made it worse now it got stuck again at [http://stackoverflow.com/questions/39284797/android-studio-and-protobuf-error7-0-plugin-with-id-com-google-protobuf-no](url), compiling example project with command line instead of using android studio worked, but there is no way to check gradle settings that were used, because gradle subdirectory do not show up in android studio like with my other projects. Would you be kind to explain how am i supposed to apply this plugin to existing project.

**Comment by zhangkun83** [comment]
Are you still seeing the issue?
