### ISSUE TITLE
JS Generation example project

### ISSUE THREAD

**Issue by luistrigueiros** [google/protobuf-gradle-plugin#115]
Hi

Where can I find one example project that generates both Java & Javascript ?

Thank you, kindly  
  Oscar

**Comment by zhangkun83** [comment]
According to https://developers.google.com/protocol-buffers/docs/reference/javascript-generated, `js` is a built-in output of `protoc`. You can do this to generate JS in addition to Java:

```gradle
protobuf {
  ...
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        js {
          // These options are copied as an example from the previously linked doc, which says
          // "protoc --proto_path=src --js_out=import_style=commonjs,binary:build/gen src/foo.proto src/bar/baz.proto"
          // They are interpreted by protoc. I don't know what they mean. You will need to figure out
          // what options you need.
          option "import_style=commonjs"
          option "binary"
        }
      }
    }
}
```

**Comment by nicqchen** [comment]
hou can i change the js output directory?

**Comment by voidzcy** [comment]
> hou can i change the js output directory?

It's not recommended to change the output directory for generated code (#332), you could add the default output directory for js (e.g., `$generatedFilesBaseDir/main/js`) to the compilation source set. If you want to export the generated code or for other packaging purposes, you could add a `Copy`/`Sync` task to do that (see [gRPC's usage](https://github.com/grpc/grpc-java/blob/67ad78608c7a978ae86affc871a4bdaa48915a33/build.gradle#L90-L117)). We strongly discourage changing the output directory to mix generated code with your own code, as the plugin may accidentally overwrite your code.
