### ISSUE TITLE
Transitive protobuf dependencies

### ISSUE THREAD

**Issue by matthewrj** [google/protobuf-gradle-plugin#116]
I have two artifacts published to a maven repo. Both are zips of proto files. The pom of one declares the other as a dependency. When I try depend on just the parent, the child dependency is ignored.

Is this a limitation or have I done something wrong?

**Comment by zhangkun83** [comment]
It might be a bug. Where are your artifacts that I can test with?

**Comment by matthewrj** [comment]
They are in a private company repo and I unfortunately cannot publicly expose them. I actually discovered it works using a "compile" dependency but doesn't work using a "protobuf" dependency. How does a "protobuf" dependency differ from a compile dependency?

**Comment by matthewrj** [comment]
To distinguish between protobuf and compile dependencies (so I can publish them separately) my workaround for this issue is to add:
```
configurations {
	compile.extendsFrom(protobuf)
}
```

**Comment by zhangkun83** [comment]
I suspect this is due to [a line](https://github.com/google/protobuf-gradle-plugin/blob/v0.8.0/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L132) that sets `transitive` to `false`. I have pushed a snapshot that changes it to `true`. Can you try it out:
```gradle
buildscript {
  repositories {
    maven {
       url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
  }
  dependencies {
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.1-SNAPSHOT'
  }
}
```

**Comment by matthewrj** [comment]
Yes that fixes it
