### ISSUE TITLE
Android Studio java project doesn't work with idea plugin.

### ISSUE THREAD

**Issue by SetoKaiba** [google/protobuf-gradle-plugin#118]
idea {
    module {
        sourceDirs += file("${protobuf.generatedFilesBaseDir}/main/java");
        // If you have additional sourceSets and/or codegen plugins, add all of them
        sourceDirs += file("${protobuf.generatedFilesBaseDir}/main/grpc");
    }
}

This is working with java project in IDEA.
But it's not working with java project in Android Studio.

**Comment by SetoKaiba** [comment]
Hi. Anyone?

**Comment by SetoKaiba** [comment]
generatedFilesBaseDir = "$projectDir/gen"

Okay. I see. I have to move the generated folder outside the build folder. Or it won't be recognized.

**Comment by zhangkun83** [comment]
I am glad you figured it out. Sorry I don't use those IDEs and I was unable to help.
