### ISSUE TITLE
Preventing incoming .proto dependencies against generating classes twice

### ISSUE THREAD

**Issue by mindas** [google/protobuf-gradle-plugin#123]
I have two Java projects which contain .proto files, let's call them `parent` and `child`.

`parent` has some shared definitions in `common.proto` which is exported in its jar together with generated .class files. Then both classes and common.proto from `parent` are imported in `child`'s `build.gradle`:

```
dependencies {
  ...
  compile 'parent:someversion'
  protobuf 'parent:someversion'
}
```

This way I do not need to redefine the same common bits in `child` project. So far so good.

Now if I run `gradlew build` for `child` project, classes from `parent`'s `common.proto` are generated again for the second time. They are already present in `parent.jar` and are now generated for `child`.

I can exclude those classes when jarring `child` project but ideally I would like to address the problem at the source. Is it possible to use shared parent .proto file so that child .proto files could be processed successfully but skip generating class files from the former? 

Alternative suggestions for such a setup are too welcome. Thanks in advance.

**Comment by zhangkun83** [comment]
You shouldn't need to have `protobuf 'parent:someversion'`. The `compile` dependency makes all packaged protos available for import in `child` without re-compiling them.

**Comment by mindas** [comment]
Sorry if I haven't expressed myself clearly, but even if I remove the `protobuf 'parent:someversion'` dependency, `gradle build` does generate classes from parent's common.proto. Is there a way to suppress that?

**Comment by zhangkun83** [comment]
This shouldn't happen. We have a [test project](https://github.com/google/protobuf-gradle-plugin/blob/master/testProjectDependent/build.gradle) for this behavior. If you could share with me your project or a minimal test project to reproduce this issue, I can look into it.

**Comment by mindas** [comment]
Sorry, you are right - my problem was caused by stale jars. Thanks for your help, appreciated.
