### ISSUE TITLE
How to tell the protobuffer Gradle plugin not to generate protogen files?

### ISSUE THREAD

**Issue by noel-yap** [google/protobuf-gradle-plugin#124]
https://stackoverflow.com/questions/43456176/how-to-tell-the-protobuffer-gradle-plugin-not-to-generate-protogen-files

I've created a proto plugin. When I execute: `protoc --plugin=protoc-gen-grpc-java=grpc-client-guice-gradle-plugin --grpc-java_out=build/generated/source/proto/client/java --proto_path=../snth-proto-definition/src/main/proto:../snth-proto-definition/build/extracted-include-protos/main ../snth-proto-definition/src/main/proto/snthnyap.proto`

it generates the files I expect and only those files. But if I execute: `gradlew generateProto`
extra files are created with the comment `// Generated by the protocol buffer compiler.  DO NOT EDIT!`.

Is there a configuration setting to prevent these files from being generated?

**Comment by zhangkun83** [comment]
Answered on the SO post.
