### ISSUE TITLE
Documentation unclear on what task to call to generate

### ISSUE THREAD

**Issue by emperorcezar** [google/protobuf-gradle-plugin#128]
Only by digging did I find that I could run `gradle generateProto`. Is this something that should be in the documentation?

**Comment by zhangkun83** [comment]
The task name is intentionally kept undocumented, because it's subject to change. `generateProto` is invoked automatically by `compileJava`. Why do you want to run it manually?

**Comment by emperorcezar** [comment]
Probably my lack of Java experience, but I'm using protobufs/grpc in my
clojure project. All I want is the generated code for the protobufs. I
didn't see the `compileJava` command called out in the docs either.

-------------------------------------------------------------------------------------------------------------
Father, Pythonista, Cyclist, Brewer. Dabbling in Clojure and Functional
Languages

**Comment by zhangkun83** [comment]
`compileJava` is defined by Gradle, and you don't normally run it directly either. Instead you would run `build` and it will invoke `compileJava` which will invoke `generateProto`.

**Comment by emperorcezar** [comment]
That makes sense. Thanks for your help.
