### ISSUE TITLE
Using --proto_path explicitly

### ISSUE THREAD

**Issue by psionic12** [google/protobuf-gradle-plugin#130]
For some reason, My project uses proto files which is shared with other projects. There are lots of files which has code like this:`import "pus/push_message.proto"`, this will get error in compiling if I put the proto files in src/main/proto. Before I use plugin to generate proto classes, this issue could be fixed by using `--proto_path` in command line, but this seems not be supported in this plugin.

I'v read https://github.com/google/protobuf-gradle-plugin/issues/8 but did not find solutions, so what should I do to generate classes without modifying the proto file?

**Comment by zhangkun83** [comment]
Are their generated Java files also shared, or just the proto file?

**Comment by psionic12** [comment]
@zhangkun83 generated files are private, do you mean to give up the plugin and use protoc instead?

**Comment by zhangkun83** [comment]
No, the plugin supports either case. Either way the protos need to be included in the output of a subproject or an artifact (jar file), then you can put that subproject or artifact in the `protobuf` or `compile` of the project that imports those protos. [Protos in dependencies](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies) from the README explains this feature.

**Comment by psionic12** [comment]
It's not about dependencies. My report seems not clear enough, here's more details:

My proto files are placed in src/main/proto, in protos there are statements like this: `import "proto/push/push_message.proto"`. If I use the normal way to generate java classes, gradle will report not found proto/push/push_message.proto. Currently I change the proto file to `import "push/push_message.proto"` and this works fine. But the proto files are shared by another project, this means if I changed the proto file, the other side will get error due to file changed. In the old time, I use `--proto_path` in command line to set the path right, so the protoc will found the `proto/push/push_message.proto`. 

That's why I am asking if the plugin support `--proto_path` explicitly, or is there any way to fix the problem with out modify the proto files.

**Comment by zhangkun83** [comment]
No, the plugin doesn't allow you to specify `--proto_path` explicitly. I would suggest you update the other project to include the path in the `import` statement.

**Comment by callmeyesh** [comment]
Hi is this supported now?

**Comment by rougsig** [comment]
@codedragon76

You an use that semi-internal method to add any dir as --proto_path, be ready for api changes. 

https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L468
