### ISSUE TITLE
Plugin not adding to `sourceSets.main.java.srcDirs`

### ISSUE THREAD

**Issue by noel-yap** [google/protobuf-gradle-plugin#135]
This causes IDEs not to see the generated source. I'm wondering if that has to do with the following:

```
      protobuf {
        generateProtoTasks {
          all().each { task ->
            task.builtins {
              remove java
            }
          }
        }
      }
```

If so, is there a way to `remove java` but still have the output directories automatically added to `srcDirs` without explicitly doing it ourselves?

**Comment by zhangkun83** [comment]
If you are using IDEA, please refer to the bottom of the README for how to add generated files to source dirs.
I don't understand your snippet. If you don't generate anything, what generated source do you expect to see?

**Comment by noel-yap** [comment]
Another part of our `build.gradle` generates source. Both IDEA and Eclipse aren't seeing the generated source. This leads me to suspect that `protobuf-gradle-plugin` isn't adding the generated source directories at least under certain scenarios.

We've been able to workaround the issue by explicitly adding the Java generated source directories.

**Comment by zhangkun83** [comment]
`protobuf-gradle-plugin` is unlikely the culprit.
