### ISSUE TITLE
How to let native build run after protobuf compilation

### ISSUE THREAD

**Issue by liuyuan10** [google/protobuf-gradle-plugin#136]
My native ndk build depends on the protoc cpp output but gradle doesn't know about that so it sometimes runs ndk cmake build before running proto tasks. I think I can use gradle .dependsOn. What is the task name I should use for the protobuf compilation?

**Comment by zhangkun83** [comment]
The code generation tasks can be gotten by using the selectors in the `generateProtoTasks` block. For example:
```gradle
protobuf {
  ...
  generateProtoTasks {
    // all() returns the collection of all protoc tasks
    all().each { task ->
      ndkCompile.dependsOn task
    }
}
```
There are also [other selectors](https://github.com/google/protobuf-gradle-plugin#customize-code-generation-tasks).

**Comment by liuyuan10** [comment]
I made it work by

def tasksAfterProto = []
tasks.all { task ->
    if (task.name.startsWith('generateJsonModel')) {
          tasksAfterProto.push(task)
  }
}

protobuf {
    protoc {
        // The version must be the same as that of the prebuilt protobuf runtime
        // checked in with native code.
        artifact = 'com.google.protobuf:protoc:3.3.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
                cpp {
                }
            }
          tasksAfterProto.each {
            it.dependsOn task
          }
        }
    }
}
