### ISSUE TITLE
How to build cpp lite

### ISSUE THREAD

**Issue by liuyuan10** [google/protobuf-gradle-plugin#139]
Now I'm compiling proto for native cpp code as below:
```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.3.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
                cpp {
                }
            }
        }
    }
}
```

To have cpp-lite, I can add "option optimize_for = LITE_RUNTIME;" into .proto file. But can I achieve this without changing proto file? Sometimes the same proto file is used by multiple applications. I would like to change optimize for in gradle file.

FYI, protoc accepts option like "cpp_out=lite:dir" to force a lite code generation.

**Comment by zhangkun83** [comment]
To achieve "cpp_out=lite:dir", add one line to the `cpp{}` block:
```gradle
cpp {
  option "lite"
}
```

**Comment by liuyuan10** [comment]
Cool. This works. Thanks
