### ISSUE TITLE
If a Java dependency jar contains proto files, should extract them and add the extracted dir to --proto_path

### ISSUE THREAD

**Issue by zhangkun83** [google/protobuf-gradle-plugin#15]
The Protobuf release jars contain proto files for well-known types. The user may import these types in their own proto files, thus the well-known type proto files should be under a directory included in ``--proto_path``.

[maven-protoc-plugin](http://sergei-ivanov.github.io/maven-protoc-plugin/usage.html) is already doing so.

**Comment by mikhailmikhaylov** [comment]
Hello, we are currently using this framework in our project and encountered this issue.
We have a multi module project and each module can have it's own proto files. Proto files by themselves are depended on each other and on protoc's proto files (any.proto and others). And we can only workaround this by manually copying proto files into module.
Could you please let us know are there any plans to resolve this issue in the nearest future

**Comment by zhangkun83** [comment]
To clarify, this applies to Java dependencies, i.e., ``compile``, ``testCompile`` etc.
There are Protobuf dependencies, i.e.., ``protobuf``, ``testProtobuf`` etc, that simply contain proto files that will be compiled. This feature, however, is questionable (#25)

**Comment by zhangkun83** [comment]
There is an issue: if the depended protos and the dependent protos are compiled with different settings of option ``java_multiple_files``, class names for a same message will be different in the two projects. We have two options:
 1. We don't do anything about it. That requires all projects to have the same ``java_multiple_files`` setting, or there will be trouble.
 2. We add an option to allow recompiling the proto files. There may still be chance of name collision, e.g., if a message has the same name as the outer class (by default it's the proto file name).

Anyway, Option 2 sounds better than nothing.

**Comment by zhangkun83** [comment]
According to @pherl, `java_multiple_files` is available as command line option only for nano, users can always specify this option in proto files, and there won't be a problem if a proto imports another proto that sets this option differently. So this is less of a problem than I initially thought. Users should just avoid using the command line option and always use in-fine options.

**Comment by zhangkun83** [comment]
@mikhailmikhaylov @mmmdreg can you guys give version `0.5.1-SNAPSHOT` a try by adding the snapshot repository https://oss.sonatype.org/content/repositories/snapshots/ ?

**Comment by zhangkun83** [comment]
FYI 0.6.1 includes this feature and has been released on Maven Central.

**Comment by yaraki** [comment]
Is this feature available for protobuf-lite?

**Comment by zhangkun83** [comment]
No. protobuf-lite doesn't provide those well-known protos.

**Comment by ejona86** [comment]
@yaraki, https://github.com/google/protobuf/issues/1889
