### ISSUE TITLE
Include path doesn't seem to be correct

### ISSUE THREAD

**Issue by panzerfahrer** [google/protobuf-gradle-plugin#154]
It seems that my `proto` files don't get collected during generation. I keep getting errors like the following:

```
com/example/entity.proto: com/example/entity.proto: No such file or directory
```

While trying to debug what I might be doing wrong, I encountered the `protoc`parameter list. It includes paths to where `proto` files are expected, including `../src/main/proto`. The paths are prepended with `-I`. Cross-checking with `protoc --help` tells me that include paths should rather be prepended with `-IPATH`:

```
-IPATH, --proto_path=PATH   Specify the directory in which to search for
                            imports.  May be specified multiple times;
                            directories will be searched in order.  If not
                            given, the current working directory is used.

```

See also: [GenerateProtoTask.groovy#L372](https://github.com/google/protobuf-gradle-plugin/blob/54ee5dbbf30c8f3667ec93e3730f18807b78e56f/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L372)

I'm using protoc v3.3.0 from the maven artifact.

Can somebody please confirm whether I might be doing something wrong.

**Comment by zhangkun83** [comment]
No, `PATH` in `-IPATH` is not part of the flag name, but the place holder for the actual path.

**Comment by panzerfahrer** [comment]
Ok, that sounds reasonable. So, I'm doing something else wrong ;) Thanks for helping out so quick!
