### ISSUE TITLE
support for android feature plugin

### ISSUE THREAD

**Issue by mos8502** [google/protobuf-gradle-plugin#162]
Protobuf plugin currently does not support android feature modules (modules with "com.android.feature" applied. The protobuf gradle plugin hes the following plugin preconditions defined

```
private static final List<String> PREREQ_PLUGIN_OPTIONS = [
            'java',
            'com.android.application',
            'com.android.library',
            'android',
            'android-library',
    ]
```

Not sure if adding "com.android.feature" to the list is enough

**Comment by zhangkun83** [comment]
@rschiu, does it require any additional change to the protobuf plugin to work with the android feature plugin?

**Comment by rschiu** [comment]
I don't believe so, although I haven't tested it.  It should be sufficient to just add the feature plugin to the list.

**Comment by bacc4git** [comment]
Is this addition planned for future releases? I think that it's currently not possible to support Instant App for a module that uses protobuf plugin..or is there a way to do that?
