### ISSUE TITLE
0.8.3 dependency path is wrong.

### ISSUE THREAD

**Issue by SetoKaiba** [google/protobuf-gradle-plugin#163]
https://plugins.gradle.org/plugin/com.google.protobuf

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.3"
  }
}

apply plugin: "com.google.protobuf"
```

"gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.3" should be "com.google.protobuf:protobuf-gradle-plugin:0.8.3"

**Comment by SetoKaiba** [comment]
It makes the 0.8.3 can't be resolved.

Error:Could not find gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.3.
Searched in the following locations:
    file:/C:/Users/Seto/.m2/repository/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
    file:/C:/Users/Seto/.m2/repository/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.jar
    https://repository.jboss.org/nexus/content/groups/public-jboss/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
    https://repository.jboss.org/nexus/content/groups/public-jboss/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.jar
    https://jcenter.bintray.com/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
    https://jcenter.bintray.com/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.jar
    https://plugins.gradle.org/m2/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
    https://plugins.gradle.org/m2/gradle/plugin/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.jar

**Comment by zhangkun83** [comment]
Wow, never noticed that. The path in the snippet on the plugins.gradle.org page is always like this, which seems to be wrong. While I don't know why it happens, you can definitely use the path in `README.md`.

**Comment by SetoKaiba** [comment]
But for 2.1+, I use the code below. It doesn't work. Because it use the plugins.gradle.org data.
It's working with 0.8.2. So I thought it's a mistake when updating 0.8.3.
```
plugins {
  id "com.google.protobuf" version "0.8.3"
}
```
The code below is working. Only problem occurs with 0.8.3.
```
plugins {
  id "com.google.protobuf" version "0.8.2"
}
```

**Comment by timyates** [comment]
I think I know the issue

You're using the gradle publishing plugin:

```
        classpath "com.gradle.publish:plugin-publish-plugin:0.9.5"
```

Unfortunately, we had a bug in `v0.9.5` that sometimes the artifacts would silently not be published to the repository 😢   This was fixed in `0.9.7` of the `plugin-publish-plugin`

Please can you update to `v0.9.8` (the latest), and re-publish?  I can remove `v0.8.3` of your plugin if you want me to, so you can re-publish the same version?  Or you can publish a new v0.8.4, and I will remove the faulty 0.8.3 when you're done?

Sorry about this...

Tim

**Comment by SetoKaiba** [comment]
@zhangkun83 Could you please help?

**Comment by zhangkun83** [comment]
@timyates yes, please delete 0.8.3 for me and I will re-publish.

**Comment by timyates** [comment]
Will do. :+1:

Away from computer now, but it should be done in 30 mins or so... 

Will post here when it's done

**Comment by timyates** [comment]
@zhangkun83 `0.8.3` removed, you should be able to re-publish

**Comment by zhangkun83** [comment]
I have re-published. @SetoKaiba, does it work now?

**Comment by SetoKaiba** [comment]
Thank you. It's working. It's ok to close this issue now.
