### ISSUE TITLE
Android Studio Canary issues

### ISSUE THREAD

**Issue by Ramithags** [google/protobuf-gradle-plugin#164]
Hello All,

Am facing some weird issue after updating to Android Studio Canary version.
When ever I tried to run test cases am facing below exception. But once I clean my Gradle it works, but every time clean my Gradle kind of tedious task. 
Error:Execution failed for task ':Path:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug'.
> java.io.IOException: Failed to delete D:\Projects\Path\build\intermediates\intermediate-jars\debug\classes.jar

Can some body help me get rid of this?

**Comment by zhangkun83** [comment]
Is it related to the protobuf plugin, or just an android plugin issue?

**Comment by Ramithags** [comment]
It's just an android plugin issue I hope.

**Comment by zhangkun83** [comment]
@rschiu, what is the proper channel to report Android plugin issues?

**Comment by rschiu** [comment]
issuetracker.google.com/issues/new?component=192709&template=842921
