### ISSUE TITLE
exec protoc Permission denied

### ISSUE THREAD

**Issue by linsea** [google/protobuf-gradle-plugin#165]
I run the build on jenkins encounter this error:

* What went wrong:
Execution failed for task ':client:generateDebugProto'.
> java.io.IOException: Cannot run program "/tmp/__ci_gradle/modules-2/files-2.1/com.google.protobuf/protoc/3.4.0/5cd3ac047470c9e09c2fa49a9378c341456a69d2/protoc-3.4.0-linux-x86_64.exe": error=13, Permission denied

p.s. my config:
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protoc_version}"
    }
    plugins {
        javalite {
            artifact = "com.google.protobuf:protoc-gen-javalite:${protoc_gen_javalite_version}"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
            }
        }
    }
}
```

**Comment by ejona86** [comment]
Is it possible /tmp is mounted with noexec? Can you run:
```
mount | grep /tmp
```

If so, I'd suggest swapping to /var/tmp for the gradle home.

**Comment by linsea** [comment]
found the reason, we run the build on docker, where restrict executable running, with the adminitrator's help, now it's OK.

**Comment by frosiere** [comment]
@linsea, would it be possible to have a bit more details about the update you did on the Docker side? Thanks.

**Comment by jpmcb** [comment]
@frosiere @linsea were you able to solve this for docker? I'm getting the same file with permission denied with a docker build

**Comment by chiefy** [comment]
@jpmcb I was having an issue with this trying to get a project built inside docker on OSX (volume bind-mounted), changed the Gradle build to use `/tmp` inside the container and it fixed the issue.
