### ISSUE TITLE
Large number of proto files leads to generate failure on Windows

### ISSUE THREAD

**Issue by mbelling** [google/protobuf-gradle-plugin#167]
Windows has a relatively small command line length.  We have a lot of proto files.  When the plugin tries to make the call to generate, we get an error because the command line that the plugin tries to call is too long.  When I printed out debug logging, I saw it was because it places each proto file on the command line.

Is there a way that a directory can be used instead of listing every proto file on the command line?  That way a directory can be passed to the command instead of a huge amount of file paths.

Edit, adding in the protoc used:
`protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.3.0'
    }
}`

**Comment by mbelling** [comment]
As I did more digging, I realized this may be a limitation of the protoc compliler:

https://github.com/google/protobuf/issues/274

**Comment by mbelling** [comment]
It looks like https://github.com/google/protobuf/issues/274 has been fixed in 3.5.0+.

**Comment by zhangkun83** [comment]
Consider it fixed by #174
