### ISSUE TITLE
Calling a pure Java plugin

### ISSUE THREAD

**Issue by cbornet** [google/protobuf-gradle-plugin#168]
With the protobuf-maven-plugin, it's possible to execute [pure Java plugins](https://www.xolstice.org/protobuf-maven-plugin/examples/protoc-plugin.html)
Would it be possible to do it with the gradle plugin also : I want to use a plugin that is made to use this feature with gradle.

**Comment by cbornet** [comment]
I've read #31 but it only partially solves the issue as an executable jar still needs to be available whereas the protobuf-maven-plugin builds the executable from the jar at compile time.

**Comment by venth** [comment]
Version 0.8.3 allows to declare jar plugin by using constant classifier (e.g. `jvm8`) and extension (e.g. `@jar`). Unfortunately such declaration of proto plugin isn't sufficient. 

I have protobuf declaration as follows:
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.3.0"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.6.1"
        }
        rxgrpc {
            artifact = "com.salesforce.servicelibs:rxgrpc:0.6.1.gradle:jvm8@jar"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {
                // To generate deprecated interfaces and static bindService method,
                // turn the enable_deprecated option to true below:
                option 'enable_deprecated=false'
            }
            rxgrpc {}
        }
    }
}
```

I've installed locally [rxgrpc](https://github.com/salesforce/grpc-java-contrib) with classfier: `jvm8` and version: `0.6.1.gradle`.

Rxgrpc plugin is properly resolved. Unfortunately gradle plugin cannot execute it finishing with the below message:

```
.../.m2/repository/com/salesforce/servicelibs/rxgrpc/0.6.1.gradle/rxgrpc-0.6.1.gradle-jvm8.jar: program not found or is not executable
  --rxgrpc_out: protoc-gen-rxgrpc: Plugin failed with status code 1.
```

`ls -l` indicates that jar file exists.

```
-rwxr--r--  1 ...  ...   9.0K Nov  7 07:54 .../.m2/repository/com/salesforce/servicelibs/rxgrpc/0.6.1.gradle/rxgrpc-0.6.1.gradle-jvm8.jar
```

How can I convince gradle plugin to execute jar? Can I do it by adding a separate task with execJava as a workaround?

**Comment by Scottmitch** [comment]
In ServiceTalk we work around this as follows:

1. java code for protoc plugin packaged to uber jar
2. custom gradle plugin (sits on top `protobuf-gradle-plugin`) that [dynamically generates a trampoline script](https://github.com/apple/servicetalk/blob/master/servicetalk-grpc-gradle-plugin/src/main/groovy/io/servicetalk/grpc/gradle/plugin/ServiceTalkGrpcPlugin.groovy#L102-L113) (based upon OS) to execute the jar file (e.g. `protoc --plugin=protoc-gen-servicetalk_grpc=<sub-project build dir>/servicetalk-grpc-protoc.[sh|bat]`)

However I don't think `protobuf-gradle-plugin` was designed to "build a plugin on top" approach and there are some initialization/sequencing issues, and can be conflicts if someone manually `protobuf-gradle-plugin`. We used the same approach as https://github.com/salesforce/reactive-grpc/issues/21#issuecomment-347282217 in the past but it isn't cross platform so we switched to a consistent "script->execute jar" approach.

Question for the maintainers ... would you be willing to accept a contribution for this type of "trampoline" for `jar` artifacts?

**Comment by Scottmitch** [comment]
I've submitted a PR here for review/discussion: https://github.com/google/protobuf-gradle-plugin/pull/422

**Comment by ejona86** [comment]
CC @rmichela

**Comment by mahieddine** [comment]
How can we specify the mainClass though ?

**Comment by Scottmitch** [comment]
https://github.com/google/protobuf-gradle-plugin/pull/423 added support for Uber-jars (package all classes inside a single jar, and indicate the main class in the meta data). Here is an example of how [ServiceTalk builds this type of artifact via gradle](https://github.com/apple/servicetalk/blob/main/servicetalk-grpc-protoc/build.gradle#L43), and an [example of how it can be used](https://github.com/apple/servicetalk/blob/main/servicetalk-examples/grpc/helloworld/build.gradle#L45).

**Comment by mahieddine** [comment]
@Scottmitch yes but if the mainClass is not specified in the manifest there is no way to specify the mainClass or am i missing something?

**Comment by Scottmitch** [comment]
afaik this plugin doesn't (yet) support specifying a `mainClass`.
