### ISSUE TITLE
Output Ruby gRPC & Protobuf

### ISSUE THREAD

**Issue by bootstraponline** [google/protobuf-gradle-plugin#177]
Support for gRPC generation seems limited. How do I make Ruby generate gRPC? This is the command that works from the CLI:

> grpc_tools_ruby_protoc --ruby_out=src/main/ruby/ --grpc_out=src/main/ruby/ soseedy.proto

I don't see a way to achieve this via the plugin.

```gradle
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.4.0'
    }

    generatedFilesBaseDir = "$projectDir/src"

    plugins {
        // https://rubygems.org/gems/grpc-tools
        ruby { path = 'grpc_tools_ruby_protoc' }
    }

    generateProtoTasks {
        all().each { task ->
            task.plugins {
                // grpc_tools_ruby_protoc --ruby_out=src/main/ruby/ --grpc_out=src/main/ruby/ my.proto
                ruby {
                }
            }
        }
    }
}
```

**Comment by zhangkun83** [comment]
[`grpc_tools_ruby_protoc`](https://github.com/grpc/grpc/blob/master/src/ruby/tools/bin/grpc_tools_ruby_protoc) is just a wrapper for `protoc`. In the `plugins {}` block, you should instead specify the path to the actual ruby plugin, which is pointed to by `plugin_path` in the linked script. Fill in that path to the `plugins {}` block and try again.

**Comment by bootstraponline** [comment]
Thanks. I ended up writing a shell script since I couldn't get this plugin to work for multiple languages & gRPC. If this is a supported use case, then some basic examples would be wonderful.

- https://github.com/instructure/test_advisory_board/blob/master/grpc/generate.sh

**Comment by timdawborn** [comment]
FWIW in case anyone else finds this GitHub issue in the same way I did, I managed to get this idea to work with the following workaround.

I defined a plugin that hits a local shell script. The plugin is named `grpc<language>`. The shell script's job is to exec the appropriate `grpc_tools_<language>_protoc_plugin` executable, proxying the arguments. The name of this plugin cannot be simply "<language>", as the name of the plugin becomes a `--<language>_out` argument to `protoc`, and if you want the gRPC output in addition to the protobuf output, you need a way to trigger both `--<language>_out` and `--grpc_out` arguments.

```kotlin
protobuf {
    plugins {
        id("grpcRuby") {
            path = "$projectDir/scripts/generate-ruby-grpc.sh"
        }
    }
```

My `scripts/generate-ruby-grpc.sh` script is:
```
#!/bin/sh
set -u
shift
exec bundle exec grpc_tools_ruby_protoc_plugin $@
```

This makes the `--grpcRuby_out` argument passed to `protoc` invoke the `scripts/generate-ruby-grpc.sh` script as a protoc plugin, which in turn just invokes the Ruby gRPC plugin.

It's not particularly pretty, but it works.
