### ISSUE TITLE
google/protobuf-gradle-plugin is forked from personal repo and unsearchable

### ISSUE THREAD

**Issue by brunobowden** [google/protobuf-gradle-plugin#18]
@aantono

It's currently impossible to search the protobuf-gradle-plugin directory as it's a parent of @aantono's public directory - this is a limitation of GitHub (see screenshot below). By following the help system, you can make a request to GitHub to remove this as a parent. I've done this before successfully by making the request, so it does work. This will be helpful for two reasons:

1. A Google project should not be a fork from a personal project. It's bizarre to see that.
1. In the request, please ask GitHub to enable searching for this repository. Hopefully that should be automatic or easy for them to do.

An alternative to try is @aantono to delete his public repository... but that may result in another repository that was a fork of @aantono to become the new "parent". It depends on when the accounts were created.

**Comment by brunobowden** [comment]
It doesn't look like any of the other repo's have a parent, so @aantono, it may work to delete your personal repository then recreate it by forking from the public Google project.

**Comment by zhangkun83** [comment]
I will contact our internal github admin to see if he can help.

**Comment by brunobowden** [comment]
If you just file a support ticket they can do it for you. That's what I did.

**Comment by zhangkun83** [comment]
Github customer service helped break up the connection.
