### ISSUE TITLE
Proto files under 'src/test/proto' not compiled to Java

### ISSUE THREAD

**Issue by liuyan82** [google/protobuf-gradle-plugin#181]
In my android project, my protobuf test cases is under src/test/proto, they are not complied automatically. While my proto files under 'src/main/proto' can be compiled.

**Comment by liuyan82** [comment]
Seems proto file under 'src/androidTest/proto' will not compiled either.

**Comment by zhangkun83** [comment]
For Android project the default test source directory is `src/androidTest`. What is `src/test` used for? (I know very little about Android build, so there may be something I have missed).

**Comment by liuyan82** [comment]
Unit test unger 'src/test' is for Tests not quite rely on Android Libraries, and it runs on PC, rather than cell phones or emulators. These run much fast than those on cell phones. Some open source project like RobolectricTestRunner supplies basic Android environment for 'src/test', making it possible to run some Android test in 'src/test'

**Comment by zhangkun83** [comment]
@rschiu , my understanding is that the Android plugin defines its own sourcesets. Should we support the user-defined `src/test` in the `android {}` block or the one outside?

**Comment by rschiu** [comment]
I am not sure what you mean by "in the android {} block or the one outside".  src/test is a feature of Android plugin for unit testing.  I imagine support for "src/test/proto" should be similar to how "src/androidTest/proto" is supported.

**Comment by zhangkun83** [comment]
My understanding is that each variant is a compilation unit, and the plugin uses `variant.registerJavaGeneratingTask` to link the protoc tasks with the Java compilation tasks for the variants. How does `src/test` fit in this model? Is it a variant by its own, or something other than variant?

**Comment by rschiu** [comment]
It is its own variant in the way there is a variant for androidTest.  I don't remember the protobuf plugin code, but I am guessing there is a call to registerJavaGeneratingTask for the variant with type VariantType.ANDROID_TEST?  You should be able to do the same for VariantType.UNIT_TEST.

**Comment by zpencer** [comment]
Looks like this is the case according to the official android docs:
https://developer.android.com/studio/test/index.html
