### ISSUE TITLE
Dex merging fails with Gradle 3 and lite protos

### ISSUE THREAD

**Issue by kantoniak** [google/protobuf-gradle-plugin#182]
[build.gradle.txt](https://github.com/google/protobuf-gradle-plugin/files/1464704/build.gradle.txt)
[build.log](https://github.com/google/protobuf-gradle-plugin/files/1464705/build.log)

I installed Android Studio 3 and tried to build project with Gradle 3 which now Studio uses. The build fails in dex merging stage:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
    [...]
Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
    [...]
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/google/protobuf/TextFormatEscaper$ByteSequence;
    [...]
```
Studio tells me that `TextFormatEscaper` class is provided in both `protobuf-java:3.4.0` and `protobuf-lite:3.0.1`. This multiple definition had not been occurring before I started using Android Studio 3 with Gradle 3. Shall I update the gradle setup or is there some problem with Gradle 3 compatibility?

The project uses lite protos and generates grpc endpoints. Full log and `build.gradle` attached.

**Comment by ejona86** [comment]
You need to exclude `protobuf-java` or avoid what's pulling in that dependency. Take a look at the dependency tree and see where protobuf-java is coming from (I tried to check your build file, but I also needed the parent build file as well):
```
$ ./gradlew dependencies --configuration=compile
```

**Comment by kantoniak** [comment]
I had to exclude `protobuf-lite` from `grpc-protobuf-lite`: https://github.com/kantoniak/green-deer/commit/689a2a3985e905561d27e88c504301338f79ce5e#diff-39e7d8c00954e920b98e7636f0ac30b2R43

Thank you for your help.

**Comment by ejona86** [comment]
@kantoniak, oh, I didn't notice you really wanted full protobuf. Instead of depending on `io.grpc:grpc-protobuf-lite:1.7.0` depend on `io.grpc:grpc-protobuf:1.7.0`.

**Comment by kantoniak** [comment]
Oh, maybe I solved another problem. I would like to use lite protos everywhere, and my last change seems to work fine with server built in lite flavor (https://github.com/kantoniak/green-deer-server/blob/master/build.gradle).

I also attach parent `build.gradle` of Android app, maybe you can advise me any changes.
 [build.gradle.root.txt](https://github.com/google/protobuf-gradle-plugin/files/1471958/build.gradle.root.txt)
