### ISSUE TITLE
Gradle sync failed: Timeout waiting to lock file hash cache  

### ISSUE THREAD

**Issue by YogeshDeveloper** [google/protobuf-gradle-plugin#183]
Gradle sync fails and the following issue occurs. 

Gradle sync failed: Timeout waiting to lock file hash cache. It is currently in use by another Gradle instance.
			Owner PID: 10116
			Our PID: 9800
			Owner Operation: 
			Our operation: 
			Lock file: C:\Users\HELLO\.gradle\caches\4.1\fileHashes\fileHashes.lock
			Consult IDE log for more details (Help | Show Log) (1m 2s 366ms)

**Comment by zhangkun83** [comment]
Doesn't seem related to the protobuf plugin.
