### ISSUE TITLE
Support to pass plugin options using --[name]_opt 

### ISSUE THREAD

**Issue by panzerfahrer** [google/protobuf-gradle-plugin#184]
I'm trying to use plugins that expect options passed via the `--[name]_opt` argument. From what I can see in [GenerateProtoTask.groovy](/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy) only additional options to the `--[name]_out` argument are supported.

Is there already a way to pass options via the `--[name]_opt` argument? If not, could this be supported?

**Comment by ejona86** [comment]
_opt? What's that... Oh, looks like it was added a year ago: google/protobuf#2284 . It appears _opt is equivalent to using the previous syntax with _out, based on [this documentation](https://github.com/google/protobuf/blob/fa5a69e73b0dd667ff15062adbc170310d440ee9/src/google/protobuf/compiler/command_line_interface.h#L174). Have you tried using the _out-based options and see if they work?

**Comment by panzerfahrer** [comment]
Oh, it actually works :) So, I guess there is nothing to do (maybe a hint in the docs)?
