### ISSUE TITLE
"You don't have permission to use the application 'protoc-3.4.0-osx-x86_64.exe'" gradle

### ISSUE THREAD

**Issue by crilofer** [google/protobuf-gradle-plugin#185]
Hi,

I am trying to build my application that uses protocol buffers. But I am getting the error shown in the screenshot attached.

![screen shot 2017-11-15 at 12 49 24](https://user-images.githubusercontent.com/6973711/32837579-01d10c94-ca06-11e7-8221-e04fe02a511f.png)

This file has 777 permissions.

Thanks.

**Comment by zhangkun83** [comment]
Are you able to run the file from command line with option `--version`?

**Comment by crilofer** [comment]
Yeah, I solved specifying the protoc path.
But now I have different problem:

<img width="451" alt="screen shot 2017-11-20 at 10 34 53" src="https://user-images.githubusercontent.com/6973711/33014264-a5cc39d2-cdde-11e7-8222-16a2791514ae.png">

Thanks.

**Comment by zhangkun83** [comment]
1.0.0-pre2 is pretty old, though it should work anyway.
Please check the permissions of the second file, and try running it from command line. You can find it under `~/.gradle/caches`.

**Comment by crilofer** [comment]
I have also tried with 1.7.0 and I got the same result. The second file has 777 permissions.

How could I run from command line?

Thanks!

**Comment by zhangkun83** [comment]
You just run it like an executable. It gives out no output and just wait for standard input, and you can `Ctrl+C` to exit.

**Comment by crilofer** [comment]
This is the result:

<img width="1221" alt="screen shot 2017-11-20 at 20 05 57" src="https://user-images.githubusercontent.com/6973711/33038958-496965ac-ce2e-11e7-9a2f-419d8177a45a.png">

**Comment by zhangkun83** [comment]
Did you try removing the `sudo`?

**Comment by crilofer** [comment]
<img width="1110" alt="screen shot 2017-11-20 at 21 31 20" src="https://user-images.githubusercontent.com/6973711/33042581-35c7f750-ce3a-11e7-88c5-29c2108b6349.png">

The file has 777 permissions and I have admin rights

**Comment by zhangkun83** [comment]
Seems OSX forbids the execution of this file despite its permissions being 777. You can try to get help from OSX supporting resources, but this is not a problem of the protobuf plugin.
