### ISSUE TITLE
Not able to specify the output directory for generated java files

### ISSUE THREAD

**Issue by minaevd** [google/protobuf-gradle-plugin#190]
Hi there,

I'm struggling with specifying output directory for protobuf generated java files files. I want to put it under gen-src, instead of gen-src/main/java.

If I set generatedFilesBaseDir to "gen-src" it outputs to gen-src/main/java. I can additionally set outputSubDir to '.' (current folder) and then it puts it to gen-src/main/
However I can't set outputBaseDir to '.' to eliminate "main" from path.

Please let me know if there is a way to achieve that.

My current workaround is to set outputSubDir to a parent folder via (`..`):

```
protobuf {
    generatedFilesBaseDir = "$projectDir/gen-src"
    ...
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    if(task.getName() == 'generateProto') {

                        // to avoid "no such folder" error when setting outputSubDir
                        println("Creating directory gen-src/main")
                        def mainDir = new File('gen-src/main')
                        mainDir.mkdirs()

                        println("Setting outputSubDir = '..'")
                        outputSubDir = '..'
                    }
                }
            }
        }
```

Thank you,
Dmitry

**Comment by zhangkun83** [comment]
It's necessary for the plugin to put the generated Java files in directories that correspond to sourceSets, because those files will be compiled along with the Java source files from the corresponding sourceSets, and we don't want the generated files from different sourceSets to be mixed. Why do you want that specific directory?

**Comment by minaevd** [comment]
I just want to have packages right under the gen-src/ folder. I don't want to have extra folders like main/java. I have other build processes that generate code and put it under gen-src/ folder. And I don't want to have separate structures for generated code, one with main/java and another with just packages. Hope that makes sense.

--
Dmitry

**Comment by zhangkun83** [comment]
The protobuf plugin doesn't support such behavior. I don't believe it's a good idea to mingle the output from different sources.

Ideally, if the generated files are the input of your own compilation task, it makes more sense for the compilation task to include multiple directories as input, say, both `gen-src` and `$generatedFilesBaseDir/main/java`. If it's not possible, you may consider creating your own task to copy the generated files to your desired location.

**Comment by Ronziod** [comment]
Hello,

I agree it's not a good idea to mingle different sources. However, being able to override main/java to be something else would still be a helpful feature. There are lots of legitimate reasons you may want to generated files to go elsewhere. Even other commonly supported sourceset naming conventions:
gen/java
main/java-gen
java

Thanks

**Comment by chrismiller** [comment]
We don't want a "main" directory either. Across all our many Gradle projects, for somewhat legacy reasons, we do not use "main" anywhere in the directory paths that our various sources live in. Not being able to specify the output directory of the protobuf plugin means we need some special casing for protobuf generated code.

**Comment by zhangkun83** [comment]
It's a really bad idea to mingle different sourcesets. If we do that, java compilation may accidentally include generated files from unwanted sourcesets. Does it cause you real problems, or it's just an cosmetic issue?

**Comment by NikolayMetchev** [comment]
I agree it's a bad idea. If however you only have one source set you should not be forced to conform. On the whole Gradle tries not to be opinionated. This restriction seems opinionated to me

**Comment by bickelj** [comment]
It would be really nice to be able to specify exactly the source path. Agree with @NikolayMetchev that the plugin should not be forcing us to use certain paths. Gradle does not force us to use certain paths, nor do other plugins.

**Comment by eduardhasanaj2** [comment]
@zhangkun83  is there any possibility to define parent folder generatedFilesBaseDir?
I am creating a plugin for flutter and putting gen folder to original android plugin seems impossible.
Best regards

**Comment by zhangkun83** [comment]
@eduardhasanaj2 can you elaborate why you need to specify it? The plugin should connect the generated files with Java/Android plugin's sourceSets, so that you don't need to do it manually. I would not be surprised if there is a setup in which it doesn't work that way.

**Comment by eduardhasanaj2** [comment]
@zhangkun83  I am sorry but I was missing the fact that generated files of plugin would go to generated folder of plugin and not app. I was so stupid
