### ISSUE TITLE
IntelliJ: proto source directory not recognized

### ISSUE THREAD

**Issue by panzerfahrer** [google/protobuf-gradle-plugin#199]
In my setup, the `src/main/proto` directory is not recognized as a source directory by IntelliJ.
I was able to circumvent this by manually adding the following to my `build.gradle`:

```
idea {
    module {
        sourceDirs += file("src/main/proto")
    }
}
```

~Could this be related and solved by #104 ? If so, I'd like to offer help to get the conflicts solved and PR merged.~ _Edit: #104 got closed after this. Should this be tackled with #193 or #198 (and possibly be available with an upcoming release)?_

Environment:
- plugin 0.8.3
- Gradle 4.3.1
- IntelliJ 2017.3

**Comment by zpencer** [comment]
The feature is complete will be available in the next release. @zhangkun83 and I will determine if there's anything else we want to include and do one in the near future.
