### ISSUE TITLE
Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins

### ISSUE THREAD

**Issue by caxton** [google/protobuf-gradle-plugin#20]
I simply added protobuf setting in build.gradle, and got the error "Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins". 

(Android Studio version 1.2.2).

build.gradle:
```groovy
apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "com.google.protobuf:protobuf-gradle-plugin:0.4.1"
    }
}

repositories {
    jcenter()
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

android {
...
```

**Comment by ejona86** [comment]
Issue #11 is for not working with the android plugin. You can follow that issue for learning about the progress in fixing the problem.
