### ISSUE TITLE
Ability to customize output directory without the sourceset name in there.

### ISSUE THREAD

**Issue by NikolayMetchev** [google/protobuf-gradle-plugin#202]
I would like the output directory for protobuf compiler to be:
src/generated/java

however the plugin currently hard codes the source set name in the output directory and it becomes:
src/generated/main/java

**Comment by zhangkun83** [comment]
Please see [my response](https://github.com/google/protobuf-gradle-plugin/issues/190#issuecomment-347273434) on #190.
