### ISSUE TITLE
Error:Execution failed for task ':app:generateDebugProto'.

### ISSUE THREAD

**Issue by yoss1994** [google/protobuf-gradle-plugin#216]
Hi everyone,
I'm new with protobuf and I got this problem while generating proto in android

Error:Execution failed for task ':app:generateDebugProto'.
> protoc: stdout: . stderr: C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-protos\main: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-include-protos\main: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-protos\main: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-include-protos\main: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\src\debug\proto: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-protos\debug: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-include-protos\debug: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\src\debug\proto: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-protos\debug: warning: directory does not exist.
C:\Users\W.S.I\AndroidStudioProjects\ProtobufTest\app\build\extracted-include-protos\debug: warning: directory does not exist.
--javalite_out: information.proto: information.proto: Cannot generate Java output because the file's outer class name, "DataProto", matches the name of one of the types declared inside it.  Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file.

Java lite package doesn't contain any file
![protobuf](https://user-images.githubusercontent.com/34320969/37023781-43206faa-2127-11e8-80d0-344816205b15.png)
Could anyone kindly help me!

**Comment by zhangkun83** [comment]
The error message is quite clear: "information.proto: information.proto: Cannot generate Java output because the file's outer class name, "DataProto", matches the name of one of the types declared inside it. Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file."

**Comment by yoss1994** [comment]
thank you very much! It works
