### ISSUE TITLE
Update Incremental Build when Plugin files change

### ISSUE THREAD

**Issue by isupeene** [google/protobuf-gradle-plugin#218]
I'm using this plugin in an Android project with a custom protoc plugin.  The plugin is in Python with a batch script wrapper, and is in my project directory under 'plugins/'.  When the .py or the .bat file is changed, I want Gradle's incremental build to recognize that an input has changed and rerun protoc.  However, I don't see any way to do that with this plugin.

It would be great if we could specify plugin files as part of the incremental build cache key so that I don't have to do a full rebuild every time I change my plugin.

**Comment by ejona86** [comment]
This was fixed by https://github.com/google/protobuf-gradle-plugin/pull/408 . Note that only your `.bat` is seen by Gradle, so you would need to add an explicit task dependency for the .py and or files.
