### ISSUE TITLE
How do i change the outputSubDir in builtins?

### ISSUE THREAD

**Issue by husnjak** [google/protobuf-gradle-plugin#226]
I do not want to use the standard sub folders: 
main -> java-> proto

I only want to hav the last one but cannot figure out how to to it in builtins, as is said to work in the readme. 

Code example: 
```
generateProtoTasks {
        ofSourceSet('main').each { task ->
            task.builtins {
                outputSubDir =  'proto'
            }
        }
    }
```
getting an error on `outputSubDir`

What am i doing wrong?

**Comment by zhangkun83** [comment]
The default should be `build/generated/source/proto/main/java`. The `build/generated/source/proto` part can be changed by:
```gradle
protobuf {
    generatedFilesBaseDir = ...
}
```
The `java` part can be changed by:
```gradle
generateProtoTasks {
        ofSourceSet('main').each { task ->
            task.builtins {
                java {
                   outputSubDir =  'proto'
                }
            }
        }
    }
```
Hope this answers your question.

**Comment by zpencer** [comment]
This looks resolved, please re-open if you still need help.
