### ISSUE TITLE
Incremental build seems not working

### ISSUE THREAD

**Issue by zhangkun83** [google/protobuf-gradle-plugin#23]
I encountered an issue where I built a project once, which failed because an error in a proto file, I then fixed the proto file and tried to build it again (without clean), and the proto file was not re-compiled.

**Comment by ejona86** [comment]
I am 99% sure that is because we changed the proto dependency. Gradle doesn't detect that we changed our dependency and thus it wasn't rebuilt. I think this is just a Gradle limitation and not much can/should be done from our end.

**Comment by zhangkun83** [comment]
This is a different issue, not related to dependencies.

**Comment by zhangkun83** [comment]
I am unable to reproduce it in the test projects based on the memory of how I ran into this. Might be a false alarm.
