### ISSUE TITLE
Please document how to generate Python sources

### ISSUE THREAD

**Issue by massenz** [google/protobuf-gradle-plugin#230]
Reading #13, it states that setting this:
```
sourceSets {
  main {
    proto {
      builtins {
        python {
        }
      }
    }
  }
}
```
_should_ generate python sources too; but I get an error:
```
A problem occurred evaluating root project 'ServerlessProtos'.
> Could not find method builtins() for arguments [build_7w3n39f0fdfgkgnm0to8jwh56$_run_closure6$_closure9$_closure10$_closure11@6ad993e4] on main Proto source of type com.google.protobuf.gradle.ProtobufSourceDirectorySet.
```
Be that as it may - this is, to say the least, non-intuitive.

How difficult would it be to have something like:
```
protobuf {
  ...
  generatePython = true
}
```
or something to that effect?

I am perfectly capable of creating a bash script to do both, but it would be nice to just run `./gradlew install` and have both Java/Python generated.

Thanks!

**Comment by zhangkun83** [comment]
The syntax from #13 is outdated. With the latest version of the plugin, you don't specify output in the sourceSets, but in the `generateProtoTasks` block. The minimal code would be:
```gradle
protobuf {
  generateProtoTasks {
    // all() returns the collection of all protoc tasks
    all().each { task ->
      task.builtins {
        remove java
        python { }
      }
    }
  }
}
```

**Comment by massenz** [comment]
Thanks.
This issue was, in fact, about actually documenting this (I was just pointing out that searching around for suggestions, that was all I could find).

Unless you tell me it's a bad idea, I'd like to add that info to this project's README and submit a PR: would that be ok?

**Comment by zhangkun83** [comment]
It is already documented. Try searching for "python" in the current README. Feel free to make a PR if you find anything that can be improved.
