### ISSUE TITLE
"./gradlew clean" should remove files from generated source dirs

### ISSUE THREAD

**Issue by edenman** [google/protobuf-gradle-plugin#24]
I'm setting `generatedFilesBaseDir = "$projectDir/src/generated"` so IntelliJ can more easily recognize my generated proto .java files as sources.  When I re-generate these files, I want a `clean` to remove them (in case I renamed a class with `java_outer_classname`, for instance)

**Comment by edenman** [comment]
Workaround is just to augment the clean task:

**Comment by zhangkun83** [comment]
I am concerned about the safety of this feature. Because `generatedFilesBaseDir` can point to any directory, even outside of the project and may contain other non-generated files, deleting it indistinguishably can be dangerous. I would expect IntelliJ should allow you to specify sources under the `build` directory. If it's not the case, your workaround seems fine.

**Comment by edenman** [comment]
imho:

- If you point `generatedFilesBaseDir` outside your project, you deserve to have that directory deleted.  What even would be the point of that?
- If you point `generatedFilesBaseDir` at a directory inside your project and it contains other non-generated files, what even would be the point of that?  Also, that's what version control is for.

**Comment by zhangkun83** [comment]
> If you point `generatedFilesBaseDir`at a directory inside your project and it contains other non-generated files, what even would be the point of that?

I can imagine some people pointing `generatedFilesBaseDir` to `$projectDir/src/` for convenience. Maybe it's not necessary at all, but people may think it is and do it anyway. This may lead to deleting their own sources. Yes we have version control, but you may still lose local edits and sometimes it's siginificant loss.

Technically you are right, but people make mistakes, and I don't want their trivial mistakes to easily turn into accidents.

In general, I don't want to encourage the practice of putting generated files outside of `build`. Files generated in the build process _should_ stay inside `build`. It's fine that you have a good reason and you want to do it anyway, but it's not the norm that we want to support.

**Comment by Shad0w1nk** [comment]
If it's not recommended, why not deprecate the possibility. That way the problem will not be present. 

For a possible solution, Gradle would have to know how, in term of file path, protoc is transforming the inputs. This would enable incremental compilation as we would know which files to remove when a proto file is deleted to keep everything up to date. Saving the processed information in a temporary file would enable both incremental compilation and cleaning. The only problem is the duplicate information between protoc and Gradle. If we can get the knowledge from protoc, then it wouldn't be a problem. Let me know what you guys think.

**Comment by zhangkun83** [comment]
Let's move the discussion to #33

**Comment by sindhuvyshaki** [comment]
This is a valid bug. At any cost, jooq clean task should not delete existing source files. I cannot reopen this bug. Perhaps I will file a new one.
