### ISSUE TITLE
Support For `implementation` Dependency Configuration

### ISSUE THREAD

**Issue by dmdashenkov** [google/protobuf-gradle-plugin#242]
As the `README` [says](https://github.com/google/protobuf-gradle-plugin/tree/master#protos-in-dependencies), it's required to use `compile` dependency configuration in order to link `.proto` dependencies. However, the configuration is [deprecated](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) now.

Could we expect support for the `implementation` and `api` (from the `java-library` plugin) for those purposes?

**Comment by zpencer** [comment]
In our tests, I verified that changing `compile` to `api` or `implementation` still works. 

I did notice that things like `protobuf files("lib/protos.tar.gz")` may cause problems in the new version of gradle. It allows users to add proto files directly into the configuration, and I suspect it just has the equivalent behavior of `api`. If so, we need a way to let people add proto files without exposing them downstream transitively.

**Comment by dmdashenkov** [comment]
Thanks for the answer, @zpencer. Could you please link the test so I can compare it to my config and find out why does it work for you, but not for me?

**Comment by zhangkun83** [comment]
@zpencer Sounds like we need something like "implementationProtobuf" and "apiProtobuf".

**Comment by zpencer** [comment]
@dmdashenkov try changing https://github.com/google/protobuf-gradle-plugin/blob/master/testProjectDependent/build.gradle#L16 to say `implementation project(':testProject')` and run this test `"testProjectDependent should be successfully executed"` for gradle 4.3. This works.

In my earlier statement I was actually modifying the wrong file, my mistake. When I change it to `api` here I am getting a general gradle error about the config `> Could not find method api() for arguments ...` . But the `implementation` at least works. What do you see on your project?

**Comment by dmdashenkov** [comment]
In my case, I use the `compile` config for a module which contains both Java and Protobuf definitions. 
When changing to `implementation`, I get an error from `protoc` which says that an import (the file from the linked dependency) is not found.

Interestingly enough, using `implementation` for a project dependency (`implementation project(':proj')`) works just fine. However, when trying to use an external artifact (`implementation "my.package:artifact:version"`) the described issue happens. 

The visible difference when building my project in those two configurations is in the `build/extracted-include-protos` directory. When using `compile`, it contains all the used `.proto` files and when using `implementation` - only the standard Protobuf definitions (those under `com.google` package).

I'll proceed with my investigation and inform you if I find some more info.

**Comment by pusolito** [comment]
I am also having similar issues.  I created a [project](https://github.com/pusolito/proto-plugin-issue) to demonstrate this.  I am only able to use `compile` **not** `implementation`.  Also, changing the version of **Kotlin** also breaks `compile`.

**Comment by dmdashenkov** [comment]
@zpencer, I experience the same behavior as @jd3nn1s. Is there a chance that someone will take a look at this issue soon?

P.S. Sorry for making such a long pause in the conversation.

**Comment by zpencer** [comment]
@zhangkun83 perhaps you can take a look at exposing the new style dependency configuration.

**Comment by dmdashenkov** [comment]
Hi, guys. Are there any updates on this issue?

**Comment by jd3nn1s** [comment]
If someone can provide a little direction on how to implement this I am willing to take a look at doing it.

**Comment by dmdashenkov** [comment]
Seems like this is what is happening:
 - `GenerateProtoTask` knows nothing about configurations, it simply picks up whatever `ProtobufExtract` produces;
 - `ProtobufExtract` takes its orders from `ProtobufPlugin` directly; `ProtobufPlugin` specifies the configuration to the `ProtobufExtract` (as `input` files);
 - [here](https://github.com/google/protobuf-gradle-plugin/blob/74b3be399dd8ea7af76e9f9aed5dc452d62435d2/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L375) `ProtobufPlugin` defaults to the `compile` configuration if none is specified;
 - if we look closely, no configuration is ever specified to the `setupExtractIncludeProtosTask(..)` method except for the case with Android builds.

It is really up to you, but I'd expect the plugin to use `compileClasspath` configuration for this purpose. Or even better, the [`compileClasspath` property](https://docs.gradle.org/current/userguide/java_plugin.html#sec:source_set_properties) of the target `SourceSet`.

**Comment by dmdashenkov** [comment]
@jd3nn1s, please let me know if you have any questions on my comment.

**Comment by dmdashenkov** [comment]
@jd3nn1s, is there any progress? If you didn't have a chance to try yet, maybe I could give it a try sometime soon.

**Comment by voidzcy** [comment]
@dmdashenkov 
Does changing "compile" to "compileClasspath" work for you?

**Comment by dmdashenkov** [comment]
Sorry for a long silence. I do not seem to receive some notifications from open source repos.

@voidzcy, yes, this should work. Moreover, according to the build warnings in Gradle `6.0`,
```
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation or api configuration instead.
```
Tip: run a build with ` --warning-mode all` to see this.

You are right, `compileClasspath` should cover both `implementation` and `api` (as well as the deprecated `compile`).

**Comment by voidzcy** [comment]
I recently found this issue is actually related to #363.

I am able to reproduce what @dmdashenkov says exactly:
> In my case, I use the `compile` config for a module which contains both Java and Protobuf definitions.
When changing to `implementation`, I get an error from protoc which says that an import (the file from the linked dependency) is not found.

**Comment by dmdashenkov** [comment]
@voidzcy, sorry for the lack of this information. I failed to mention this. I guess I was distracted by the fact that `java-library` actually applies `java` as well. But yes, we do use `java-library` in projects where this can be reproduced.

**Comment by dmdashenkov** [comment]
I've migrated to `0.8.11` and now the issue seems to be gone. Thank you.
