### ISSUE TITLE
different buildtype different output location

### ISSUE THREAD

**Issue by sunquan1985** [google/protobuf-gradle-plugin#243]
when i assembleDebug in android studio
the output protobuf file generated in src/main/java
while i assembleRelease
the output protobuf file generated in src/main/java/release/javanano
how they can be the same? thanks.

my config is:
`protobuf {

    //https://github.com/google/protobuf-gradle-plugin
    protoc {
        artifact = 'com.google.protobuf:protoc:3.1.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove javanano
            }
            task.builtins {
                javanano {}
                // Add cpp output without any option.
                // DO NOT omit the braces if you want this builtin to be added.
                //                cpp {}
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/src/main/java"
 }`

**Comment by zhangkun83** [comment]
`src/main/java/release/javanano` is the expected location.
Have you tried a clean build?

**Comment by zhangkun83** [comment]
Because of your `generatedFilesBaseDir` setting, the protobuf generated files will all be under `src/main/java`. And because it's not under `build`, a "clean" build may not work properly.

Can you delete all generated files manually and try building again?

**Comment by sunquan1985** [comment]
@zhangkun83 thank3，by remove generatedFilesBaseDir config it works
