### ISSUE TITLE
[Android] Program type already present: com.google.protobuf.ByteOutput

### ISSUE THREAD

**Issue by jmiecz** [google/protobuf-gradle-plugin#244]
Hello,

I am trying to setup an Android project to use the Protobuf Plugin but when I add the below lib, I get the below error. When I remove the dependency, it seems to compile. 
`compile 'com.google.protobuf:protobuf-lite:3.0.0'`

```
Program type already present: com.google.protobuf.ByteOutput
Message{kind=ERROR, text=Program type already present: com.google.protobuf.ByteOutput, sources=[Unknown source file], tool name=Optional.of(D8)}
```

**Comment by ejona86** [comment]
You probably have full protobuf (`com.google.protobuf:protobuf`) as a transitive dependency. You can only have one as a dependency. Use `gradle dependencies` to investigate where it is coming from. For reduced output, you can specify a particular configuration, e.g. `gradle dependencies --configuration=releaseCompileClasspath`.

**Comment by ronnie173** [comment]
Did this ever get resolved? I am having the same issue

**Comment by zpencer** [comment]
This is likely an issue with your build configuration rather than this plugin. Have you tried running the above `gradle dependencies` command to see whether full protobuf got pulled into your build?

**Comment by dimitrileite** [comment]
In my case it was caused by this conflict between:
+--- com.google.protobuf:protobuf-lite:3.0.1@jar
and
+--- io.grpc:grpc-protobuf-lite:1.12.0@jar
and now? What`s next?

**Comment by ejona86** [comment]
@dimitrileite, I don't think that is a conflict. grpc-protobuf-lite depends on protobuf-lite, so that is quite normal. com.google.protobuf:protobuf is likely somewhere in the dependency tree.

**Comment by junkomatic** [comment]
I encountered this issue using com.google.firebase:firebase-firestore database dependency which uses com.google.protobuf:protobuf-lite, with also using com.google.Capillary library which uses com.google.protobuf:protobuf-java.  When I try to run on device I get "Error: Program type already present: com.google.protobuf.Any" (or other such class type). I cant figure out how to get them to run together without breaking the functionality of the com.google.Capillary library.

**Comment by ejona86** [comment]
You cannot mix com.google.protobuf:protobuf-java and com.google.protobuf:protobuf-lite. It looks like capillary needs to be fixed. We'll continue that conversation at google/capillary#11.

**Comment by ejona86** [comment]
This is not an issue with the plugin, as is evidenced by those multiple users that have reported the issue and fixed it. If you see this, look for accidentally mixing protobuf-java and protobuf-lite as I mention in my first reply.
