### ISSUE TITLE
Release a build compatible with Android Studio 3.2.0-beta1

### ISSUE THREAD

**Issue by bubenheimer** [google/protobuf-gradle-plugin#245]
It appears that 0.8.5 is incompatible with Android Studio 3.2.0-beta1, but the current 0.8.6 SNAPSHOT build is compatible. Can someone please cut a release?

https://issuetracker.google.com/issues/110564407

**Comment by davidburstromspotify** [comment]
Is the current snapshot also compatible with 3.1.x?

**Comment by zhangkun83** [comment]
0.8.6 has been released.
