### ISSUE TITLE
Plugins utilizing protoc insertion points

### ISSUE THREAD

**Issue by isupeene** [google/protobuf-gradle-plugin#249]
I'm using the javalite protoc plugin to generate proto code for my Android app, and I want to extend the code with my custom protoc plugin using insertion points.

There appear to be two problems with this.
1. The different protoc plugins output to different directories, so when my custom protoc plugin is run, it complains that the file it's trying to insert code into doesn't exist.
2. There doesn't appear to be a way to ensure that the base code is generated before my custom insertion code, since both protoc plugins are run as part of the same gradle task.

Is there any guidance on how to use this gradle plugin for this use case?

**Comment by isupeene** [comment]
Update on this after discussing with zhangkun offline and trying it out for myself:

1. The output directory can be changed with something like this:
```
  generateProtoTasks {
    all().each { task ->
      task.plugins {
        myplugin {
          outputSubDir = 'javalite'
        }
      }
    }
  }
```
2. The second point I raised actually isn't the issue, since I discovered that to work properly, both plugins (generation and insertion) actually do need to be invoked with the same protoc call.  However, the output directory for the insertion plugin needs to be specified _after_ the output directory for the generation plugin.  The specification order implemented by the gradle plugin appears to be alphabetical, since I finally made it work by renaming my insertion plugin to start with 'z' instead of 'a'.

So the only remaining thing I believe should be done to support this use case is to make the output dir specification order based on the order the plugins are listed in the gradle file, if that's possible.

**Comment by zhangkun83** [comment]
`task.plugins` (`GenerateProtoTask#plugins`) is a `NamedDomainObjectContainer` which, according to its [documentation](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectContainer.html), sorts its elements by name.

A possible solution is to implement our own `NamedDomainObjectContainer`, and create `GenerateProtoTask#plugins` through `project.container(PluginOptions, containerFactory)`.

**Comment by zhangkun83** [comment]
I just had a talk with @ejona86 and @xfxyjwf (Protobuf TL). Their answer is that insertion point is never a public feature, has caused problems and is disabled internally. Protobuf team is talking about removing it. They highly recommend stop using this feature. If you do have to use it, renaming your insertion plugin to start with 'z' doesn't sound a horrible idea.
