### ISSUE TITLE
protobuf with multiple imports

### ISSUE THREAD

**Issue by skinkie** [google/protobuf-gradle-plugin#254]
I have encountered the follow issue. For readability of a very large grpc project I have split the message into several files with one include. My layout looks like:
projectname.proto
chapter1.proto
chapter2.proto

I have noticed that while the code generation for c++ is fine, the generation with android/kotlin is problematic. First I thought that the issue was that because of the ``**/*.proto`` selection any file was individually generated. While I couldn't figure out how to disable this include to only include ``'**/projectname.proto'`` I renamed all chapters to chapterN.import.

This again resulted in the same compilation errors showing classes started with numbers, and errors such as expected ')'  <identifier> expected illegal start of type.

When I merge the entire project into one single file "book.proto" and remove all other files, the errors seem to disappear.  But the project then still doesn't compile, the errors then become cannot find symbol class. I consider the first part of this issue a bug, and the second part request for help.

**Comment by zhangkun83** [comment]
@skinkie has my reply on https://github.com/grpc/grpc-java/issues/4690 answered your question?

**Comment by skinkie** [comment]
@zhangkun83 I still have to figure out how to do it. But  grpc/grpc-java#4690 contained a bug that is certainly not solved by documentation alone.

**Comment by ejona86** [comment]
I'm pretty certain this fixed, although I can't easily track down when. I believe this is fixed because the recent (fixed) regression #622 sounds just like this.
