### ISSUE TITLE
Option to prevent generateProto from "linking" with existing tasks

### ISSUE THREAD

**Issue by cretz** [google/protobuf-gradle-plugin#256]
Right now, `generateProto` is set as a dependency of other common tasks (e.g. `compileKotlin`). I believe this is what issue #211 was referring to before it was closed. It is a very common use case to only run this manually and not during other tasks (whether or not it is up to date).

I have not yet found a way to only make this run manually (i.e. stop setting it as `dependsOn` other tasks), but in the meantime for anyone else needing this, here is a snippet that will just disable the task if there are any other non-protobuf tasks that have been loaded:

```groovy
gradle.taskGraph.whenReady { graph ->
    // Just disable the proto task if there are any non-proto tasks
    def hasNonProto = graph.allTasks.any { !it.class.name.contains('protobuf') }
    if (hasNonProto) generateProto.enabled = false
}
```

So if you run `generateProto` it remains enabled because other tasks are not present, but if you run something like `test` it won't run.

**Comment by cretz** [comment]
For some use cases, people want to generate the proto code manually and then maybe commit it. They may want to tweak it from there, run it through another tool, etc. For my use case, the tooling/plugin setup for generating the protobuf code is complex enough that I am committing my generated code instead of re-generating every compile.

Either way, it seems reasonable to allow people to use these tasks without requiring that they infect their existing task dependencies with it. While defaults are sensible, it is normal for people to be able to rearrange the dependencies of their tasks in Gradle and if someone wants to, say, run generateProto in some other way and not during compilation, they should be able to.

**Comment by zhangkun83** [comment]
> For some use cases, people want to generate the proto code manually and then maybe commit it. 

This is not a usual use case. For someone that does it, they does it only occasionally IIUC. Then your snippet seems to be a reasonable workaround.

> They may want to tweak it from there, run it through another tool, etc.

This might justify for some change if it is part of the normal build process to run the generated files through some post-processor before they are compiled by javac. Is it your case or do you know any tool that does that?

**Comment by cretz** [comment]
> This is not a usual use case

While not the norm, committing generated code is not completely abnormal.

> Then your snippet seems to be a reasonable workaround.

It's not, I just have to use it because of the stage that dependencies are added. I can't remove them from `dependsOn` or anything at any stage I can find. I would welcome a more reasonable approach than looking for a string in a package name and disabling the task.

>  Is it your case or do you know any tool that does that?

Even though there are plenty of post processing tools, I'm not sure enumerating them is worth it here. In general, wrt build tooling, flexibility to override defaults has value. But just close the issue if this plugin will always attach itself to compilation without the ability to change it.

**Comment by zhangkun83** [comment]
> While not the norm, committing generated code is not completely abnormal.

Agreed. gRPC does that too. What we did is just put the whole protobuf stuff in a big if-block and control it with a property. When we want to use the committed generated code, we don't apply the protobuf plugin at all:
https://github.com/grpc/grpc-java/blob/v1.14.0/build.gradle#L119

> Even though there are plenty of post processing tools, I'm not sure enumerating them is worth it here. In general, wrt build tooling, flexibility to override defaults has value. But just close the issue if this plugin will always attach itself to compilation without the ability to change it.

I agree with your statement in general. That goal may be easier to achieve in build systems like bazel which require you to specify every step by yourself. As with Gradle, language plugins, including the Android plugin, usually create tasks implicitly and wire them up for you. We don't want users to tackle with the dependencies among those implicit tasks, because 1) they are implementation details and subject to change, and 2) it may not be trivial.

That said, if you have a concrete use case that's not satisfied, we can talk about making ad-hoc changes to support it.

**Comment by cretz** [comment]
> As with Gradle, language plugins, including the Android plugin, usually create tasks implicitly and wire them up for you. We don't want users to tackle with the dependencies among those implicit tasks

Right, I agree. Just asking for an option that I can set to never call [this method](https://github.com/google/protobuf-gradle-plugin/blob/42d741c1f32cd2551329f2f39ba374d59338267e/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L420) or at least make it a noop. But if I'm the only one asking, I can understand why y'all won't do it.

**Comment by cretz** [comment]
For anyone else using this hack to only generate protos manually, I instead changed my code to:

```groovy
    gradle.taskGraph.whenReady { graph ->
        generateProto.enabled = graph.allTasks.last().class.name.contains('protobuf')
    }
```

Still a complete hack to check package names of tasks, but sadly it's considered by others as a reasonable workaround.

**Comment by tozsvath** [comment]
I think cretz usecase's is valid. I have a similar issue. We would use protobuf in a chain of tasks. It would be the following: resolve dependencies, get the tdl files are coming from jars - get the protofiles from jar - generateProto  Our proto files generated after protobuf and I can't hook before this event. @zhangkun83  is there any other workaround except using basel?

**Comment by zhangkun83** [comment]
@tozsvath sorry I don't understand your chain of tasks. At which step are your proto files generated?
