### ISSUE TITLE
Plugin should find dependencies on `compileClasspath` instead of `compile` configuration.

### ISSUE THREAD

**Issue by dmvk** [google/protobuf-gradle-plugin#258]
Hello,

in multiproject build we depend on proto files from other project. As we are not using deprecated `compile` configuration, we also need to add dependency to `protobuf` configuration.

Can plugin depend on `compileClasspath` by default in order to support `api` and `implementation` configurations?

Thanks,
David

**Comment by zhangkun83** [comment]
Not sure what you mean by "depending on `compileClasspath` by default". We will add support to `api` and `implementation` as discussed in #242.

**Comment by voidzcy** [comment]
Please try out 0.8.11 release, we did some work regarding this issue. Please let us know if there is anything else related to this issue.
