### ISSUE TITLE
importing artifacts containing protos without code

### ISSUE THREAD

**Issue by ankitpatel29** [google/protobuf-gradle-plugin#259]
Does the plugin support importing other artifacts which only consists of proto files and adding it to the dependency of the current protos. I read the documentation it has an example which is like protobuf files("lib/proto.jar"), this assumes that the jar is available in the lib folder of my project. What if I do not want to manually add this jar there but instead use gradle to pull this proto containing jar as an artifact. Is there a way to feed that to the plugin and use it in compilation. Maybe I am missing something. Please advice.

**Comment by ejona86** [comment]
It uses the normal gradle syntax. Let's say you want proto-google-common-protos from Maven Central, then use `protobuf 'com.google.api.grpc:proto-google-common-protos:1.0.0'`

**Comment by ankitpatel29** [comment]
Thanks for replying. Sweet, I think that is exactly what I was looking for. Let me give this a try, I will respond back shortly.

**Comment by ankitpatel29** [comment]
Confirmed. This works as I expected. Thanks a lot.
