### ISSUE TITLE
Duplicate Entry Errors with Android and MultiDex

### ISSUE THREAD

**Issue by donnfelker** [google/protobuf-gradle-plugin#26]
I'm following the Android example project here: https://github.com/google/protobuf-gradle-plugin/tree/master/testProjectAndroid  

My project uses multidex and when I integrate this into my project I start getting the following error: 

```
Error:Execution failed for task ':MyApp:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: io/grpc/protobuf/DeferredProtoInputStream.class
```

Normally this is fixed by applying an exclusion because you have a duplicate entry somewhere. I confirmed that I do not have a duplicate entry by inspecting the gradle dependency graph. The dependency related to protobuf is this one: 

```compile 'io.grpc:grpc-all:0.7.0'```

I made some changes to it, recompiled (rinse/wash/repeat) and eventually got to the point where I was having to exclude everything the dependency relies on: 

```
    compile('io.grpc:grpc-all:0.7.0') {
        exclude group: 'io.grpc', module: 'grpc-protobuf'
        exclude group: 'io.grpc', module: 'grpc-protobuf-nano'
        exclude group: 'io.grpc', module: 'grpc-stub'
    }
```

At this point the app breaks because I'm using the nano messages. 

I have not referenced anything proto related anywhere else in my project and this is the first time I've introduced it to my project. 

What do I need to do in order to get this working? What needs to change? Is there a bug with multidex?

**Comment by donnfelker** [comment]
To get this bug to show up, simply add the following line to the android config block in the testProjectAndroid

```
multiDexEnabled true
```

That will make the testProjectAndroid fail with the following error: 

```
Error:Execution failed for task ':testProjectAndroid:packageAllArmFreeappDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/squareup/okhttp/OkHttpTlsUpgrader$DummyAuthenticator.class
```

**Comment by zhangkun83** [comment]
This is interesting, but it doesn't look related to the protobuf plugin.
I tried to reproduce it with the way you provided, but it builds fine.
Can you try not loading the protobuf plugin and copy the generated files (under ``build/generated/source/proto/``) into your source directory temporarily just to see if you still have the problem?

**Comment by donnfelker** [comment]
@zhangkun83 Yeah taking generated proto files and putting them into the src/ directory and then commenting out all the plugin code in the build.gradle allowed a successful build. Thoughts?

**Comment by donnfelker** [comment]
@zhangkun83 I was mistaken. `Build Project (F9)` succeds. But if you attempt to run the Android build configuration I'm getting the following error: 

```
Error:Execution failed for task ':testProjectAndroid:packageAllArmFreeappDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/squareup/okhttp/OkHttpTlsUpgrader$DummyAuthenticator.class
```

**Comment by donnfelker** [comment]
FYI, following the changes made in this commit: https://github.com/google/protobuf-gradle-plugin/commit/47d1430e9980ff3591cf7230f6c124a12e4f491b I was able to resolve the issues. Not sure exactly what the root cause was (I'd love to know) but I just wanted to let you know that this fixed the issue.
