### ISSUE TITLE
Use on Alpine Linux

### ISSUE THREAD

**Issue by rangerscience** [google/protobuf-gradle-plugin#265]
Hia, trying to use this plugin. Code is being built via Jenkins in a docker image based off Alpine Linux, but is generated the following error:

```
> java.io.IOException: Cannot run program "/home/jenkins/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.0.0/201dfa4737accd4cf6fbed76a7467e321e47983c/protoc-3.0.0-linux-x86_64.exe": error=2, No such file or directory
```

Here's the modules `build.gradle`:
```
apply plugin: 'com.google.protobuf'

buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.6'
  }
}

dependencies {
  compile 'com.google.protobuf:protobuf-java:3.5.1'
}

javadoc {
  options.addStringOption 'Xdoclint:none', '-quiet'
}

protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.0.0'
  }
}
```

Note: Prior error was that `protoc` wasn't available (makes sense, it's not installed on the build image), which is when I added the `artifact` bit as per the docs on this repo.

Any ideas / solutions / links? Cheers!

**Comment by rangerscience** [comment]
Okay, handy.

The docs for this plugin state: `It assembles the Protobuf Compiler (protoc) command line`. This led us to believe that we didn't have to have protoc installed on the image; that the plugin would handle that. Is this not the case?

**Comment by domineerLong** [comment]
Are there any news or solutions to this issue? I am experiencing the exact same problem...

**Comment by adrianmkng** [comment]
Best solution I've found so far is to install glibc into your alpine image. Instructions on how to do this can be found here: https://github.com/sgerrand/alpine-pkg-glibc

I needed it for gRPC code generation as well.

**Comment by tmacam** [comment]
> Best solution I've found so far is to install glibc into your alpine image. Instructions on how to do this can be found here: https://github.com/sgerrand/alpine-pkg-glibc
> 
> I needed it for gRPC code generation as well.

Just faced this problem and now (2022-Aug) there is a somewhat easier solution: installing `gcompat` package. From  https://wiki.alpinelinux.org/wiki/Running_glibc_programs

> gcompat is the go-to compatibility layer for Alpine users.
> 
> ```
> apk add gcompat
> ```
> 
> After that you run your binaries as normal.

**Comment by ejona86** [comment]
I didn't realize this was still open. Yeah `gcompat` is the way to go here. For some usages you could use the [Alpine protoc package](https://pkgs.alpinelinux.org/package/edge/main/x86/protoc) but gcompat works with grpc as well and allows you to choose the protoc version.

**Comment by xyziven** [comment]
after install gcompat in alpine linux on arm64.  Got error “Protoc error exit code: 134”:

`2024-12-10 17:43:57,072 ERROR v.z.b.c.p.ProtocInvoker: [Protoc error log] terminate called after throwing an instance of 'std::system_error'
2024-12-10 17:43:57,072 ERROR v.z.b.c.p.ProtocInvoker: [Protoc error log]   what():  No error information
2024-12-10 17:43:57,073 ERROR v.z.b.GRPCSampler: java.lang.RuntimeException: Unable to resolve service by invoking protoc:

Protoc error exit code: 134

Protoc execute command:
        protoc-jar: protoc version: 3.21.4, detected platform: linux-aarch_64 (linux/aarch64)
        protoc-jar: using default maven settings, didn't find user settings.xml
        protoc-jar: cached: /tmp/protocjar.webcache/com/google/protobuf/protoc/maven-metadata.xml
        protoc-jar: cached: /tmp/protocjar.webcache/com/google/protobuf/protoc/3.21.4/protoc-3.21.4-linux-aarch_64.exe
        protoc-jar: executing: [/tmp/protocjar13854389467975432323/bin/protoc.exe, /test/hello_account.proto, -I/test, -I/tmp/polyglot-well-known-types13045650643440698478, -I/test/hello_account.proto, --descriptor_set_out=/tmp/descr

Protoc execute error: 
   terminate called after throwing an instance of 'std::system_error'`
