### ISSUE TITLE
generated files are always named Protos.java

### ISSUE THREAD

**Issue by anshulverma** [google/protobuf-gradle-plugin#27]
Am I missing something or does the `generateProtos` task always generated a file named `Protos.java`?
Ideally, I would like it to generate multiple files (one per message). I see there is a way to specify `option 'multiple_files=true'` for `javanano`. I was hoping to have something similar.

**Comment by ejona86** [comment]
It is most likely named "Protos.java" because your file name is "protos.proto" (and this name can be overridden with java_outer_classname). The plugin itself does not choose the file names, those are chosen by protoc itself.

Try setting "option java_multiple_files = true;" in the .proto.

**Comment by anshulverma** [comment]
Thanks, setting `option java_multiple_files = true;` worked.

By the way, the file was not named `protos.proto`. I understand why that could cause the same issue. I in fact had `option java_outer_classname = "Protos";`.
