### ISSUE TITLE
Unable to find JsonFormat class in Android

### ISSUE THREAD

**Issue by sourcesoftankit** [google/protobuf-gradle-plugin#276]
I am using "Protobuf" library in android, and My business logic required to convert Proto format to Json so i need JsonFormat class for that but i am not able to find the "com.google.protobuf.util.JsonFormat" class and even com.google.protobuf.util package also.

I am using lite version of Protobuf and My gradle entry for protobuf is 

     apply plugin: 'com.google.protobuf'

     protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.plugins {
                 javalite { }
               }
           }
       }
    }

      dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation 'com.android.support:appcompat-v7:26.1.0'
        implementation 'com.google.protobuf:protobuf-lite:3.0.0'

    }

And in my project level gradle:

       dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.3'
      }

**Comment by ejona86** [comment]
This has nothing to do with this plugin, since `com.google.protobuf.util` isn't generated code.

But in short, `com.google.protobuf.util` is in a different artifact, `protobuf-java-util`. And it doesn't work with `protobuf-lite`. Using the JSON conversion is unsupported on Android, as Lite does not include the necessary descriptors (as they would increase the apk size too much).

**Comment by ejona86** [comment]
I'm not aware of any, but I'm not in-the-know enough to say if someone else has made something. We tend to think that conversions like that shouldn't be happening in an Android app (due to app size), so we design the system differently.

**Comment by cepages** [comment]
If it helps to anyone. I've described the problem and the solution in a thread in google forums.

Solution, using `protobuf-java` instead of javalite

https://groups.google.com/forum/#!topic/protobuf/EC2TtPixCFY

**Comment by rakshitsoni02** [comment]
is there any good solution except  using protobuf-java instead of javalite?
