### ISSUE TITLE
/imestamp.proto: File not found.

### ISSUE THREAD

**Issue by rogerlzp** [google/protobuf-gradle-plugin#277]
Android studio: 3.2.1
gradle: 4.6
Using  classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.6' /
Two packages in src/main/proto:  commuter/authorization_token.proto, google/protobuf/timestamp.proto, google/type/*.proto

snippet of  commuter/authorization_token.proto:
```
syntax = "proto3";
package commuter.protobuf;
import "main/proto/google/protobuf/timestamp.proto";
option java_multiple_files = true;
option java_outer_classname = "AuthorizationTokenProto";
option java_package = "com.commuter.protobuf";
message AuthorizationToken {...}
```
snippet of google/protobuf/timestamp.proto:
```
syntax = "proto3";
package main.proto.google.protobuf;
option java_multiple_files = true;
option java_outer_classname = "TimestampProto";
option java_package = "com.google.protobuf";
```
Tried to set sourceSet in app/build.gradle:
```
android {
  sourceSets {
        main {
    proto {
                srcDir 'src/main/proto/google/protobuf'
            }
      }
```
However, always failed with error: /StudioProjects/commuter/app/src/debug/proto: warning: directory does not exist.
main/proto/google/protobuf/timestamp.proto: File not found.
commuter/authorization_token.proto: Import "main/proto/google/protobuf/timestamp.proto" was not found or had errors.

It seems srcDir doesn't work.
Anyone who can help a hand?

**Comment by zhangkun83** [comment]
Import path should be relative to the root of the source directly. Try changing
```
import "main/proto/google/protobuf/timestamp.proto";
```
to
```
import "google/protobuf/timestamp.proto";
```
and deleting the snippets in `sourceSets`.

**Comment by rogerlzp** [comment]
thanks very much for this.
I will change it accordingly.
