### ISSUE TITLE
Try to generateProto failed，could you give me some advise？

### ISSUE THREAD

**Issue by shuai102102** [google/protobuf-gradle-plugin#278]
![dto dc1 giyzynb6 v _8](https://user-images.githubusercontent.com/40763268/49280909-3e41c600-f4c6-11e8-8531-b3e82e3d5435.png)

**Comment by shuai102102** [comment]
```
sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
    }

    test{
        java{
            srcDir 'src/test/java'
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protocVersion}"
    }

    generatedFilesBaseDir = "src"

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }

    generateProtoTasks {
        ofSourceSet('main').each { task ->
            task.builtins {
                java{
                    outputSubDir = 'java'
                }
            }
            task.plugins {
                grpc {
                    outputSubDir = 'java'
                }
            }
        }
    }
}
```
This is my build.gradle.

![1543570863 1](https://user-images.githubusercontent.com/40763268/49281277-2159c280-f4c7-11e8-90db-7ac56c704f3a.jpg)
This is my project architecture.

**Comment by zhangkun83** [comment]
What's the error message?

**Comment by shuai102102** [comment]
I try to generate grpc.java files through protocbuf plugins. This action throws errors above.

**Comment by zhangkun83** [comment]
Those are not error messages. Your IDE should have a output window that displays errors in text.

**Comment by shuai102102** [comment]
This problem have resolved，the reason is that repository of gradle can not be reached.Thank you.
