### ISSUE TITLE
Skip plugin for specific files

### ISSUE THREAD

**Issue by miroslavvojtus** [google/protobuf-gradle-plugin#279]
I am working on a project which has on one side grpc+protobuf (end-device to edge-device) and mqtt+protobuf (edge-device to cloud) on the other.

Is there any simple way how to declare in gradle build script to use grpc plugin only for subset of proto files?

**Comment by zhangkun83** [comment]
You can exclude unwanted files in the `sourceSet` block, e.g.,
```gradle
sourceSets {
  main {
    proto {
      exclude 'some/unwanted/package/**'
    }
  }
}
```
