### ISSUE TITLE
Extracted protos are passed as input protos

### ISSUE THREAD

**Issue by stephenh** [google/protobuf-gradle-plugin#281]
We're using the google `Timestamp` type in our proto files, and so need the extracted protos to be available on the import path.

However, it seems like protoc is being invoked with the extract protos as both import paths (-I) as well as regular import files:

```
14:31:27.093 [INFO] [org.gradle.api.Task] [/home/stephen/.gradle/caches/.../protoc-3.5.1-linux-x86_64.exe, -I.../src/main/proto, -I.../build/extracted-protos/main, -I.../build/extracted-include-protos/main, --twirp_typescript_out=.../build/generated/source/proto/main/twirp_typescript, --plugin=protoc-gen-twirp_typescript=./bin/protoc-gen-twirp_typescript, .../build/extracted-protos/main/google/protobuf/any.proto, .../build/extracted-protos/main/google/protobuf/api.proto, .../build/extracted-protos/main/google/protobuf/compiler/plugin.proto, .../build/extracted-protos/main/google/protobuf/descriptor.proto, .../build/extracted-protos/main/google/protobuf/duration.proto, .../build/extracted-protos/main/google/protobuf/empty.proto, .../build/extracted-protos/main/google/protobuf/field_mask.proto, .../build/extracted-protos/main/google/protobuf/source_context.proto, .../build/extracted-protos/main/google/protobuf/struct.proto, .../build/extracted-protos/main/google/protobuf/timestamp.proto, .../build/extracted-protos/main/google/protobuf/type.proto, .../build/extracted-protos/main/google/protobuf/wrappers.proto, .../src/main/proto/service.proto]
```

So it's passing extracted protos both as `-I` arguments (correct) _as well as_ primary input protos (incorrect AFAIU).

E.g. ".../src/main/proto/service.proto" is the only proto that should be passed after the `--plugin` arguments because it's the only non-extracted proto in my project.

Note that this normally doesn't seem to break things, for the regular java/etc. output; except if I turn on the ruby output, then the ruby backend blows up b/c the `google/protobuf/compiler/plugin.proto` is using proto2 syntax (even in the proto3 releases/branch), and the ruby backend explicitly does not support this yet.

https://github.com/protocolbuffers/protobuf/blob/3.6.x/src/google/protobuf/compiler/plugin.proto#L47

If I call `protoc` manually with the extracted paths only as `-I`s then everything works great.

It seems like this is a bug? The extracted protos shouldn't be considered as input for real code generation (and they seem to generally be actively ignored by everything except the ruby backend), and AFAIU should only be for `-I` import paths.

Can you clarify if the current behavior is expected/necessary?

E.g. I think this line:

https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L314

Should somehow pass the extracted protos as something different than `include`, so that they can be differentiated for the command line output.

**Comment by zhangkun83** [comment]
There are [two types of dependencies](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies) with which you can use external protos. `protobuf/testProtobuf` compile the protos, and `compile/testCompile` don't.

"extracted-protos" from your output indicates you are using the `protobuf` dependency, which does compile the protos. You should instead use the `compile` dependency.

**Comment by stephenh** [comment]
...actually I think I can fix this by putting `protobuf-java` into the `compile` scope instead of `protobuf`. Going to assume that works and close. Apologies for the noise!

**Comment by TimelyToga** [comment]
Just to re-state what @stephenh posted, you need to have `com.google.protobuf:protobuf-java:<some_version>` in your dependencies instead of `com.google.protobuf:protobuf:<some_version>`. 😄 

Complete Kotlin DSL example: 
```
dependencies {
    implementation("com.google.protobuf:protobuf-gradle-plugin:$protoGradleVersion")
    implementation("com.google.protobuf:protobuf-java:$protocVersion")
}
```
