### ISSUE TITLE
A way to specify --descriptor_set_out on protoc command

### ISSUE THREAD

**Issue by lomdalf** [google/protobuf-gradle-plugin#29]
Hi,

Our use case requires us to generate a descriptor file. Is there a way to specify --descriptor_set_out flag on protoc command via the plugin?

We've tried:
```groovy
protobuf {
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                descriptor_set {}
            }
        }
    }
}
```

But, it looks like this generates
protoc --descriptor_set_out=src/main/descriptor_set
where src/main/descriptor_set is a directory.

This doesn't work because protoc requires that --descriptor_set_out should point to a file instead of a directory.

Your help in this matter would be greatly appreciated.

**Comment by zhangkun83** [comment]
FYI 0.6.1 includes this feature and has been released.

**Comment by lomdalf** [comment]
Thank you so much!
