### ISSUE TITLE
TODO(zhangkun83): Include source proto files in the compiled archive,

### ISSUE THREAD

**Issue by Sanjay-F** [google/protobuf-gradle-plugin#299]
![image](https://user-images.githubusercontent.com/8078089/52925367-0a12ce80-336c-11e9-87cc-c653cd767af4.png)
@zhangkun83 this todo need you . it has been 4 year .lol
 now it's time to finish it.
i need this feature , thanks

**Comment by ejona86** [comment]
Fixed by #601
