### ISSUE TITLE
Generating only first proto file

### ISSUE THREAD

**Issue by JonasVautherin** [google/protobuf-gradle-plugin#301]
I am using a custom protoc plugin (python module), together with `javalite` and `grpc`. Both `javalite` and `grpc` work well, but my plugin, when run, only generates the first found proto file. Also, it is not generating the file in the right place.

A quick look at the output of `tree` makes it quite clear:

```
% tree
.
├── dcsdk
│   └── Action.java
├── grpc
│   └── io
│       └── dronecode_sdk
│           ├── action
│           │   └── ActionServiceGrpc.java
│           ├── calibration
│           │   └── CalibrationServiceGrpc.java
 ...         ...
│           └── telemetry
│               └── TelemetryServiceGrpc.java
└── javalite
    └── io
        └── dronecode_sdk
            ├── action
            │   └── ActionProto.java
            ├── calibration
            │   └── CalibrationProto.java
            ...
            └── telemetry
                └── TelemetryProto.java
```

I would expect more outputs than `Action.java`, and I would expect `Action.java` in `io.dronecode_sdk.action`, following the pattern of the other two plugins.

Here is how I setup protobuf in `build.gradle`:

```groovy
...

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.6.1'
    }

    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }

        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.18.0"
        }

        dcsdk {
            path = "/path/to/dcsdkgen"
        }
    }

    generateProtoTasks {
        all()*.each { task ->
            task.builtins {
                remove java
            }

            task.plugins {
                javalite {}

                grpc {
                    option 'lite'
                }

                dcsdk {
                    option 'file_ext=java'
                }
            }
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir '../proto/protos/'
        }

        ...
    }
}

...
```

My protoc plugin is working well with Python and Swift already, and the `Action.java` file generated here is fine as well. So I am wondering what I am missing for Java. It doesn't give me any compilation error, so I don't know where to look.

What could I be doing wrong there? Is there a way to get more output to understand what's happening?

**Comment by marcoferrer** [comment]
You will want to set your outputSubDir in the dcsdk block to java.

**Comment by JonasVautherin** [comment]
But that will just output `java/Action.java` instead of my current `dcsdk/Action.java`, and the problems remain the same, right? Or did I misunderstand what you mean? Your referring to [this](https://github.com/google/protobuf-gradle-plugin#change-where-files-are-generated), right?

**Comment by marcoferrer** [comment]
I think I might have misunderstood your issue. If you were expecting an output similar to the other plugins then the plugin needs to set the file name to the path where you want it outputted.

**Comment by JonasVautherin** [comment]
Right. I thought it would be managed by protoc, but now that I think about it, it makes sense because Java is special in that case.

But my real problem is really that I have 10 proto files, and only 1 gets generated without an error. In the example above, `action.proto` becomes `Action.java`, and `calibration.proto` and `telemetry.proto` are simply ignored. Without an error coming from my plugin...

**Comment by zhangkun83** [comment]
Looking at the grpc plugin source code, the location of the generated files are from the protobuf API (see the `context` on [this line](https://github.com/grpc/grpc-java/blob/v1.18.0/compiler/src/java_plugin/cpp/java_plugin.cpp#L59)). Python may have the same API. I am closing this issue as this is not an issue in the Gradle plugin.
