### ISSUE TITLE
How can I change output directory?

### ISSUE THREAD

**Issue by konachan700** [google/protobuf-gradle-plugin#303]
How can I change output directory?

Now I set:
generatedFilesBaseDir = "$projectDir/src/main/java/generated"
outputSubDir = ''

I want:
$projectDir/src/main/java/generated/MyProto.java

I have: 
$projectDir/src/main/java/generated/**debug**/MyProto.java

How I can remove a "debug/release" directory from path?

**Comment by zhangkun83** [comment]
No, you can't. If you want to have the generated files in an arbitrary directory, you can leave `generatedFilesBaseDir` unchanged, and instead use the Gradle [Sync task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Sync.html) to copy the files to your desired directory.
