### ISSUE TITLE
Gradle 5.1 Task Avoidance API

### ISSUE THREAD

**Issue by imoverclocked** [google/protobuf-gradle-plugin#304]
This plugin eagerly creates these tasks everywhere it is applied:

  * extractIncludeProto
  * extractProto
  * extractTestProto
  * generateProto
  * generateTestProto

For large multi-project repositories, this can add up to a lot of extra tasks that are configured but never get executed.

Using the new gradle 5.1 API to avoid configuring tasks unless they are used may bring precious whole seconds back for projects that heavily use protobuf. These seconds are realized for every run of gradle that does not need to run *Proto tasks.

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by klesniewski** [comment]
Seems related to https://github.com/google/protobuf-gradle-plugin/issues/304

**Comment by mmorrisontx** [comment]
#246 is about tasks being executed unnecessarily while this is about tasks being configured unnecessarily.

**Comment by ejona86** [comment]
This was fixed in 0.9.0, by a large collection of PRs. I'll note that if you use the project from an IDE or with idea/eclipse plugins, we have to eagerly configure some tasks because of IDE limitations.

**Comment by imoverclocked** [comment]
Thanks to everyone who worked on this!
