### ISSUE TITLE
Build succeeds on version 0.8.7, fails on 0.8.8

### ISSUE THREAD

**Issue by rhuffman** [google/protobuf-gradle-plugin#307]
I have a project that fails when I update the protobuf plugin from 0.8.7 to 0.8.8. When I run ```./gradlew clean; /gradlew build``` it fails:

```
> Task :generateTestProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTestProto'.
  foo.proto: File not found.
  bar.proto: Import "foo.proto" was not found or had errors.
bar.proto:44:12: "foo.messages.MessageGroup" is not defined.
```

My project has multiple dependencies on protobuf files that are in zip files. The dependencies look something like this:

```gradle
dependencies {
  ...
  testProtobuf 'com.acme:foo:10.+'
  testProtobuf 'com.acme:bar:4.+'
}
```
Unfortunately, the 'foo' dependency includes a subdirectory in the archive, so it is unzipped in directory ```$buildDir/extracted-protos/idl```. Using 0.8.7 I handled that by adding the directory to sourceSets:

```gradle
sourceSets {
  test {
    proto {
      // One of the dependencies uses the subdirectory "idl" in the protobuf artifact, for some reason. So
      // we have to add that directory to the source set.
      srcDir "$buildDir/extracted-protos/test/idl"
    }
  }
}
```

However, with 0.8.8, on the first run of ```./gradlew build```, the file is no longer being found, so I get a failed import.

Oddly, if I run ```./gradlew build``` a second time (without a clean), then the build finishes correctly. Even stranger, ```./gradlew clean build``` (running both tasks in the same invocation of Gradle) also works.

I suspect I somehow need to be using 'include' instead of added it to the proto srcDir, but my trail-and-error has so far not led to any success.

**Comment by zhangkun83** [comment]
You shouldn't need to put `extracted-protos` in the `sourceSets`. To import protos under a subdirectory, simply put the path in your import statement, like:
```proto
import "idl/foo.proto";
```

The different result from different ways of invocation sounds like a problem with parallel build. Do you have parallel build turned on? If so, can you try with `--no-parallel` and see if it's still reproducible?

**Comment by rhuffman** [comment]
I could try that, but it will involve changing a lot of files that import 'foo'. Is there no way to indicate $builddir/extracted-protos/idl" should be searched for imports?

**Comment by rhuffman** [comment]
So this is my new workaround, which is pretty terrible. (Maybe there's something more succint?) I used to simply add "idl" to the source set and everything was fine.

```gradle
task copyProto(type: Copy) {
  from "$buildDir/extracted-protos/main/idl"
  include "*.proto"
  into "$buildDir/extracted-protos/main"
}

task deleteProtoSubdir(type: Delete) {
  delete "$buildDir/extracted-protos/main/idl"
}

task moveProto {
  dependsOn 'copyProto', 'deleteProtoSubdir'
}

task copyTestProto(type: Copy) {
  from "$buildDir/extracted-protos/test/idl"
  include "*.proto"
  into "$buildDir/extracted-protos/test"
}

task deleteTestProtoSubdir(type: Delete) {
  delete "$buildDir/extracted-protos/test/idl"
}

task moveTestProto {
  dependsOn 'copyTestProto', 'deleteTestProtoSubdir'
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:$protobufVersion"
  }
  generateProtoTasks {
    all().each { task ->
      switch (task.name) {
        case 'generateProto':
          task.dependsOn 'moveProto'
          break;
        case 'generateTestProto':
          task.dependsOn 'moveTestProto'
          break;
      }
    }
  }
}
```

**Comment by zhangkun83** [comment]
I am afraid changing your imports is the only proper fix.

**Comment by rhuffman** [comment]
I don't really understand why. It seems to me I should be able to point the generateProto task at any directory, not just extracted-protos. Especially since it worked until 0.8.8.

**Comment by zhangkun83** [comment]
Sorry, this is how the gradle plugin works as it is. The fact it works prior to 0.8.7 could be a coincidence, and that's not a supported behavior.

The actual issue is not about changing the directory for generated files, but rather (attempting) to include to-be-generated files in the `sourceSets`. `sourceSets` should only point to files that are existing **before** the build starts. Files that are generated **during** the build is not considered "source files" of the build.
