### ISSUE TITLE
Compiling protos using two different versions of protobuf (v2 and v3) within a java project

### ISSUE THREAD

**Issue by linusred** [google/protobuf-gradle-plugin#308]
Hey, having trouble finding any documentation on using two different versions of protoc to generate both proto2 and proto3 messages within the same project using the gradle plugin. The proto files themselves are entirely separate messages, so I don't need to compile one message to different versions, just two separate sets of protos to their respective versions.

I'd appreciate an example or documentation pointing to this usecase, if it's even possible through the gradle plugin . Thanks!

Or alternatives that might fulfill the use-case (For instance, would it be considered good practice to include a jar that's already had it's protos compiled with it's own version of the proto runtime jar shaded inside it, and would this plugin have any adverse side effects to that usecase)

**Comment by zhangkun83** [comment]
Unfortunately you can only specify one protoc to the protobuf gradle plugin. Why do you want to mix protobuf versions? If you add `syntax = "proto2";` to the proto2 proto files, they can be compiled by the proto3 protoc too.

**Comment by linusred** [comment]
We have a custom implementation of the proto generator and runtime with custom attributes and fields on protos that depends on a specific commit of proto2. But we're now using GRPC with proto3, but still need use that custom runtime/generator for older messages into the other system.

Either way, it does seem we can just wrap the other protos in a jar with a shaded proto runtime, and it seems to work fine. So, I'll close the issue.
