### ISSUE TITLE
WARNING: API 'variant.getJavaCompile()' is obsolete

### ISSUE THREAD

**Issue by CleverMod** [google/protobuf-gradle-plugin#312]
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

**Comment by zhangkun83** [comment]
This is a duplicate of #295
