### ISSUE TITLE
Cannot find build-time generated proto files

### ISSUE THREAD

**Issue by tozsvath** [google/protobuf-gradle-plugin#313]
I have an issue, and struggling with for a few days:
  protoc: stdout: . stderr C:\Users\myuser\myWorkspace\mainProject\mySubProject\build\out\path\to\proto\protofile.proto : File does not reside within any path specified using --proto_path (or -I).  You must specify...
I have checked the forumns but non of them helped.

I have used the gradle plugin in a java project, dependency verisons:

Classpath dependency:
"com.google.protobuf:protobuf-gradle-plugin:0.8.8"

Dependencies:
"com.google.protobuf:protoc:3.3.0"
"com.google.protobuf:protobuf-java:3.4.0"

Artifacts
"io.grpc:protoc-gen-grpc-java:1.17.1"
"com.google.protobuf:protoc:3.3.0"

apply plugin: 'com.google.protobuf'

I have used absolute path on proto{srcDir "${rootDir.getAbsolutePath()}/mySubProj/build/out"}

Our scenario would be the following
1, create proto with my tasks
2, From proto generate java classas - We have the issue here with protobuf

I have set the dependency of generation files to proto with the following code:

            if (task.name.equals("generateProto")) {
               //prepare files is for creating proto files
                prepareFiles.each {
                    task.dependsOn(it)
                }
            }

Also I have tried to separate protobuf to a submodule within the project and se tthe project dependencies, but I had the same error:

 protoc: stdout: . stderr C:\Users\myuser\myWorkspace\mainProject\mySubProject\build\out\path\to\proto\protofile.proto : File does not reside within any path specified using --proto_path (or -I). You must specify

There are a couple of interesting things about this error. 

0, I have checked the execution order of tasks, and proto files present when generateProto task starts. I was checked it numerous way and my tasks are getting executed before generateProto.
1, I have just given the path for ${rootDir.getAbsolutePath()}/mySubProj/build/out and the error message it exactly points to the existing file.
2, If i run the build/task one more time, it succeeds.
3, If I run the tasks manually, createProto then the generate proto it succeeds .

Any idea how can I resolve the issue? Our goal would be to during buildtime execute the following tasks 
1. create protofiles 
2. proto to java conversion(with protobuf)
 
It would happen during the build time.

**Comment by zhangkun83** [comment]
Did you put `proto{srcDir "${rootDir.getAbsolutePath()}/mySubProj/build/out"}` in the `sourceSets`? That doesn't sound right. My understanding is that `sourceSets` should be files that are present before build starts. Files created during the build or from the output of another (sub)project are not **source files** per se, and they should not go to `sourceSets`.

In order to compile proto files from a subproject, you would need to have a `protobuf` configuration in your dependencies that points to the subproject, something like:
```gradle
dependencies {
  protobuf project(':mySubProject')
}
```

The `protobuf` configuration allows you to import proto files for compilation from external artifacts, including other projects. It has been tested to work with a specific directory and archive files, although I have not tested it with `project()`.

**Comment by tozsvath** [comment]
The error message gone, but it still not resolved the issue. When I run first, it is getting finished without error, but no files generated. When I run second time, everything is getting generated, if i use protobuf from the same project.

What I have tried:
1, protobuf files("${rootDir.getAbsolutePath()}/mySubProj/build/out") -> it is the same issue what  I have just mentioned. I have tried it in thes ame project, and in subproject too.
2, protobuf project(':mySubProj')  Proto files are beeing generated during the subproject build, but protobuf finishes without finding anything.

If I place the files in a folder manually before starting the gradle build, and run the generateProto it is working fine.

Somehow it seems the protobuf files("${rootDir.getAbsolutePath()}/mySubProj/build/out") block  is being initialized before the files created despite it is in the same project or not.  In this way, it is not possible to pass any proto folder to proto plugin, which is being created during the build.

Any idea how to move on?

**Comment by zhangkun83** [comment]
`protobuf project(':mySubProj')` should be closer to the right answer. Please that one more time with `--info` on the Gradle commandline, and post the output under "Task :generateTestProto"? It should include a very long line that looks like:

[/usr/local/google/home/zhangkun/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.0.0/201dfa4737accd4cf6fbed76a7467e321e47983c/protoc-3.0.0-linux-x86_64.exe, -I/usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/src/test/proto, -I/usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/build/extracted-protos/test, -I/usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/build/extracted-include-protos/test, --java_out=/usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/build/generated/source/proto/test/java, /usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/build/extracted-protos/test/tmp/stuff.proto, /usr/local/google/home/zhangkun/github/protobuf-gradle-plugin-upstream/examples/exampleProject/src/test/proto/test.proto]

**Comment by wesleypeck** [comment]
I encounter this issue when upgrading from 0.8.7 to 0.8.8. When running the gradle tasks using `--info` I get the output shown below. The 0.8.8 version of this plugin is missing some of the include paths compared to the 0.8.7 version of the plugin.

0.8.7 (working with build time generated files):
protoc
    -I/Users/myuser/myproject/lib/src/main/proto
    -I/Users/myuser/myproject/lib/build/proto
    -I/Users/myuser/myproject/lib/build/extracted-protos/main
    -I/Users/myuser/myproject/lib/build/extracted-include-protos/main
    --java_out=/Users/myuser/myproject/lib/build/generated/source/proto/main/java
    /Users/myuser/myproject/lib/build/proto/example/pkg1/file1.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg1/file2.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg2/file3.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg3/file4.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg4/file5.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file6.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file7.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file8.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file9.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file10.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file11.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file12.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file13.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file14.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file15.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file16.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file17.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file18.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file19.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file20.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file21.proto

0.8.8 (not working with build time generated files)
protoc
    -I/Users/myuser/myproject/lib/build/extracted-protos/main
    -I/Users/myuser/myproject/lib/build/extracted-include-protos/main
    --java_out=/Users/myuser/myproject/lib/build/generated/source/proto/main/java
    /Users/myuser/myproject/lib/build/proto/example/pkg1/file1.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg1/file2.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg2/file3.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg3/file4.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg4/file5.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file6.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file7.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file8.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file9.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file10.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file11.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file12.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file13.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file14.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file15.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file16.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file17.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file18.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file19.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file20.proto
    /Users/myuser/myproject/lib/build/proto/example/pkg5/file21.proto

**Comment by zhangkun83** [comment]
@wesleypeck can you provide your link to your project for me to try out?

**Comment by wesleypeck** [comment]
@zhangkun83, here is a minimal example that fails with 0.8.8 but succeeds with 0.8.7:
```
plugins {
  id "com.google.protobuf" version "0.8.8"
  id "java"
}

repositories {
    jcenter()
}

sourceSets {
    main {
        proto {
            srcDir "${buildDir}/proto"
        }
    }
}

// An example task that "generates" protobuf files. A real project
// would fetch protobuf definitions from an HTTP site and/or have
// a code generator task that would generate protobufs.
task generateProtobuf() {
    def file = new File("${buildDir}/proto/example.proto")
    doLast {
        file.parentFile.mkdirs()
        file.text = '''
        syntax = "proto2";

        message TestMessage {
            optional int32 example = 1;
        }
        '''
    }
}

protobuf {
    generateProtoTasks {
        all().each { task -> task.dependsOn generateProtobuf }
    }
}

dependencies {
   compile "com.google.protobuf:protobuf-java:3.7.1"
}
```

While I'm not very familiar with this code base, I did do a little poking through the change set between 0.8.7 and 0.8.8 and this seemed like it could be related:
https://github.com/google/protobuf-gradle-plugin/compare/v0.8.7..v0.8.8#diff-24cbfae194dcd6012006c8784570736bL305

Particularly because these protobuf source directories don't exist in the project until after the generator task's execution phase.

**Comment by voidzcy** [comment]
I believe this issue is because `GenerateProtoTask`'s `includeDirs` and `sourceFiles` are not [lazily configured](https://docs.gradle.org/current/userguide/lazy_configuration.html), see https://github.com/google/protobuf-gradle-plugin/blob/d25369e20db8a3b3520c3835523641b5e1321ee1/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L347

So build-time generated proto files are not added into `GenerateProtoTask` even if with enforced task execution order. This should be fixed.

**Comment by zhangkun83** [comment]
I was under the impression that `sourceSets` should not include files generated during the build, but now I realized that's what gRPC is doing: https://github.com/grpc/grpc-java/blob/v1.21.0/build.gradle#L166, and a google search on "gradle sourceset for generated code" suggests this being an acceptable approach.  Lazy configuration sounds right to me.

**Comment by ejona86** [comment]
@zhangkun83, note that gRPC is _not_ including generated files. It is including _pre-generated_ files, for when the plugin is _not_ being used.

**Comment by voidzcy** [comment]
@zhangkun83 
I recently realized that including non-existing path in `sourceDirectorySet` isn't really a "correct" use case of Gradle, although many people are still trying to do that as you said when searching for "gradle sourceset for generated code". Gradle [`SourceDirectorySet` doc](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#srcDir-java.lang.Object-) says "Directories that do not exist are ignored", although it does say if "not exist" means directories not exist before the user run gradle build or before gradle execution phase. 

Though changes in #317 will not break other stuff of the plugin, I am not sure if we should merge this. By the way, I believe what gRPC is doing is the "correct" way of working around the issue of including build-time proto files. That is, the user should write logic in its own `build.gradle` for adding in build-time protos.

**Comment by zhangkun83** [comment]
gRPC doesn't generate proto files at build time, so it doesn't have the same issue. As you said, Gradle isn't clear about the time when talking about existence of source files. You could experiment with the java compilation and see if java compile tasks pick up source files that are not there at the beginning but generated during the build, and we just follow suit.

**Comment by voidzcy** [comment]
I experimented with the Java plugin. With the following dummy build:
```
apply plugin: 'java'

task myTask(type: DefaultTask) {
    doLast {
        def file = new File('generated/HelloWorld.java')
        file.parentFile.mkdirs()
        file.text = '''
        public class HelloWorld {
            public static void main(String[] args) {
                System.out.println("Hello, world");
            }
        }
        '''
        println 'We are done!'
    }
}

sourceSets {
    main {
        java {
            srcDirs 'generated'
        }
    }
}

compileJava.dependsOn myTask
```

It turns out the Java plugin does pick up source files that are generated by other tasks lazily. So shall I just merge the change? @zhangkun83

**Comment by zhangkun83** [comment]
@voidzcy please go ahead.

**Comment by zhangkun83** [comment]
v0.8.9 is released and includes this fix. We have some issue in releasing it on Gradle Plugins Portal. So this release is currently limited to Maven Central via the buildscript syntax.

**Comment by zhangkun83** [comment]
v0.8.9 is now also available through the Gradle `plugins {}` DSL.
