### ISSUE TITLE
Please update support for latest protobuf lite support

### ISSUE THREAD

**Issue by RaymondRexxar** [google/protobuf-gradle-plugin#315]
According to https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md and https://github.com/protocolbuffers/protobuf/issues/5961#issuecomment-490738070, the latest protobuf lite is already at rc. 

There are changes with GeneratedMessageLite.MethodToInvoke which causes failure on compiling. It would be great if this newly released 3.8.0-rc-1 can be supported, at least when it is out of rc state. Thank you!

**Comment by zhangkun83** [comment]
Changes in the generated code interfaces should be irreverent to the Gradle plugin.  Can you post your `build.gradle` and the build output?

**Comment by voidzcy** [comment]
Seems there does have some problem with latest `protobuf-javalite`. Following is the configuration I tested with

```
dependencies {
    compile 'com.google.protobuf:protobuf-javalite:3.8.0-rc-1'
    protobuf files("ext/")
    testCompile 'junit:junit:4.12'
}

protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.8.0-rc-1'
  }
  plugins {
    javalite {
      artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
    }
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        remove java
      }
      task.plugins {
        javalite { }
      }
    }
  }
}
```

and I got some compilation errors in generated classes such as 

```
error: cannot find symbol
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                                                                 ^
  symbol:   variable MergeFromVisitor
  location: class GeneratedMessageLite
```
or 
```
error: an enum switch case label must be the unqualified name of an enumeration constant
        case MERGE_FROM_STREAM: {
             ^
```
etc.

@ RaymondRexxar
Do you encounter the same issue?

**Comment by zhangkun83** [comment]
According to https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md, it appears the lite codegen is not a separate plugin any more, but instead an option to `java_out`. Have you tried:
```gradle
protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.8.0-rc-1'
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        java {
          option "lite"
        }
      }
    }
  }
}
```

**Comment by bubbleguuum** [comment]
I had this issue and above snippet fixed it (using com.google.protobuf:protoc:3.8.0).

**Comment by RaymondRexxar** [comment]
> Seems there does have some problem with latest `protobuf-javalite`. Following is the configuration I tested with
> 
> ```
> dependencies {
>     compile 'com.google.protobuf:protobuf-javalite:3.8.0-rc-1'
>     protobuf files("ext/")
>     testCompile 'junit:junit:4.12'
> }
> 
> protobuf {
>   protoc {
>     artifact = 'com.google.protobuf:protoc:3.8.0-rc-1'
>   }
>   plugins {
>     javalite {
>       artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
>     }
>   }
>   generateProtoTasks {
>     all().each { task ->
>       task.builtins {
>         remove java
>       }
>       task.plugins {
>         javalite { }
>       }
>     }
>   }
> }
> ```
> 
> and I got some compilation errors in generated classes such as
> 
> ```
> error: cannot find symbol
>           if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
>                                                                  ^
>   symbol:   variable MergeFromVisitor
>   location: class GeneratedMessageLite
> ```
> 
> or
> 
> ```
> error: an enum switch case label must be the unqualified name of an enumeration constant
>         case MERGE_FROM_STREAM: {
>              ^
> ```
> 
> etc.
> 
> I believe this is because the version of javalite codegen plugin (3.0.0 is the latest I can find in maven) is not compatible with latest release of protobuf.
> 
> @RaymondRexxar
> Do you encounter the same issue?

Yes exactly the same

**Comment by RaymondRexxar** [comment]
> According to https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md, it appears the lite codegen is not a separate plugin any more, but instead an option to `java_out`. Have you tried:
> 
> ```groovy-gradle
> protobuf {
>   protoc {
>     artifact = 'com.google.protobuf:protoc:3.8.0-rc-1'
>   }
>   generateProtoTasks {
>     all().each { task ->
>       task.builtins {
>         java {
>           option "lite"
>         }
>       }
>     }
>   }
> }
> ```

Thank you!

**Comment by UmanShahzad** [comment]
Should probably update the docs in the README and elsewhere to note this change.

**Comment by Morteza-Rastgoo** [comment]
My working build.gradle:
```

dependencies {

   implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'io.grpc:grpc-core:1.27.1'
    implementation 'io.grpc:grpc-stub:1.27.1'
    implementation 'io.grpc:grpc-okhttp:1.27.1'
    implementation('io.grpc:grpc-protobuf-lite:1.27.1') {
        exclude module: "protobuf-lite"
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.11.4'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.27.1'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option 'lite'
                }
            }

            task.plugins {
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}
```

**Comment by Pxinxs365** [comment]
> My working build.gradle:
> 
> ```
> 
> dependencies {
> 
>    implementation 'com.squareup.okhttp:okhttp:2.7.5'
>     implementation 'javax.annotation:javax.annotation-api:1.3.2'
>     implementation 'io.grpc:grpc-core:1.27.1'
>     implementation 'io.grpc:grpc-stub:1.27.1'
>     implementation 'io.grpc:grpc-okhttp:1.27.1'
>     implementation('io.grpc:grpc-protobuf-lite:1.27.1') {
>         exclude module: "protobuf-lite"
>     }
> }
> 
> protobuf {
>     protoc {
>         artifact = 'com.google.protobuf:protoc:3.11.4'
>     }
>     plugins {
>         grpc {
>             artifact = 'io.grpc:protoc-gen-grpc-java:1.27.1'
>         }
>         javalite {
>             artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
>         }
>     }
>     generateProtoTasks {
>         all().each { task ->
>             task.builtins {
>                 java {
>                     option 'lite'
>                 }
>             }
> 
>             task.plugins {
>                 grpc {
>                     // Options added to --grpc_out
>                     option 'lite'
>                 }
>             }
>         }
>     }
> }
> ```

Can you represent generateProtoTasks  this part for gradle.kts?

**Comment by jamesward** [comment]
For `build.gradle.kts` I had to do:
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${rootProject.ext["protobufVersion"]}"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:${rootProject.ext["grpcVersion"]}"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.builtins {
                named("java") {
                    option("lite")
                }
            }
            it.plugins {
                id("grpc") {
                    option("lite")
                }
            }
        }
    }
}
```

**Comment by fmatosqg** [comment]
@jamesward 's solution didn't work for me.  Instead of `named("java")` I had to use `id("java")`

```
plugins {
    id("com.android.library")

    id("com.google.protobuf") version "0.8.12"

}

dependencies {
. . .
    implementation("androidx.datastore:datastore-preferences:${globalVersions.dataStore}")
    implementation("androidx.datastore:datastore:${globalVersions.dataStore}")
. . .
    implementation("com.google.protobuf:protobuf-javalite:${globalVersions.protobuf}")

}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${globalVersions.protobuf}"
    }

    generateProtoTasks {
        all().forEach { task ->

            task.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}
```

where `protobuf="3.10.0"` and `dataStore = "1.0.0-alpha05"`
