### ISSUE TITLE
--rxgrpc_out: protoc-gen-rxgrpc: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by lcgao** [google/protobuf-gradle-plugin#316]
Cause: protoc: stdout: . stderr: google/logging/v2/logging.proto: warning: Import google/rpc/status.proto but not used.
google/logging/v2/logging_config.proto: warning: Import google/protobuf/timestamp.proto but not used.
google/speech/v1/cloud_speech.proto: warning: Import google/protobuf/any.proto but not used.
--rxgrpc_out: protoc-gen-rxgrpc: %1 不是有效的 Win32 应用程序。

**Comment by lifenglsf** [comment]
how can you fixed?
