### ISSUE TITLE
C# generated proto in Unity: error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments

### ISSUE THREAD

**Issue by TheRealJagwire** [google/protobuf-gradle-plugin#327]
As the title suggests, I'm seeing the error message:

error CS1729: 'GeneratedClrTypeInfo' does not contain a constructor that takes 7 arguments

When loading the generated csharp file in Unity. It seems like I maybe missed a runtime for or something, but I'm not sure which/what piece I'm missing. Any ideas?

**Comment by TheRealJagwire** [comment]
I found I can download the runtime here: https://www.nuget.org/packages/Google.Protobuf

**Comment by mchiang-goo** [comment]
@TheRealJagwire What are you supposed to exactly do with the new runtime in Unity? I'm using the [grcp unity package](https://github.com/grpc/grpc/tree/master/src/csharp/experimental#unity) which doesn't use a NuGet package and only has .dll's.

But weirdly, I also do in fact have a .nuget directory in my root that I have no idea where it came from. There's a google protobuf 3.8 in there, but my protoc used to compile the generated csharp files is on 3.12.

I'm also on OSX.

**Comment by TheRealJagwire** [comment]
Hey @mchiang-goo, I'm also on a Mac. You just need to put the plugins in an Assets/plugins folder from within Unity. You'll want to make sure you have the DLLs for the correct scripting runtime you're using. For example, in my project settings -> player tab, I have the _scripting backend_ set to **IL2CPP** and the _API Comptability_ Level to **.NET 4.x**

**Comment by mchiang-goo** [comment]
@TheRealJagwire Appreciate the response! I tried your suggestions and still running into the same errors.

What is your setup? Unity version, protobuf, protoc, grpc_csharp_plugin, etc?

**Comment by TheRealJagwire** [comment]
So my setup is a little bit different as I wanted to build my own infrastructure out of protobuf instead of using gRPC. I'm running Unity 2019.3, protobuf gradle plugin version 0.8.10, and protoc version 3.8.0. 

Can you post the errors you're seeing?

**Comment by mchiang-goo** [comment]
I ended up getting it working by using the _correct protoc version to compile_ and match with the Unity runtime. This is my setup:

- Protoc (v3.8) and grpc_csharp_plugin ([grpc-protoc_macos_x64-1.26.0-dev.tar.gz](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)) was used to compile and generate code files from proto.
- [grpc_unity_package.2.26.0-dev.zip](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml)

**Comment by teozkaya** [comment]
That helped me, thanks a lot. Unity Version, Protoc version and grpc_unity_package versions are important.
