### ISSUE TITLE
Support for java-library plugin?

### ISSUE THREAD

**Issue by Ider** [google/protobuf-gradle-plugin#328]
I'd created a java library (`apply plugin: java-library`)with protobuf models instead of using **"android-library"** plugin in Android Studio, since I assume protobuf doesn't need to depend on android components.
However, the IDE can't recognize the generated model classes, although the gradle build works fine.

Checking the code, seems it's because "java-library" plugin is not whitelisted in protobuf plugin
```
    private static final List<String> PREREQ_PLUGIN_OPTIONS = [
            'java',
            'com.android.application',
            'com.android.feature',
            'com.android.library',
            'android',
            'android-library',
    ]
```

Any reason why we can't use java-library for protobuf? 
What's the block for us to whitelist 'java-library'?

Thanks

**Comment by zhangkun83** [comment]
It does look like "java-library" should be added to this list. However, if missing entry in this list were a problem, it would have failed the Gradle build. So I am not sure adding it to the list would solve your problem.

Did you apply the 'idea' plugin as [mentioned in the doc](https://github.com/google/protobuf-gradle-plugin#intellij-idea)?

**Comment by andrew8er** [comment]
That fixed the problem for me.

**Comment by voidzcy** [comment]
Closing, as we had added support for `java-library` since 0.8.12.
