### ISSUE TITLE
Migration to AndroidX : cannot find symbol class EnumVerifier

### ISSUE THREAD

**Issue by AmolVJ** [google/protobuf-gradle-plugin#340]
I am migrating existing project to AndroidX. 
Following is my gradle setup : 

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.8.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}

dependancy {
    implementation 'com.google.protobuf:protobuf-javalite:3.8.0'
}

dependancy {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.10'
}

When I try to run the app, I am getting following "error: cannot find symbol class EnumVerifier" from "com.google.protobuf.Internal.".
So I checked in auto generated file "Internal" and "EnumVerifier" is missing there.

Thanks.

**Comment by ryanwwest** [comment]
Did you solve this issue?
