### ISSUE TITLE
Import "protoc-gen-swagger/options/annotations.proto" was not found or had errors.

### ISSUE THREAD

**Issue by kant111** [google/protobuf-gradle-plugin#353]
I get the following error

```
Import "protoc-gen-swagger/options/annotations.proto" was not found or had errors.
```

How do I add `protoc-gen-swagger` to the plugin?

**Comment by zhangkun83** [comment]
If the directory `protoc-gen-swagger` is under the directory `/path/to/foo`:
```gradle
dependencies {
  protobuf files('/path/to/foo')
}
```

If the directory `protoc-gen-swagger` is in a package file, e.g., `/path/to/foo.zip`:
```gradle
dependencies {
  protobuf files('/path/to/foo.zip')
}
```

**Comment by kant111** [comment]
Hi @zhangkun83 

Thanks for that, it works when I zip the directory and specify the zip file but it fails with the same error when I don't zip it. any idea?

**Comment by zhangkun83** [comment]
I don't know. They should've worked the same. If you can provide a minimal reproducible example, we can take a look.

**Comment by kant111** [comment]
@zhangkun83 is there a way to do?

```
dependencies {
  protobuf files('s3://mybucket/path/to/foo.zip')
}

```

**Comment by zhangkun83** [comment]
No, I don't think Gradle's `files()` API can read from s3.
