### ISSUE TITLE
Confusing warning during Android builds

### ISSUE THREAD

**Issue by stkent** [google/protobuf-gradle-plugin#354]
In a minimal Android test project with these plugins applied:

```groovy
apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'
```

I see the following warning when running `./gradlew app:assembleDebug`:

```none
The com.google.protobuf plugin was already applied to the project: :app and will not be applied again after plugin: android
```

Is there anything I can do to resolve this warning? Does it indicate a problem with project configuration, or with the plugin itself?

It looks like this warning was discussed tangentially in https://github.com/google/protobuf-gradle-plugin/issues/166#issuecomment-333600401; I'm opening this standalone issue to obtain clarification around the meaning of the warning and to revive discussion around removing or lowering the priority of the warning if it is safe to do so.

**Comment by voidzcy** [comment]
That's not really a warning, or at least most times it doesn't mean something is broken and you could ignore it. As mentioned in #166, maybe we could lower the log level to INFO.
