### ISSUE TITLE
How to specify include -I someDir in the plugin?

### ISSUE THREAD

**Issue by kant111** [google/protobuf-gradle-plugin#360]
I have the following directory structure

```
---workspace
     ---src/github/grpc-ecosystem/GAZILLION Protofiles in this directory
     --src/github/golang/GAZILLION Protofiles in this directory
     ---src/github/mycompany/myproject/core/interfaces/proj1/Test1.proto
     ---src/github/mycompany/myproject/core/interfaces/proj1/Test2.proto
```
    

Now inside my `Test2.proto` I have the following

`import "github/mycompany/myproject/core/interfaces/proj1/Test1.proto"`

when I run the build the generateProto task throws an error saying it cannot find `Test1.proto`

I want all the proto files under `src/github/mycompany/myproject/core/interfaces` to be compiled **not all the GAZILLION proto files under** `workspace/src` so If I were to do this protoc I would pass `-I workspace/src` since it only instructs protoc compiler where to find the dependencies. 

I don't how to specify this using this plugin?

Already tried the below although I am not sure what it does

```
dependencies {
    protobuf files('/home/workspace/src')
} 

```

and I get this  error `Execution failed for task ':extractProto'.'

**Comment by voidzcy** [comment]
That's not what it intends to be. The `protobuf` configuration inside `dependencies` closure is used for configuring dependency files (i.e., upstream). Here your issue is `protoc` did not include `Test1.proto` in its invocation, which it should have by default based on your directory structure. Can you post the complete build file?

**Comment by kant111** [comment]
```buildscript {
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.10'
    }
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
  
 
}

plugins {
    id "com.google.protobuf" version "0.8.10"
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'com.google.cloud.tools.jib'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'
    apply plugin: 'com.github.kt3k.coveralls'
    apply plugin: 'jacoco'

    jacoco {
        toolVersion = '0.8.4'
    }

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    repositories {
      mavenLocal()
      jcenter()
    }

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
            options.compilerArgs << "-Xlint:unchecked"
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir "$projectDir/core/interfaces/"
            include '**/*.protodevel'
        }
    }
}

protobuf {
    // Configure the protoc executable
    generatedFilesBaseDir = "$projectDir/codegen"

    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }

    clean {
        delete protobuf.generatedFilesBaseDir
    }

    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.0.0-pre2'
        }
    }

    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {}
            }
            task.generateDescriptorSet = true
            task.descriptorSetOptions.includeImports = true
        }
    }
}

dependencies {
    compile 'com.google.protobuf:protobuf-java:3.0.0'
    compile 'io.grpc:grpc-stub:1.0.0-pre2'
    compile 'io.grpc:grpc-protobuf:1.0.0-pre2'
    compile 'com.google.api.grpc:proto-google-common-protos:1.12.0'
    protobuf files("$System.env.HOME/protoc-gen-swagger.zip")
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'
    
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url 'https://s3-us-west-1.amazonaws.com/peernova-dataprocessing-repo'
        }
        maven {
            url 'http://conjars.org/repo'
        }
        maven {
            url 'https://maven.atlassian.com/repository/public'
        }
    }
}

```

**Comment by voidzcy** [comment]
Given this buildscript, I believe source directories should have been correctly included in `protoc` invocation. You can confirm it by enabling gradle logging (`--debug`) and see the log entry `ProtobufCompile using files [  SOME FILES ]` in `generateProto` task.

I suspect the `import` clause  `"github/mycompany/myproject/core/interfaces/proj1/Test1.proto"` is not correct. It should be `$package_name.Test1.proto`, where `$package_name` should be the same as that you declared by `Test1.proto`'s `package` clause.

**Comment by kant111** [comment]
@voidzcy yes if try `import "package1/test1.proto"` inside `test2.proto` it works. But is there a way to keep `import "github/mycompany/myproject/core/interfaces/proj1/Test1.proto"` ? otherwise I need to make a lot of changes in the directory that could potentially affect another language builds.

**Comment by voidzcy** [comment]
Hmm... I think sadly there isn't. Because really the `import` is not doing the right thing, it has to be the package path of the dependent proto definition. Otherwise, the `protoc` compiler would just think the dependent proto should be from package `github.mycompany.myproject.core.interfaces.proj1` and such a package does not exist (or does not have `test1.proto`). Depending on your project package structure, you may choose to change the `package` clause in your proto files to `package github/mycompany/myproject/core/interfaces/proj1`. But either way, proto being imported needs to be from the package it is defined. Otherwise, it will not work. This works the same way as most languages' package management mechanism.
