### ISSUE TITLE
how to use a specific java version in the proto task?

### ISSUE THREAD

**Issue by shaliniramachandra** [google/protobuf-gradle-plugin#361]
Is there a way to mention a specific java version in the generate proto tasks in addition to the language?  
```
  generateProtoTasks {
        all()*.plugins {
            javapgv {
                option "lang=java"
            }
        }
    }
```
I still want my original source (my project) to be in java 11, but I just want the proto generated .class files to be compiled using java8.

**Comment by voidzcy** [comment]
Sadly there is no such a flipping thing in `protoc`. It always generates the Java code with the oldest Java version it supports. This wouldn't bring in trouble though, as this only generates the Java code but not compile it. You would still do a single compilation for your whole project using your own Java compiler.

**Comment by zhangkun83** [comment]
Why do you want the generated classes to be compiled to a different java version than your own source code? They are going into the same jar anyway.
