### ISSUE TITLE
v0.8.11 isn't available on the Gradle Plugin Portal

### ISSUE THREAD

**Issue by eskatos** [google/protobuf-gradle-plugin#373]
It is on Maven Central
https://search.maven.org/artifact/com.google.protobuf/protobuf-gradle-plugin/0.8.11/jar

But not on the Gradle Plugin Portal
https://plugins.gradle.org/plugin/com.google.protobuf

**Comment by voidzcy** [comment]
Previously we had a permission issue. Now it's there.

**Comment by eskatos** [comment]
Awesome, thanks!
