### ISSUE TITLE
ERROR: org/gradle/api/attributes/LibraryElements

### ISSUE THREAD

**Issue by yanzhonghui** [google/protobuf-gradle-plugin#378]
Hi, anybody! 
I'm an Android programmer. I encountered a problem. after I added `apply plugin: 'com.google.protobuf'` to `app/build.gradle`, Gradle project sync failed. The error message is `ERROR: org/gradle/api/attributes/LibraryElements`. Can you help me？please!
the below is my `build.gradle` file, and my Android Studio version is 3.5.3.

Project/build.gradle
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.11'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

app/build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

android {...}
dependencies{...}
```

**Comment by voidzcy** [comment]
What's the full error message? Is it saying `org/gradle/api/attributes/LibraryElements not found`? This plugin requires Gradle version >= 5.6. Please verify your running Gradle version.

**Comment by yanzhonghui** [comment]
@voidzcy thank U, my gradle version is too low. i have updated and it's works now! thanks.

**Comment by yanzhonghui** [comment]
The problem has already been solved.

**Comment by RdeWilde** [comment]
I was using Gradle 5.6.1 and upgraded to 6.1.1 (newest)

build.gradle.kts
```
tasks {
    "wrapper"(Wrapper::class) {
        gradleVersion = "6.1.1"
        distributionType = Wrapper.DistributionType.ALL
    }
}
```

Still same error though:

```
FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/api/attributes/LibraryElements
> org.gradle.api.attributes.LibraryElements
```

**Comment by yanzhonghui** [comment]
@RdeWilde If you also use Android studio, open your `Project/gradle/wrapper/gradle-wrapper.properties` file and set the `distributionUrl` value like this.
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

**Comment by yanzhonghui** [comment]
@RdeWilde also can...
![image](https://user-images.githubusercontent.com/29450950/73452490-fa39a200-43a4-11ea-85a8-8ff189853f3f.png)

**Comment by FerhatBahceci** [comment]
Running gradle wrapper and refreshing the build.gradle file removed LibrayElements issue for me. Thanks for that!
