### ISSUE TITLE
How to execute the protobuf task at the root project before compiling the subprojects in gradle?

### ISSUE THREAD

**Issue by kant111** [google/protobuf-gradle-plugin#384]
How to execute the protobuf task at the root project before compiling the subprojects in gradle?

I have a multi-project build with the following `build.gradle` in the root project

```
    apply plugin: 'com.google.protobuf'
    
    
    allprojects {
    
    }
    
    subprojects {
    
    }

    protobuf {
    
       protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.10.0'
       }

       plugins {
          grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.23.0'
          }
       }

       generateProtoTasks {
          ofSourceSet('main')*.plugins {
            grpc {}
          }
       }
    }
```

I want the protobuf tasks to be executed first before compiling any of the subprojects because my subprojects depends on the generated java files from protobuf task. so how can I achieve this? I don't want to have the protobuf task in each subproject instead I just want to do it at once at the root project but before compiling the subprojects.

**Comment by voidzcy** [comment]
> I want the protobuf tasks to be executed first before compiling any of the subprojects because my subprojects depends on the generated java files from protobuf task.

Where are your proto files located? 

If your proto files belong to each of your subprojects, each subproject's build will run code generation before compiling so you don't need to do anything special. This is a recommended way of organizing your project structure.   

If your proto files are not in source sets of subprojects, for which they are used (e.g., in some directory of the root project), you will need to apply this plugin on your root project's buildscript just as you did above. Gradle will run root project's tasks before subprojects' tasks. 

What I am suspecting is that you have the mixture of the two approaches. Your root project's generate proto tasks cannot find your proto files as they are not in root project's default source sets. You can use the [`sourceSets {}`](https://github.com/google/protobuf-gradle-plugin#customizing-source-directories) closure to configure it. Anyway, I would recommend you go with the first approach to organize your project structure.
