### ISSUE TITLE
Files in extracted-included-protos are not generated for JS 

### ISSUE THREAD

**Issue by donpaul120** [google/protobuf-gradle-plugin#385]
Gradle Version : 5.6
Protobuf Gradle Plugin : 0.8.11
Java Version  : 12
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.10.0"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.24.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
        all().each { task ->
            task.builtins {
                js {
                    // These options are copied as an example from the previously linked doc, which says
                    // "protoc --proto_path=src --js_out=import_style=commonjs,binary:build/gen src/foo.proto src/bar/baz.proto"
                    // They are interpreted by protoc. I don't know what they mean. You will need to figure out
                    // what options you need.
                    option "import_style=commonjs_strict"
                    option "binary"
                }
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/src"
}
```

**Example Proto**
```
syntax = "proto3";

package google.protobuf;

//import "google/api/annotations.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";

import "google/type/latlng.proto"; //Main Focus

option java_multiple_files = true;
option java_outer_classname = "QueryProto";
option java_package = "com.google.protobuf";

message Query {
    repeated PropertyReference projection = 2;
    repeated KindExpression kind = 3;
}
```

*Generated JS Code*
var jspb = require('google-protobuf');
var goog = jspb;
var proto = {};

//For some reasons i can't find the LatLng file in the js folder, it is not generated!
Everything works fine for Java.

```
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
goog.object.extend(proto, google_protobuf_field_mask_pb);

//For some reasons i can't find this file, it is not generated!!
var google_type_latlng_pb = require('../google/type/latlng_pb.js');
goog.object.extend(proto, google_type_latlng_pb);

goog.exportSymbol('google.protobuf.KindExpression', null, proto);
goog.exportSymbol('google.protobuf.PropertyFilter', null, proto);
goog.exportSymbol('google.protobuf.PropertyFilter.Operator', null, proto);
goog.exportSymbol('google.protobuf.PropertyOrder', null, proto);
goog.exportSymbol('google.protobuf.PropertyOrder.Direction', null, proto);
goog.exportSymbol('google.protobuf.PropertyReference', null, proto);
goog.exportSymbol('google.protobuf.Query', null, proto);
```

**Comment by voidzcy** [comment]
Proto files extracted into `extracted-include-protos` directory are those extracted from an upstream dependency, they are not compiled as they should already have been compiled in their own project. For dependencies that do not compile protos (e.g., googleapis), you would need to add them as `protobuf` dependency. See [here](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies) for explanation of `compile` vs `protobuf` dependencies.

**Comment by donpaul120** [comment]
@voidzcy Thanks very much, it works fine. However, i have an issue where grpc files for JS aren't generated only the messages not the services.

**Comment by voidzcy** [comment]
You would need a grpc-js codegen plugin. In the above code snippet, you use `grpc-java` codgen plugin, so it only generates Java code for grpc services.

_Disclosure: I am not quite familiar with usages of grpc's JS codegen plugin, so the following information may be wrong._
I don't find any grpc JS codegen artifact in maven central, so you probably need to download manually and configure it with 
```
plugins {
    grpc {
        path = ...
    }
}
```
in `protobuf` closure. There is one for [grpc-web](https://github.com/grpc/grpc-web#code-generator-plugin). You can also check out [grpc-node](https://github.com/grpc/grpc-node#grpc-tools). There might also be a way to do it, but I am not familiar with it.

**Comment by donpaul120** [comment]
@voidzcy How can i buy you a Cold BEER... Thanks very much, this worked. 
I used the `grpc-tools` plugin from the `grpc-node` and added it to the path just as you specified, works perfectly. 

Although i had already manually used the plugin to generate the grpc for JS, but doing it within gradle makes sense for me.

Thanks!!!!!!
