### ISSUE TITLE
Proto files in project root directory

### ISSUE THREAD

**Issue by georgwi** [google/protobuf-gradle-plugin#387]
We would like to set up a multi project build similar to this structure:

```
rootProject
   build.gradle
   settings.gradle
   subprojectA
      build.gradle
   proto (git submodule)
      api.proto
      build.gradle
```

The `proto` project is a git submodule that contains our proto files.

I have trouble getting this to work. I have added

```
sourceSets {
   main {
      proto {
         srcDir projectDir // "." behaves the same
      }
   }
}
```

To the `build.gradle` of the proto repository but when I run the task `generateProto` I get the following error:

```
Execution failed for task ':proto:generateProto'.
> protoc: stdout: . stderr: google/protobuf/any.proto:151:10: "google.protobuf.Any.type_url" is already defined in file "build/extracted-protos/main/google/protobuf/any.proto".
  google/protobuf/any.proto:154:9: "google.protobuf.Any.value" is already defined in file "build/extracted-protos/main/google/protobuf/any.proto".
  google/protobuf/any.proto:122:9: "google.protobuf.Any" is already defined in file "build/extracted-protos/main/google/protobuf/any.proto".
  google/protobuf/type.proto: Import "google/protobuf/any.proto" was not found or had errors.
  google/protobuf/type.proto:178:3: "google.protobuf.Any" seems to be defined in "build/extracted-protos/main/google/protobuf/any.proto", which is not imported by "google/protobuf/type.proto".  To use it here, please add the necessary import.
  build/extracted-protos/main/google/protobuf/api.proto: Import "google/protobuf/type.proto" was not found or had errors.
  build/extracted-protos/main/google/protobuf/api.proto:64:12: "Option" is not defined.
  build/extracted-protos/main/google/protobuf/api.proto:97:3: "Syntax" is not defined.
  build/extracted-protos/main/google/protobuf/api.proto:119:12: "Option" is not defined.
  build/extracted-protos/main/google/protobuf/api.proto:122:3: "Syntax" is not defined.
```

Finally, if I change the project structure such that the proto files are in a sub directory within the `proto` repository (and changing above to `srcDir proto`) everything works fine.

My question is: Is it possible to have proto files in the project directory?

**Comment by voidzcy** [comment]
What else does your `proto` directory have? And what are your `protobuf` dependencies? The error shows you have a `protobuf` dependency that pulls in `any.proto` and for some reason there is another copy of it.

**Comment by georgwi** [comment]
You are correct we have some dependencies. Our project is rather large but I have made a minimum example that reproduces the issue. For the proto file I put
```
syntax = "proto3";
import "google/protobuf/any.proto";
```
And for the `build.gradle` I have
```
plugins {
   id "java"
   id "com.google.protobuf" version "0.8.11"
}

repositories {
   mavenCentral()
}

sourceSets {
   main {
      proto {
         srcDir '.'
      }
   }
}

dependencies {
   protobuf 'com.google.protobuf:protobuf-java:3.10.0'
}

protobuf {
   generatedFilesBaseDir = 'src'
   protoc {
      artifact = 'com.google.protobuf:protoc:3.0.0'
   }
   plugins {
      grpc {
         artifact = 'io.grpc:protoc-gen-grpc-java:1.20.0'
      }   
   }
   generateProtoTasks {
      ofSourceSet('main')*.builtins {
         java {
            outputSubDir = 'grpc'
         }
      }
      ofSourceSet('main')*.plugins {
         grpc { }
      }
   }
}
```
This is sufficient for me to get the following error:
```
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: api.proto: warning: Import google/protobuf/any.proto but not used.
  build/extracted-protos/main/google/protobuf/any.proto:151:10: "google.protobuf.Any.type_url" is already defined in file "google/protobuf/any.proto".
  build/extracted-protos/main/google/protobuf/any.proto:154:9: "google.protobuf.Any.value" is already defined in file "google/protobuf/any.proto".
  build/extracted-protos/main/google/protobuf/any.proto:122:9: "google.protobuf.Any" is already defined in file "google/protobuf/any.proto".
```

Again, if I move the `proto` file into a folder and change the proto source directory to that folder it works fine. It seems to me that the plugin is picking up all the proto files inside the `build` directory which makes sense I suppose. Is there a way to avoid that if that is indeed the issue?

**Comment by voidzcy** [comment]
> It seems to me that the plugin is picking up all the proto files inside the build directory which makes sense I suppose.

This reminds me what is happening here. You cannot add the whole `$projectDir` directory to the source directory set where this plugin will look for proto files. When the build process runs, the `build` directory will be created in `$projectDir` directory. The `build` directory is the workspace of Gradle build, which contains protos extracted from upstream dependencies. `extractProto` task runs before `generateProto` task, so `generateProto` task will pick up all proto files in `$projectDir` as user's source proto, including those in `build/extracted-protos`. And proto files in `build/extracted-protos` will be included in proto compilation again as dependent protos.

**Comment by pathammer** [comment]
Seems like there should be some way to exclude the build directory?

**Comment by georgwi** [comment]
Is there a way to explicitly exclude a folder from being searched for `*.proto` files in this case? 

Something like
```
sourceSets {
   main {
      proto {
         srcDir '.'
         exclude 'build/**'
      }
   }
}
```
would be nice

**Comment by voidzcy** [comment]
I suspect it would not work, as the `build` directory is created at runtime after the filter has been applied.

**Comment by georgwi** [comment]
You are right the exclude does not work.

In that case I will change the structure of the java build to

```
rootProject
   build.gradle
   settings.gradle
   subprojectA
      build.gradle
   apiSubproject
      proto (git submodule)
         api.proto
      build.gradle
```

It would be nice if there was some kind of way of making this work since I would have liked the `build.gradle` file to be part of the git submodule repository that contains all the API.

If you can not think of a different way of making this work and this is not something you would consider addressing for the plugin feel free to close this issue. Thank you for your replies @voidzcy
