### ISSUE TITLE
Exclude .proto files from Generated Jar

### ISSUE THREAD

**Issue by lkishor** [google/protobuf-gradle-plugin#390]
There should be a way to exclude .proto files from Generated Jar.
Why would I want to include .proto into a Jar in the first place?
Seem like I am missing something.
Why would I want to expose source protos, when I am providing the JAR to someone?

**Comment by voidzcy** [comment]
As an application, it might make sense to not expose source protos. However, libraries may want to expose their protos so that downstream projects depending on them are able to define proto messages/services with composition of protos from upstream libraries. This plugin was designed at the time `java-library` plugin had not been invented. Even nowadays, a lot of library projects are still using `java` plugin instead of `java-library` plugin. So we keep this plugin to fulfill as much need as possible.

**Comment by lkishor** [comment]
Thanks for the quick reply.

> If the dependency is put in the compile configuration, the proto files are extracted to an extracted-include-protos directory and added to the --proto_path flag of the protoc command line, so that they can be imported by the proto files of the current project. **The imported proto files will not be compiled since they have already been compiled in their own projects**.

I am unable to achieve this, Is there a way to disable bundling of proto files with the Jar?

I tried creating a Jar of just the proto files, and applying it as 
```
implementation files("libs/some-lib-with-protos.jar")
```
Sources are not found.

Or any other hack to disable this would be greatly helpful.

**Comment by voidzcy** [comment]
At which step you failed? What's the error you get?

First, your `some-lib-with-protos` project should apply this plugin and be able to successfully build and create the Jar. Then in your consumer project, adding `implementation files("libs/some-lib-with-protos.jar")` should allow you to import proto types defined in `some-lib-with-protos.jar`.

**Comment by sharpau** [comment]
@lkishor I had the same need (excluding protos from the jar) and was able to do so this way:

`jar {
    exclude '*.proto'
}`

**Comment by lkishor** [comment]
Thanks @sharpau,
It worked like charm, `.proto` files are no longer a part of my .jar file.

Now I am left with a bunch of Empty folders (Which contained proto files).
Any scrips to remove them as well?

**Comment by ejona86** [comment]
[`includeEmptyDirs`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:includeEmptyDirs) will do what you want.

```groovy
jar {
  exclude '*.proto'
  includeEmptyDirs false
}
```

CC @dapengzhang0

**Comment by lkishor** [comment]
Thanks @ejona86.
Solved my problem.

**Comment by bobatsar** [comment]
@ejona86 I'm having the same problem. When building an android library as .aar the .proto files are included.
Where do I have to put the 
```
jar {
  exclude '*.proto'
  includeEmptyDirs false
}
```
I added now
`project.android.packagingOptions.exclude("**/*.proto")`
 to `android.libraryVariants.all`

This seems also working. Is this correct?

**Comment by voidzcy** [comment]
> project.android.packagingOptions.exclude("**/*.proto")
to android.libraryVariants.all

Yep, packingOptions is the thing for Android.
