### ISSUE TITLE
Add support for Java > 8

### ISSUE THREAD

**Issue by NikolayMetchev** [google/protobuf-gradle-plugin#397]
Hello,
Any chance that the protobuf plugin could be made to work with a java version past 8?
Many thanks.

**Comment by ejona86** [comment]
It works with Java versions greater than 8. Why do you believe it does not?

**Comment by NikolayMetchev** [comment]
i get the following error when I run gradle with Java 11:

Unable to find a matching variant of project :proto:
          - Variant 'apiElements' capability metals:proto:unspecified:
              - Incompatible attributes:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Required org.gradle.category 'library' and found compatible value 'library'.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.jetbrains.kotlin.platform.type 'jvm' but no value provided.
          - Variant 'runtimeElements' capability metals:proto:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
              - Other attributes:
                  - Required org.gradle.category 'library' and found compatible value 'library'.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'jvm' but no value provided.

**Comment by ejona86** [comment]
gRPC has a CI that runs the plugin with Java 11. So that's probably not it.

What version of Gradle are you using? What is the version of the plugin you are using?

**Comment by NikolayMetchev** [comment]
Gradle 6.3,
Plugin Version 0.8.12

**Comment by ejona86** [comment]
Hmm... just tested with that version and combination and it worked fine. So there's something about the configuration that matters.

@voidzcy pointed me to #391, which does indeed look very similar. I don't really understand what is going on here; I'm not up-to-speed on variants. It's not clear to me if this is a plugin bug or not.

**Comment by NikolayMetchev** [comment]
It started working for me. I think the problem was unrelated.

**Comment by TacB0sS** [comment]
just cause it might save someone the few hours I wasted... 
IntelliJ -> Preferences -> Build, Execution, Deployment -> Build tools -> Maven -> Gradle

and set **Gradle JVM** to 1.8
make sure you also have JDK 8 installed...

**Comment by ejona86** [comment]
@TacB0sS, the plugin totally works with Java 8 and 11; as I said gRPC uses those versions in a CI and haven't had problems. Please open a separate bug with the error you see.
