### ISSUE TITLE
Please apply the Java plugin or the Android plugin first

### ISSUE THREAD

**Issue by dlamblin** [google/protobuf-gradle-plugin#40]
A complete minimal example `build.gradle` file that uses the new plugins block would be appreciated; https://plugins.gradle.org/plugin/com.google.protobuf suggests the new "plugin mechanism introduced in Gradle 2.1" build script snippet should be:

```Gradle
plugins {
    id "com.google.protobuf" version "0.7.0"
}
```

I tried setting up a very minimal project with only two [proto](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime-proto) [files](http://datamine.mta.info/sites/all/files/pdfs/nyct-subway.proto.txt) in `src/main/proto` (renamed to nyct-subway.proto  and gtfs-realtime.proto) and I can't seem to get the proto plug in to not complain to "Please apply the Java plugin or the Android plugin first", though, you know that's not so specific since http://plugins.gradle.org/plugin/java isn't a plugin.

#### A broken `build.gradle` using new `plugins` mechanism
```Gradle
plugins {
//    id "java" //Having this line or not changes nothing.
    id "com.google.protobuf" version "0.7.0"
}
group 'foo'
version '0.1-SNAPSHOT'

apply plugin: 'java'
apply plugin: "com.google.protobuf"

sourceCompatibility = 1.5

repositories {
    mavenCentral()
}

protobuf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.0.0-alpha-3'
    }
}
```
The message occurs no matter the task, including unrelated tasks like 'wrapper'. For now I'm using the `generateProto` task, because I haven't seen a clear explanation of what tasks this plugin adds by default. That said, it does seem to correctly get the `protoc` dependency on the first invocation.

The `generateProto` task will work correctly when given a `build.gradle` file like:
#### A working `build.gradle` file using the older `buildscript` block
```Gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.7.0'
    }
}

group 'foo'
version '0.1-SNAPSHOT'

apply plugin: 'java'
apply plugin: "com.google.protobuf"

sourceCompatibility = 1.5

repositories {
    mavenCentral()
}

protobuf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.0.0-alpha-3'
    }
}
```

You might consider fixing support for the new plugin mechanism, making the error message much more detailed, or adding a detection specific to the new plugin mechanism to produce an error message about lacking support or compatibility with the suggestion to use the buildscript block style.

**Comment by s4nch3z** [comment]
+1

**Comment by zhangkun83** [comment]
I pushed `0.7.2` to plugins.gradle.org. Unfortunately it doesn't seem to work. Since the new plugin mechanism lacks a testing repo or support for local repo, I will not create more "hopeful fix" releases at this moment. I will go ahead and add instructions in favor of the old mechanism.

**Comment by zhangkun83** [comment]
`0.7.3` is now released with the improved error message.

**Comment by dlamblin** [comment]
While I'm glad there's a resolution, I'm sad the new plugins block does not work.

**Comment by steffenyount** [comment]
If I'm reading it correctly, it looks like there's documentation recommending against using the project.plugins.hasPlugin('java') API based on the PluginContainer and instead it is recommending in favor of using the project.pluginManager.hasPlugin('java') API based on the PluginManager.

https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginAware.html#getPlugins()
vs
https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginAware.html#getPluginManager()

@zhangkun83 would you be willing to attempt another release using this alternate API?
