### ISSUE TITLE
Support for multi-project proto imports

### ISSUE THREAD

**Issue by orionHong** [google/protobuf-gradle-plugin#402]
We would like to have a project structure that looks similar to this where we group all gRPC service project under `rootProject/api`
```
├── rootProject
│   ├── api
│   │   ├── projectA (non-java)
│   │   │   ├── proto
│   │   │   │   ├── projectA.proto
│   │   │   │   └── ...
│   │   ├── projectB (java project) **
│   │   │   ├── proto
│   │   │   │   ├── projectB.proto
│   │   │   │   └── ...
│   │   │   ├── src
│   │   │   ├── build.gradle
│   │   ├── shared-proto
│   │   │  ├── common.proto
│   │   │  └── ...
│   ├── backend
|   │   └── ...
│   └── ...
```
In this case, we found that it is easier to have all proto imports using a path relative to the `rootProject`. For example, in `projectB.proto` we would have an import like
```protobuf
// projectB.proto
import "api/shared-proto/common.proto";
```
Therefore, when we generate the protobuf classes in `projectB`, we tried passing the whole `rootProject` to protobuf so that the extracted `common.proto` would have the full path relative to rootProject: `api/shared-proto/common.proto`:
```gradle
dependencies {
    protobuf files(rootProjectPath)
}
// Also the sourceSets of projectB is defined as
sourceSets {
    main {
        proto {
            srcDir 'proto'
        }
    }
}
```
This currently would cause two issues:
1. Since the `rootProject` also includes the `build` directory of Gradle, we would have a repetitive copy of the extracted proto's. This can be fixed by excluding the copy destination directory when we extract the proto.
> Execution failed for task ':extractProto'.
"Could not copy file '/Users/a/rootProject/api/projectB/build/extracted-protos/.../main/api/projectB/build/extracted-include-protos/main/google/geo/type/viewport.proto' to '/Users/a/rootProject/api/projectB/build/extracted-protos/main/api/projectB/build/extracted-protos/.../main/api/projectB/build/extracted-include-protos/main/google/geo/type/viewport.proto'."
2. If the above issue is gone, we would still have the same issue mentioned in #387 since the `rootProject` includes the source directory.
> Execution failed for task ':generateProto'.
protoc: stdout: . stderr: api/projectB/build/extracted-include-protos/main/google/api/billing.proto:20:1: warning: Import google/api/metric.proto is unused.
  api/projectB/build/extracted-include-protos/main/google/api/http.proto:34:21: "google.api.Http.rules" is already defined in file "google/api/http.proto".
...

After some struggle, I reached to a workaround that can still preserve our project structure. 
I added a `packProjectProto` task that packs proto's in our project and excludes the build directory and proto source directory.
```gradle
def packedProtosDir = "$buildDir/packed-protos"
def packedProtosFileName = "packed-protos.zip"
task packProjectProto(type: Zip) {
    archiveFileName = packedProtosFileName
    destinationDirectory = file(packedProtosDir)
    // rootProjectPath comes from an env variable in our build pipeline
    from(rootProjectPath) { 
        includeEmptyDirs = false
        // avoid including build files
        exclude "api/projectB/build"
        // avoid including the proto already added to our project's sourceSets
        exclude "api/projectB/proto"
        include "**/*.proto"
    }
}

tasks.whenTaskAdded { task ->
    if (task.name == 'extractIncludeProto') {
        task.dependsOn packProjectProto
    }
}

dependencies {
    // Let protobuf read in the generated zip from task packProjectProto
    protobuf files("${packedProtosDir}/${packedProtosFileName}")
}
```
This is the cleanest solution that I can come up with. Please advise if there is a more proper way to include proto's in a multi-project structure. If there's no better solution, can we consider making this configurable to the plugin itself?

**Comment by voidzcy** [comment]
Your project structure is somewhat different from what a standard one would look like, especially your definition of "multi-project" is vague. Based on your project structure, `projectA`, `projectB` and `shared-proto` are subprojects here.  Each of them, with each of their own buildscripts, are independent with each other. The `import` clause in the proto file is really `<package>/<filename>`. However, `api` here is not really a _package_ as it lives outside each subproject's package scope. So if `projectB` needs to import `shared-proto`'s proto, it needs to have a dependency on it and the import path is what the imported proto's package path inside its own project.

For your case, the standard way would be

projectB's `build.gradle`:

```
dependencies {
    protobuf files("../shared-proto")
}

sourceSets {
    main {
        proto {
            srcDir 'proto'
        }
    }
}
```
and the import clause in `projectB.proto` would be
```
import "common.proto";
```

Btw, the standard place of `proto` sources in Java projects is inside `sourceSet` (e.g., `src/main` or `src/test`) so that you do not need to specify it explicit in the buildscript as this plugin can pick it up automatically. Anyway, this is optional and you can still do what you are doing now.

**Comment by orionHong** [comment]
Thanks for the explanation! Yes, you are right. I think there is indeed some weirdness in our CI pipeline, and it is pretty unusual to have the `proto` packages span over multiple sub-projects. I would love to see if there could be some example projects that have sub-projects written in different programming languages. That would be very helpful for future developers.

I'll close this issue for now.
