### ISSUE TITLE
google/protobuf/any.proto: File not found

### ISSUE THREAD

**Issue by davidzchen** [google/protobuf-gradle-plugin#41]
I am trying to use protobuf-gradle-plugin with proto3. However, it seems that the plugin is unable to import runtime proto definitions, such as google/protobuf/any.proto.

According to [the documentation for the Any time](https://developers.google.com/protocol-buffers/docs/proto3?hl=en#any), I added the following to the beginning of my proto file:

```proto
syntax = "proto3";

import "google/protobuf/any.proto";
```

And following the documentation for the protobuf-gradle-plugin:

```groovy
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    ...
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.7.0'
  }
}

...

project(':azkaban-common') {
  apply plugin: 'com.google.protobuf'

  protobuf {
    protoc {
      artifact = 'com.google.protobuf:protoc:3.0.0-beta-1'
    }
  }

  ...
}
```

However, when I tried to build, I got an error saying that `google/protobuf/any.proto` was not found:

```
❯❯❯ gradle build -x test
Picked up JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
:azkaban-common:extractIncludeProto
:azkaban-common:extractProto
:azkaban-common:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':azkaban-common:generateProto'.
> protoc: stdout: . stderr: /Volumes/Ocean/Projects/azkaban/azkaban/azkaban-common/build/extracted-protos/main: warning: directory does not exist.
  /Volumes/Ocean/Projects/azkaban/azkaban/azkaban-common/build/extracted-include-protos/main: warning: directory does not exist.
  google/protobuf/any.proto: File not found.
  workflow.proto: Import "google/protobuf/any.proto" was not found or had errors.
  workflow.proto:27:3: "Any" is not defined.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.922 secs
```

**Comment by ejona86** [comment]
If you add a `compile` dependency to the protobuf runtime, they should automatically get pulled from protobuf's JAR and included with -I. Does that work for you?

**Comment by davidzchen** [comment]
Ah. That did the trick. Thanks!

**Comment by davidzchen** [comment]
Sorry, spoke too early. I forgot that I had copied `any.proto` to `src/main/proto` as a temporary workaround.

I have both of the following dependencies in the subproject where I apply the protobuf plugin:

```groovy
project(':azkaban-comon') {
  ...
  dependencies {
    ...
    compile('com.google.protobuf:protobuf-java:3.0.0-beta-1')
    compile('com.google.protobuf:protobuf-java-util:3.0.0-beta-1')
    ...
  }
  ...
}
```

However, the plugin was still not able to find `any.proto`.

**Comment by zhangkun83** [comment]
I cannot reproduce the issue.
If you download the protobuf-gradle-plugin project sources, and do:
```
$ ./gradlew install && ./gradlew testProjectDependent:test
```
It should succeed. `testProjectDependent` is an example project that uses `any.proto`.

Can you check if `azkaban-common/build/extracted-include-protos/` exists at all? If it does, can you list its content?

**Comment by testark** [comment]
@zhangkun83 I'm having the same problem here. `extracted-include-protos` exists and contains `any.proto` and `empty.proto`, but I get the same errors. I'm using the latest version (`0.7.7`).

**Comment by zhangkun83** [comment]
@testark Can you provide you project for me to debug on, or if it's not feasible, at least a stripped-down project on which I can reproduce the issue?

**Comment by testark** [comment]
@zhangkun83 I will try to put something up in the next couple of hours.

**Comment by jimht011** [comment]
Seems this reported issue was closed but no further solution. Is this resolved in latest version? We got same issue even after copy the code to the path.

**Comment by zhangkun83** [comment]
@jimht011 it would be very helpful for my investigation if you could provide a minimal example project that reproduces this issue.

**Comment by jimht011** [comment]
Thanks Zhang, I'll upload steps shortly. Since this source code comes from tensorflow 0.9, I think it will be a little easy to be reproduced.

**Comment by RishuK** [comment]
@jimht011 Could you please share the steps here if this was solved?

**Comment by yohoph** [comment]
I'm having the same problem here.
I found that may be related to the environment. I can do it under the window, but I can't compile it through Jenkins. @jimht011
