### ISSUE TITLE
Support --experimental_allow_proto3_optional option

### ISSUE THREAD

**Issue by 2is10** [google/protobuf-gradle-plugin#415]
Since protoc version 3.12.0, this option enables the use of `optional` in proto3 for explicit field presence.

https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

When I try to use this option, it’s unrecognized in IntelliJ, and the `optional` keyword is still forbidden.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/647851/85634134-9784c380-b62f-11ea-9ced-d0eac6d6eaa5.png">

<img width="372" alt="image" src="https://user-images.githubusercontent.com/647851/85634087-7de37c00-b62f-11ea-95fd-1058f9bbb0f8.png">

**Comment by 2is10** [comment]
I looked for a way to configure protoc gradle tasks with `--experimental_allow_proto3_optional`, but [GenerateProtoTask.groovy](https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy) doesn’t seem to support it.

**Comment by okorz001** [comment]
I think I have a PR that adds this but I confess I cannot get tests working (even on master)

**Comment by ejona86** [comment]
The experimental flag is intended to allow time for plugin implementors to support optional. We explicitly want to discourage users going off and adding the flag. Implementors generally can run protoc manually without too much heart-ache, or they can use the `test_proto3_optional` file name approach. The flag will become default-enabled soon enough.

In general, passing flags to protoc yields ecosystem issues, as everyone really needs to agree on one set of options. For example, that was one of the issues with javanano. We understand you're excited about optional fields in proto, but _they are still not supported_ at this time.

**Comment by doctorpangloss** [comment]
Please reconsider, this is such a valuable feature, I promise I'll be responsible and move to whatever new syntax you want when it's officially supported.

**Comment by tobq** [comment]
+1

**Comment by hkoosha** [comment]
As now this is impossible to build google ads protos with gradle and this plugin :|
I used this workaround. 


```groovy
protobuf {
    def versionOverride = '3.12.0'

    Map<String, String> notation = [
            group     : 'com.google.protobuf',
            name      : 'protoc',
            version   : versionOverride,
            classifier: project.osdetector.classifier,
            ext       : 'exe',
    ]
    Dependency dep = project.dependencies.add('protobuf', notation)
    File protocFile = configurations['protobuf'].fileCollection(dep).singleFile
    if (!protocFile.canExecute() && !protocFile.setExecutable(true))
        throw new GradleException("Cannot set ${protocFile} as executable")
    println "Using protoc: ${protocFile}"

    def myProtoc = new File("$projectDir/my-protoc.sh");
    myProtoc.delete();
    if(myProtoc.exists())
        throw new GradleException("Cannot set delete ${myProtoc}")
    myProtoc << "#!/bin/bash\n"
    myProtoc << "$protocFile " + '--experimental_allow_proto3_optional $@'
    myProtoc << "\n"
    if(!myProtoc.setExecutable(true))
        throw new GradleException("Cannot set ${myProtoc} as executable")

    protoc {
        path = "${protocFile}"
    }
}
```

**Comment by ejona86** [comment]
It is no longer experimental. https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0
