### ISSUE TITLE
How can I generate Kotlin code instead of java?

### ISSUE THREAD

**Issue by iskuhis** [google/protobuf-gradle-plugin#417]
I am working on a project which is using Protobuf and the generated code Is in java.
Wondering how can I generate Kotlin code instead of java code?

**Comment by voidzcy** [comment]
Protobuf's support for Kotlin is [WIP](https://github.com/protocolbuffers/protobuf/issues/3742).

If you are using gRPC, [gRPC-Kotlin](https://github.com/grpc/grpc-kotlin) provides a protoc plugin for generating service code in Kotlin (with Kotlin-style APIs). But for protobuf messages, the generated code is still Java.

**Comment by pe4enko** [comment]
Now  this WIP is resolved. But i can't find any example how to say gradle plugin to generate kotlin classes.
I'm use this configuaration in build.gradle.kts 
`import com.google.protobuf.gradle.generateProtoTasks
import com.google.protobuf.gradle.id
import com.google.protobuf.gradle.plugins
import com.google.protobuf.gradle.protobuf
import com.google.protobuf.gradle.protoc

val protocVersion: String by project

plugins {
    id("com.google.protobuf")
    idea
}

dependencies {
    api("com.google.protobuf:protobuf-kotlin:$protocVersion")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protocVersion"
    }

    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                id("kotlin")
            }
        }
    }
}`

Is it best way to generate kotlin classes?

**Comment by ejona86** [comment]
@pe4enko, please create a new issue instead of posting here. FWIW, kotlin is a protoc "builtin" not a "plugin"
