### ISSUE TITLE
[Configuration cache] Using plugin in a Java project with configuration cache enabled gives unexpected warning

### ISSUE THREAD

**Issue by jjohannes** [google/protobuf-gradle-plugin#419]
This is a follow up issue to #408

If you apply the latest version of the protobuf plugin to a pure Java project like this (latest Gradle 6.6 nightly):

```
plugins {
  id 'java-library'
  id 'com.google.protobuf' version '0.8.13-SNAPSHOT'
}
```

And use the configurations cache

```
./gradlew assemble --configuration-cache
```

You'll get the following _configuration cache_ warning:

```
value provider(?) failed to unpack provider
  fieldvariantName of com.google.protobuf.gradle.GenerateProtoTask
    task:Server-Protocol-Buffer:generateProto of type com.google.protobuf.gradle.GenerateProtoTask
      java.lang.IllegalStateException: variant should not be used in a Java project
```

This is because Gradle tries to read the [variantName](https://github.com/google/protobuf-gradle-plugin/blob/7c89f8199c60caba5534c44c88cdb377a16a80e6/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L103) field which is backed by the `variant` property. The getter of that property then throws the "variant should not be used in a Java project" error.

I think this can be fixed by making `variantName` transient similar to how it was done for the backing `variant` field in #408. //cc @gavra0

**Comment by voidzcy** [comment]
Are you interested in creating a PR for the fix?
