### ISSUE TITLE
how to pass extra arguments to protoc for generating python modules

### ISSUE THREAD

**Issue by zyxue** [google/protobuf-gradle-plugin#424]
I have been able to generate python pb2 files following the instruction on https://github.com/google/protobuf-gradle-plugin#default-outputs.

But I'd also like pass `--mypy_out=output/location` argument (https://github.com/dropbox/mypy-protobuf) to `protoc`, how could I do that, please?

**Comment by voidzcy** [comment]
It would be

```
protobuf {
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                mypy {
                    option 'output/location'
                }
            }
        }
    }
}

```
Basically, builtin/plugin options (`--xxx_out=...` options in `protoc` invocations) are configured via `option` property of the corresponding builtin/plugin configuration closure.

You can see some description at [configure what to generate](https://github.com/google/protobuf-gradle-plugin#configure-what-to-generate).

**Comment by ejona86** [comment]
Actually, since output/location is just the normal location, not an option to the plugin, you'd just do:

```
protobuf {
    generateProtoTasks {
        all()*.plugins {
             // no need to specify 'option', and specifying it won't change the output directory
            mypy { }
        }
    }
}
```

The plugin will choose the output directory.

**Comment by zyxue** [comment]
@voidzcy , it worked thank you! I used

```
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                // Generates Python code in the output folder:
                python { }
            }

            task.plugins {
                mypy { }
            }
        }
    }
```

@ejona86 , what does `all()*` mean, please?

**Comment by voidzcy** [comment]
Oops, thanks @ejona86 for the correction. 😢 

@zyxue 

> what does all()* mean, please?

It is actually the `*.` operator. According to [Groovy doc](http://docs.groovy-lang.org/latest/html/documentation/working-with-collections.html#Collections-Gettingefficientwiththestar-dotoperator)
> The "star-dot" operator is a shortcut operator allowing you to call a method or a property on all elements of a collection

So it is calling the configuration method on each element returned by `all()`.

**Comment by zyxue** [comment]
thank you @voidzcy . a follow-up question, please.

Currently, the python output ends in

```
myapp/build/generated/source/proto/main/python/com/abc/myapp/api/myapp_pb2.py
```
and the pyi (from mypy) file ends in 
```
myapp/build/generated/source/proto/main/mypy/com/abc/myapp/api/myapp_pb2.pyi
```

if `option 'output/location'` won't work, is it still possible to make the output go to the same directory as it doesn't make sense for `.py` and `.pyi` files to be separate?

**Comment by voidzcy** [comment]
Each builtin/plugin has a property for setting its output directory. So it should be something like

```
protobuf {
    generateProtoTasks {
        all()*.plugins {
            mypy {
               outputSubDir 'path/to/output' 
            }
        }
    }
}
```

You can set the `outputSubDir` for both `python` builtin and `mypy` plugin. Note the path you set should be relative to each GenerateProtoTask's `outputBaseDir`,  which the default is `"$generatedFilesBaseDir/$sourceSet`. There is an example in the [README](https://github.com/google/protobuf-gradle-plugin#change-where-files-are-generated).

**Comment by zyxue** [comment]
Thank you! just a nit: there should be an equal sign `outputSubDir = 'path/to/output'`.

**Comment by MrBigBanks** [comment]
> I have been able to generate python pb2 files following the instruction on https://github.com/google/protobuf-gradle-plugin#default-outputs.
> 
> But I'd also like pass `--mypy_out=output/location` argument (https://github.com/dropbox/mypy-protobuf) to `protoc`, how could I do that, please?

DENIED*

**Comment by MrBigBanks** [comment]
- [ ] ACCSSS DENIED

1. ×
