### ISSUE TITLE
protoc --proto_path miss "="

### ISSUE THREAD

**Issue by dbds** [google/protobuf-gradle-plugin#428]
GenerateProtoTask.groovy, line 570: 

```groovy
    // The source directory designated from sourceSet may not actually exist on disk.
    // "include" it only when it exists, so that Gradle and protoc won't complain.
    List<String> dirs = includeDirs.filter { it.exists() }*.path.collect { "-I${it}" }
    logger.debug "ProtobufCompile using directories ${dirs}"
    logger.debug "ProtobufCompile using files ${protoFiles}"
```

List<String> dirs = includeDirs.filter { it.exists() }*.path.collect { "-I${it}" }
should be modify to: 
List<String> dirs = includeDirs.filter { it.exists() }*.path.collect { "-I=${it}" }

**Comment by ejona86** [comment]
Why do you say that? That `-I` mirrors the normal flag to compilers which doesn't use an `=`. The protoc help shows there is no `=`:

```
Usage: ./bin/proto3.12/bin/protoc [OPTION] PROTO_FILES
Parse PROTO_FILES and generate output based on the options given:
  -IPATH, --proto_path=PATH   Specify the directory in which to search for
...
```

**Comment by dbds** [comment]
https://developers.google.com/protocol-buffers/docs/overview

IMPORT_PATH specifies a directory in which to look for .proto files when resolving import directives. If omitted, the current directory is used. Multiple import directories can be specified by passing the --proto_path option multiple times; they will be searched in order. **-I=_IMPORT_PATH_** can be used as a short form of --proto_path.

**Comment by dbds** [comment]
this is my error:

```
> Task :ddz-server-room:generateProto FAILED
Caching disabled for task ':ddz-server-room:generateProto' because:
  Build cache is disabled
Task ':ddz-server-room:generateProto' is not up-to-date because:
  Class path of task ':ddz-server-room:generateProto' has changed from 319bc6fabd4221c7aa440a2b20e2e22a to 33533dba9ac4d6309d4a59cdec2f66c0.
Resolved artifact: C:\Users\ttxzm\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\2.5.0\6c8857b03e5065f91855bd004dd6b2f4c6bb0dc6\protoc-2.5.0-windows-x86_64.exe
[C:\Users\ttxzm\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\2.5.0\6c8857b03e5065f91855bd004dd6b2f4c6bb0dc6\protoc-2.5.0-windows-x86_64.exe, -ID:\repo\ttigd\upgs\ddz-server-room\src\main\proto, -ID:\repo\ttigd\upgs\ddz-server-room\build\extracted-protos\main, -ID:\repo\ttigd\upgs\ddz-server-room\build\extracted-include-protos\main, --java_out=D:\repo\ttigd\upgs\ddz-server-room/src//main/java, D:\repo\ttigd\upgs\ddz-server-room\src\main\proto\DDZRoomCmd.proto]
:ddz-server-room:generateProto (Thread[Execution worker for ':',5,main]) completed. Took 0.049 secs.

Execution failed for task ':ddz-server-room:generateProto'.
> protoc: stdout: . stderr: DDZRoomCmd.proto:9:12: "IllegalState" is not defined.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by ejona86** [comment]
> -I=IMPORT_PATH can be used as a short form of --proto_path.

It seems that documentation is wrong. I've filed b/165794917 internally to look into fixing it.

The error is:
> 9:12: "IllegalState" is not defined.

That error should never occur due to a wrong `-I`. If the import path is wrong, you'd get a file import error, not a missing symbol. You've either not imported a file within the same package that contains `IllegalState` or you forgot to use prefix the symbol with its package name.

**Comment by dbds** [comment]
thanks
