### ISSUE TITLE
Support earlier version of glibc

### ISSUE THREAD

**Issue by aantono** [google/protobuf-gradle-plugin#43]
When trying to use a pre-compiled linux protoc binary, getting an error:
```/lib64/libc.so.6: version `GLIBC_2.14' not found```
If possible, recompile with a lower version (2.10 or 2.12) to support a wider range of Linux OS.

**Comment by ejona86** [comment]
What version of protobuf were you trying to use? We would expect new builds to support glibc 2.12 or later. I sort of assume you are using protobuf 2.6.1 because of google/protobuf#781.

**Comment by aantono** [comment]
I'm using the protobuf 2.6.1 and have glibc 2.12 installed on my Linux box. RHEL CentOS 6.4

**Comment by ejona86** [comment]
It would be nice to do a fixed build. But let's track that in google/protobuf#781, since it is its release artifacts.
