### ISSUE TITLE
Cannot build Android with Firebase-inAppMessage

### ISSUE THREAD

**Issue by Tommy-Kanzaki** [google/protobuf-gradle-plugin#432]
im facing below error while building app:

/Users/home/.gradle/caches/transforms-2/files-2.1/01129c75def25dec2e0418b329b8019d/jetified-protobuf-javalite-3.11.0.jar: R8: Type com.google.protobuf.DurationOrBuilder is defined multiple times: /Users/home/.gradle/caches/transforms-2/files-2.1/01129c75def25dec2e0418b329b8019d/jetified-protobuf-javalite-3.11.0.jar:com/google/protobuf/DurationOrBuilder.class, /Users/home/AndroidStudioProjects/vmedia-recorder-android/pb/build/intermediates/runtime_library_classes_jar/release/classes.jar:com/google/protobuf/DurationOrBuilder.class

After adding firebase-inAppMessage library, this error occurred.
Can you tell me any solutions?

**Comment by voidzcy** [comment]
You are probably including more than one prtobuf lite dependencies, probably one `protobuf-lite` and one `protobuf-javalite`. Firebase android has migrated from `protobuf-lite` to `protobuf-javalite` (https://github.com/firebase/firebase-android-sdk/pull/1534), so you need to upgrade all your firebase SDKs and make sure that you only see `protobuf-javalite` from `gradle dependencies`.
