### ISSUE TITLE
Missing 'Client' classes while generating code for PHP

### ISSUE THREAD

**Issue by kkochanski** [google/protobuf-gradle-plugin#434]
Hello,

I'm using this plugin to generate code for Java and PHP. While doing it for PHP, in the build, I'm missing classes that allow calling procedures.

Proto file example:
```
syntax = "proto3";

package helloworld;

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string message = 1;
}
```

Output generated by Gradle plugin:
```
├── GPBMetadata
│   └── Helloworld.php
└── Helloworld
    ├── HelloReply.php
    └── HelloRequest.php

2 directories, 3 files
```

Output generated by php-protoc-plugin (https://grpc.io/docs/languages/php/quickstart/#php-protoc-plugin)
```
├── GPBMetadata
│   └── Helloworld.php
└── Helloworld
    ├── GreeterClient.php
    ├── HelloReply.php
    └── HelloRequest.php

2 directories, 4 files
```

While playing with Graddle, I was using plugin versions:
`0.8.11` and `0.8.11`

Protoc versions:
`3.12.2` and `3.13.0`

`io.grpc:protoc-gen-grpc-java` versions:
`1.30.0` and `1.32.1`

At PHP level I used Protoc `3.11.0`and `php-protoc-plugin` `1.28.1`

What should I do at the Gradle plugin level, to ensure that the missing 'Client' class will be generated?

**Comment by voidzcy** [comment]
Seems the grpc PHP plugin is not configured correctly. Can you post the `protobuf{ }` block of your buildscript? Make sure you have a plugin configured with the path to where `php-protoc-plugin` is installed in the `plugins{ }` block.

**Comment by kkochanski** [comment]
You're right, I forgot to add that one:
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.12.2"
    }
    generatedFilesBaseDir = "$projectDir/build/generated/grpc-code-packages"
    clean {
        delete generatedFilesBaseDir
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.30.0"
        }
        javapgv {
            artifact = "io.envoyproxy.protoc-gen-validate:protoc-gen-validate:0.3.0"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
            javapgv {
                option "lang=java"
            }
        }

        all().each { task ->
            task.builtins {
                java { }
                php { }
            }
        }
    }
}
```


I tried to add to **plugins** section data for `php-protoc-plugin`, but it build didn't finish with expected results:
```
plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.30.0"
        }
        javapgv {
            artifact = "io.envoyproxy.protoc-gen-validate:protoc-gen-validate:0.3.0"
        }
        phpProtocPlugin {
            path = "/dummy/path/grpc_php_plugin"
        }
    }
```

Instead of `phpProtocPlugin`, I tried also `phpprotocplugin`, `php-protoc-plugin` and `php_protoc_plugin`

**Comment by voidzcy** [comment]
Did you also configure the `phpProtocPlugin` plugin in `generateProtoTasks{ }`? The `plugins{}` block only locates the plugin executables, you need to configure the code generation tasks to run with located plugins, just as what has been done for `grpc` and `javapgv` plugins.

**Comment by kkochanski** [comment]
```
plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.30.0"
        }
        javapgv {
            artifact = "io.envoyproxy.protoc-gen-validate:protoc-gen-validate:0.3.0"
        }
        phpprotocplugin {
            path = "/dummy/path/grpc_php_plugin"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
            javapgv {
                option "lang=java"
            }
            phpprotocplugin {}
        }

        all().each { task ->
            task.builtins {
                java { }
                php { }
            }
        }
    }
```

Given configuration works, thanks a lot!
