### ISSUE TITLE
README.md contains several references to the (now deprecated) "compile" and "testCompile" configs

### ISSUE THREAD

**Issue by jaimet** [google/protobuf-gradle-plugin#438]
Now that [issue 242](https://github.com/google/protobuf-gradle-plugin/issues/242) is closed/fixed, could you please update [README.md](https://github.com/google/protobuf-gradle-plugin/blob/master/README.md) to change the "compile" configurations to "implementation", and the "testCompile" configuration to "testImplementation". Thank you.

**Comment by arnoob16** [comment]
Can I work on this issue?

**Comment by voidzcy** [comment]
> Can I work on this issue?

Yeah, go ahead. I was thinking about clean up everything including examples and tests. But if you want to just work on the doc and examples only, that's fine.

**Comment by ejona86** [comment]
This was fixed by #454
