### ISSUE TITLE
Code generation produces invalid classes with missing enum constants.

### ISSUE THREAD

**Issue by Orbyt** [google/protobuf-gradle-plugin#442]
**Description**
The classes produced by the code generation process appear to be incorrect and contain references to constants which are undefined. This results in errors when attempting to rebuild an Android project.

<img width="466" alt="Screen Shot 2020-11-02 at 12 54 18 PM" src="https://user-images.githubusercontent.com/8474654/97918294-c3fdca00-1d0a-11eb-8347-5b7d112544a1.png">
<img width="434" alt="Screen Shot 2020-11-02 at 12 54 42 PM" src="https://user-images.githubusercontent.com/8474654/97918298-c52ef700-1d0a-11eb-8678-a7a0582585b0.png">
<img width="416" alt="Screen Shot 2020-11-02 at 12 54 53 PM" src="https://user-images.githubusercontent.com/8474654/97918299-c5c78d80-1d0a-11eb-9bfb-4d823b21fcb7.png">

**Protobuf integration details**
These issues have been seen while attempting to integrate Protobuf into an Android project. Several tutorials we're followed in an attempt to produce a correct integration (such as [this one](https://proandroiddev.com/protobuf-in-android-55b01d855c40) and [this one](https://proandroiddev.com/how-to-setup-your-android-app-to-use-protobuf-96132340de5c)).

`classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.13'` was added to the project level `build.gradle` file.

The code noted below was added to the module level `build.gradle` file.
```
apply plugin: 'com.google.protobuf'

sourceSets {
    main.java.srcDirs +=  "${protobuf.generatedFilesBaseDir}/main/javalite"
    main.java.srcDirs += "$projectDir/src/main/proto"
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.0.0-rc-2'
    }
    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.plugins {
                javalite { }
            }
        }
    }
}


dependencies {
    // ........
    implementation 'com.google.protobuf:protobuf-javalite:4.0.0-rc-2'
}
```

I do not believe the issue is related to the setup described above, as the undefined variables in the generated classes are not specific to a project.

**Comment by voidzcy** [comment]
Can you try a clean build? I remember I experienced something similar in the past when trying to rebuild after modifying proto definitions, like what's being described in #331.

**Comment by Orbyt** [comment]
@voidzcy I've invalidated caches, cleaned, and performed a full rebuild, but the issue persists. For reference, the `.proto` file in used is the [sample file provided by Google](https://github.com/protocolbuffers/protobuf/blob/master/examples/addressbook.proto).

**Comment by Orbyt** [comment]
It has been pointed out to me by another developer that `GeneratedMessageLite.MethodToInvoke.IS_INITIALIZED` doesn't even exist anymore (see [commit](https://github.com/protocolbuffers/protobuf/commit/176f7db#diff-3d54e4b66a8ae5df2da412b01073234d42cddc9e98bdd2ba1de096198577ab8bL270)), which can be verified by viewing the source:

```
/**                                                                  
 * Defines which method path to invoke in {@link GeneratedMessageLite
 * #dynamicMethod(MethodToInvoke, Object...)}.                       
 *                                                                   
 * <p>For use by generated code only.                                
 */                                                                  
public static enum MethodToInvoke {                                  
  // Rely on/modify instance state                                   
  GET_MEMOIZED_IS_INITIALIZED,                                       
  SET_MEMOIZED_IS_INITIALIZED,                                       
                                                                     
  // Rely on static state                                            
  BUILD_MESSAGE_INFO,                                                
  NEW_MUTABLE_INSTANCE,                                              
  NEW_BUILDER,                                                       
  GET_DEFAULT_INSTANCE,                                              
  GET_PARSER;                                                        
}                                                                    
```

**Comment by fis** [comment]
Making a few educated guesses from [current java/lite.md documentation](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md), I think you should no longer need a separate `protoc-gen-javalite` dependency, because classes using the lite runtime are now generated with `--java_out=lite:...` flags to protoc, rather than `--javalite_out=...`. I do not know how that translates to Gradle terms, hoewver.

In any case, version 3.0.0 for the protoc plugin predates that commit, so it makes sense it would be generating references to `IS_INITIALIZED`.

**Comment by fis** [comment]
Oh, looks like what this means in Gradle-speak is documented on this plugin's readme. See the example under "Starting from Protobuf 3.8.0, lite code generation is built into protoc's "java" output" on https://github.com/google/protobuf-gradle-plugin

**Comment by voidzcy** [comment]
@fis Thanks for the reminder.

@Orbyt Please see details at [this section in README](https://github.com/google/protobuf-gradle-plugin#default-outputs).

**Comment by Orbyt** [comment]
Modifying the `protobuf` block as shown below appears to result in a working integration.

```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.0.0-rc-2'
    }

    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}
```
I appreciate the help @voidzcy, @fis.
