### ISSUE TITLE
Gradle Kotlin DSL changed method signature of NamedDomainObjectContainerExtensionsKt.invoke

### ISSUE THREAD

**Issue by andrewparmet** [google/protobuf-gradle-plugin#444]
In KtDslCompatibilityUtils.java the plugin calls `NamedDomainObjectContainerExtensionsKt.invoke(container, block)` with `block` being a `Function1<? super NamedDomainObjectContainerScope<T>, Unit>`. In the latest Gradle build (6.8-milestone-2), that signature has been changed to `Action<NamedDomainObjectContainerScope<T>>`: https://github.com/gradle/gradle/commit/593001e74f21a67ecc8d6f6c6174818f02eab007, so builds using the Kotlin DSL fail using new builds.

**Comment by Shakezulla57** [comment]
Is there a work around for this?

**Comment by hua0512** [comment]
A workaround is to rewrite the KtDslCompatibilityUtils.configureNamedDomainObjectContainer and therefore functions that depends on it.
Then your have:
> configureNamedDomainObjectContainer:
`fun <T : Any> configureNamedDomainObjectContainer(
  container: NamedDomainObjectContainer<T>,
  action: Action<NamedDomainObjectContainerScope<T>>
): NamedDomainObjectContainer<T> {
  return container.invoke(action)
}`

> id:
`fun <T : Any> NamedDomainObjectContainerScope<T>.id(id: String, action: (Action<T>)? = null) {
  action?.let { create(id, action) }
    ?: create(id)
}`

> plugins:
`fun ProtobufConfigurator.plugins(action: NamedDomainObjectContainerScope<ExecutableLocator>.() -> Unit) {
  plugins(closureOf<NamedDomainObjectContainer<ExecutableLocator>> {
    configureNamedDomainObjectContainer<ExecutableLocator>(this, action)
  })
}
`

> task builtins:
`fun GenerateProtoTask.builtins(action: NamedDomainObjectContainerScope<GenerateProtoTask.PluginOptions>.() -> Unit) {
  builtins(closureOf<NamedDomainObjectContainer<GenerateProtoTask.PluginOptions>> {
    configureNamedDomainObjectContainer<GenerateProtoTask.PluginOptions>(this, action)
  })
}
`

> task plugins:
`fun GenerateProtoTask.plugins(action: NamedDomainObjectContainerScope<GenerateProtoTask.PluginOptions>.() -> Unit) {
  plugins(closureOf<NamedDomainObjectContainer<GenerateProtoTask.PluginOptions>> {
    configureNamedDomainObjectContainer<GenerateProtoTask.PluginOptions>(this, action)
  })
}
`

Actually you just have to change _configureNamedDomainObjectContainer_ and _id_ if you are able to build your local protobuf gradle plugin.

**Comment by ejona86** [comment]
CC @EdGue42 for https://github.com/grpc/grpc-java/issues/8027

**Comment by voidzcy** [comment]
Gradle has reverted the API deletion at gradle/gradle#15508. Try upgrading Gradle to 6.8 RC3 or later if you are experiencing this issue.

We will still try to migrate to Action-based API, but currently we are not able to find newer releases of `org.gradle:gradle-kotlin-dsl` containing the new API. Filed https://github.com/gradle/gradle/issues/16884 to see if anyone from Gradle can give a pointer.

**Comment by iNikem** [comment]
Seems to be solved by #531
