### ISSUE TITLE
Build fails with MissingPropertyException: No such property: generatedFilesBaseDir

### ISSUE THREAD

**Issue by kgribov** [google/protobuf-gradle-plugin#445]
Exception: 
```
Caused by: groovy.lang.MissingPropertyException: No such property: generatedFilesBaseDir for class: java.lang.String
	at com.google.protobuf.gradle.ProtobufPlugin$_addGenerateProtoTask_closure19.doCall(ProtobufPlugin.groovy:339
```

How to reproduce:
Extract versions from https://github.com/google/protobuf-gradle-plugin/blob/master/examples/exampleProject/build.gradle to **gradle.properties**
If version variable will be defined in gradle.properties as 
```
protobuf = 3.0.0
```
You will get an exception.

If you use any other name for this variable - plugin works.

I can't reproduce similar behavior with other java/kotlin plugins like jooq, detekt and etc.

**Comment by voidzcy** [comment]
`project.protobuf` is a reserved extension name used by this plugin (aka, the `protobuf` closure you use to configure things). So you should not override it (gradle.properties configures the `project` object). Maybe change to something like

```
protobufVersion = 3.0.0
```

**Comment by kgribov** [comment]
yes, changing the name of variable solve the issue. 

The problem is that it is not so obvious, that I can't use such naming and exception doesn't help me in this at all... and as I mentioned above - other plugins are not affected by such naming.

This issue is not critical for sure, but will be cool to not have such behavior in future.

Thanks!
