### ISSUE TITLE
GenerateProtoTask is not cache relocateable between OS because of `alternativePaths`

### ISSUE THREAD

**Issue by runningcode** [google/protobuf-gradle-plugin#457]
The GenerateProtoTask adds an OS specific binary to the `alternativePaths` input. This path is OS specific meaning that the cache cannot be re-used between linux, macOS and windows.
![GenerateProtoTask](https://user-images.githubusercontent.com/332597/103747930-a77c5780-5003-11eb-9591-23a1be0fdfb7.png)

 The tasks output should be the same no matter what kind of protoc dependency it is using so one solution would be to remove this as an input to the task.

**Comment by ejona86** [comment]
The output would be different with different versions of protoc, so I don't think simply removing the input is appropriate.

**Comment by runningcode** [comment]
By different versions do you mean that the output is different depending on the OS? Or just the version number of protoc? If it is just the version number of protoc perhaps we can just make the version number of protoc an input?

**Comment by ejona86** [comment]
Well, it would seem the group ID and artifact ID are also appropriate. So "exclude the classifier" would seem the more conservative approach.

Note that the change you're suggesting seems to mean alternative paths could no longer be file-based, but we'll still need a file-based input if the user specifies a `path` directly.

How does the dependency cache normally handle things like different javac versions? It just assumes that all "Java 8" versions behave the same? And I guess for things like Groovy/Kotlin you pin to a specific version?

**Comment by ejona86** [comment]
Also, if we stop using file-based input -SNAPSHOT versions may stop working correctly.

**Comment by mvitaly** [comment]
I'm hitting this issue too.

How about adding a new property to the task that will be used for caching (will not have os classifier or os extension) and ignore the alternativePaths from cache key?

**Comment by ejona86** [comment]
Fixed by #560
