### ISSUE TITLE
How to set proto file options without changing the proto files?

### ISSUE THREAD

**Issue by Hendrik-H** [google/protobuf-gradle-plugin#462]
In a proto file I can defined options like `java_multiple_files`, `java_package` and `java_outer_classname`. But what if I'm just pulling the proto file as a dependency and the creator of the file did not set these options, for example as the service was written in go? Is there a way to specify those options in my own build?

**Comment by ejona86** [comment]
No, there's not a way to specify that during the build. Generally speaking, you should get the proto fixed upstream.

**Comment by Hendrik-H** [comment]
hm, ok, but isn't it a bit "ugly" that you basically need to end up setting options for every language?

**Comment by ejona86** [comment]
There's not much of an alternative if you want a canonical proto file for a service. In any case, this is a limitation of `protoc` and can't be changed as part of this repository. protoc is maintained by https://github.com/protocolbuffers/protobuf.

**Comment by Hendrik-H** [comment]
thanks
