### ISSUE TITLE
Cannot access 'com.google.protobuf.AbstractMessageLite' which is a supertype of 'com.google.protobuf.GeneratedMessageLite'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by tucson-tom** [google/protobuf-gradle-plugin#466]
Maintaining a Kotlin project that was dropped on me.  I'm not too familiar with Kotlin and even less familiar with protobuf.  Getting about 1,100 variations on the error message above in the build after updating to the latest stable Android Studio (Gradle version doesn't seem to matter).  The same project was compiling just fine on this machine with a previous version of Android Studio.

I've tried all the usual suspects (invalidate cache and restart, search Google for the error, check versioning in build.gradle files, etc).  Not even sure where to begin to look.

Edit - after messing around with the Gradle files for a while, I still have the same issue.  Here's what I've currently got:

build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.4.30'
    ext.anko_version = '0.10.8'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.14'
        classpath 'com.google.gms:google-services:4.3.5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Project build.gradle (:protobuf_model):

```
apply plugin: 'kotlin'
apply plugin: 'com.google.protobuf'

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.8.0"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs += file("${protobuf.generatedFilesBaseDir}/main/javalite")
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    protobuf 'com.google.protobuf:protobuf-java:3.10.0'
    implementation "com.google.protobuf:protobuf-javalite:3.8.0"
}

sourceCompatibility = "1.7"
targetCompatibility = "1.7"
```

**Comment by tucson-tom** [comment]
Building the `protobuf_model` module by itself raised a ton of duplicate class messages like `error duplicate class "com.google.protobuf.Any"`.  I deleted the entire 'build' directory and built it again and the errors went away but so did the tree.  I then changed 'srcDirs' above to `/main/java` instead of `/main/javalite` and rebuilt it and the tree reappeared and also no errors with the module.

Then I went and deleted the `app/build` directory and rebuilt the project.  Unfortunately, I still get the `Cannot access 'com.google.protobuf.AbstractMessageLite' which is a supertype of 'com.google.protobuf.GeneratedMessageLite'....` message.

**Comment by tucson-tom** [comment]
I've now created a 100% brand spankin' new project that minimally produces the same error:

[PROTOBUFBUGTEST.zip](https://github.com/google/protobuf-gradle-plugin/files/5960926/PROTOBUFBUGTEST.zip)

I was hoping that creating a new project would somehow make the problem go away on its own, but unfortunately it's still showing up:

![image](https://user-images.githubusercontent.com/2447055/107560377-85de3500-6b9a-11eb-9b32-57e4caff522f.png)

**Comment by voidzcy** [comment]
Because your `protobuf_model` module is pulling in `protobuf-javalite` as an `implementation` dependency. It's not exposed to the consuming module, which is `app`. All you need to do is change it to

```
api "com.google.protobuf:protobuf-javalite:3.8.0"
```

You can find more details for `implementation` vs `api` in [this Gradle doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies).

**Comment by tucson-tom** [comment]
The main repo README says:

```
Starting from Protobuf 3.8.0, lite code generation is built into protoc's "java" output. Example:

dependencies {
  // You need to depend on the lite runtime library, not protobuf-java
  implementation 'com.google.protobuf:protobuf-javalite:3.8.0'
}

protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.8.0'
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        java {
          option "lite"
        }
      }
    }
  }
}
```

No mention of `api` anywhere.  Switching to `api` fixes the issue.

**Comment by voidzcy** [comment]
The consideration of `implementation` vs `api` is specific to user projects, nothing to do with this plugin. Code snippets given in docs are just example usages. That's being said, the issue you encountered is not related to this plugin, it's about the general usage of Gradle.
