### ISSUE TITLE
How to generate Javadoc?

### ISSUE THREAD

**Issue by milbrandt** [google/protobuf-gradle-plugin#469]
Generating Java classes I tried also to generate sources- and javadoc-jars.
Unfortunately both jars are empty.
When I copy the generated Java sources and then compile them (removing protoc) sources- and javadoc-jars contain the expected output.

```groovy
plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.8.14'
}

dependencies {
  // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
  implementation 'com.google.protobuf:protobuf-java:3.14.0'
}

protobuf {
  protoc {
    // The artifact spec for the Protobuf Compiler
    artifact = 'com.google.protobuf:protoc:3.14.0'
  }
}

java {
  withSourcesJar()
  withJavadocJar()
}
```

If it is possible some documentation would be very helpful.

**Comment by milbrandt** [comment]
The work-around from #109 helped be to generate the requested sources and doc-jars:

```groovy
sourceSets {
  main {
    proto {
      srcDir '../Middleware.Messages'
      exclude 'obj/**'
      exclude 'bin/**'
    }
    java {
      srcDirs 'build/generated/source/proto/main/java'
    }
  }
}
```

**Comment by voidzcy** [comment]
Not polluting project source sets with generated code (but only add as inputs into compilation tasks) is working as intended for this plugin, as it might have other implications (e.g., Javadoc, checkStyle, etc).

A better solution would be configuring the Javadoc task itself. Something like
```
javadoc {
  source += 'path/to/generated/code'
}
```

**Comment by DJViking** [comment]
> Not polluting project source sets with generated code (but only add as inputs into compilation tasks) is working as intended for this plugin, as it might have other implications (e.g., Javadoc, checkStyle, etc).
> 
> A better solution would be configuring the Javadoc task itself. Something like
> 
> ```
> javadoc {
>   source += 'path/to/generated/code'
> }
> ```

That did not work for me. It failed.
It complained about missing java module com.google.protobuf
```
javadoc {
    source += "${buildDir}/generated/source/proto/main/java/com/company/java-library"
}
```

Also using this approach will not give you an Source JAR.

I went with the other workaround.

This projects README should mention Javadoc and Sources, so other doesn't need to search through the issues to find a solution.

**Comment by philbrock** [comment]
Agreed it would be really helpful to document this somewhere. It might not be for everyone, but it's not a mad request. In our case we're building the generated Protobuf handling code into a jar file to be used by projects needing to read the messages. Generating a source jar for that seems like a reasonable thing to do. (Even if I'd only expect to venture into that code in the case of debugging something.)
