### ISSUE TITLE
for 390 the wrong classifier is used to fetch the protoc exe

### ISSUE THREAD

**Issue by Hendrik-H** [google/protobuf-gradle-plugin#472]
When protoc is selected via `artifact = "com.google.protobuf:protoc:3.15.1"`, so without a classifier the plugin code tries to determine the correct classifier: https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy#L106
This seems to call https://github.com/google/osdetector-gradle-plugin/blob/master/src/main/java/com/google/gradle/osdetector/OsDetector.java#L62 which finally comes by https://github.com/trustin/os-maven-plugin/blob/master/src/main/java/kr/motd/maven/os/Detector.java#L245
So for the architecture `s390x` the code uses `s390_64`, which gets in the end concatenated to `linux-s390_64`. protoc does however use a different classifier for 390, which is `linux-s390x`, as you can see here: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.15.1/

This could of course be fixed on both sides but I have never seen `s390_64`.

**Comment by voidzcy** [comment]
The os-maven-plugin and protoc diverge in the representations for some platform. You could bridge it by supplying an explicit classifier to other artifact `artifact = "com.google.protobuf:protoc:3.15.1:s390x"`. You could use osdetector plugin with `def classifier = osdetector.classifier != "s390_64" ?: "s_390x"` if you do not want to hardcode it.

**Comment by ejona86** [comment]
That seems like a bug with protobuf. There's no real point to upload the artifact to maven central without following the os-detector convention. If they didn't like the name, they should have worked with os-detector and figured out a way to determine a better name.

It looks like it was mistakenly "fixed" in https://github.com/protocolbuffers/protobuf/pull/7073 to further diverge from os-detector.

**Comment by voidzcy** [comment]
> That seems like a bug with protobuf. There's no real point to upload the artifact to maven central without following the os-detector convention. If they didn't like the name, they should have worked with os-detector and figured out a way to determine a better name.

Oh, didn't realize there is such a coupling between protobuf and os-maven-plugin. I'd file an issue to protobuf.

**Comment by ejona86** [comment]
https://github.com/protocolbuffers/protobuf/issues/8340 is now resolved. This should begin working with the next protobuf release.
