### ISSUE TITLE
Generated source folder should be registered on the SourceSet

### ISSUE THREAD

**Issue by oehme** [google/protobuf-gradle-plugin#474]
The plugin currently registers its generated sources directly on the `JavaCompile` task. This is too low level and means that other plugins/tasks will not pick up on those generated sources. For example, they will be missing from the source jar.

On top of that, it should integrate with the IDEA plugin and register that folder as a "generated" folder, so that it is correctly marked as generated in IDEA. That way, users are warned if they try to edit those files.

**Comment by voidzcy** [comment]
> This is too low level and means that other plugins/tasks will not pick up on those generated sources. For example, they will be missing from the source jar.

This is kind of working as intended. Protobuf projects work in the way that APIs are exposed through protobuf definitions, so that consuming projects can import protos from dependencies to build their own proto APIs. Generated code is not the _real source_, but protos are. On the other hand, adding generated code into source sets automatically includes them Javadoc as generated classes are always public. This is generally not wanted (e.g., for gRPC-Java) given that proto sources are exposed as APIs.

> On top of that, it should integrate with the IDEA plugin and register that folder as a "generated" folder, so that it is correctly marked as generated in IDEA. That way, users are warned if they try to edit those files.

Right, that's the better approach. There is a [TODO item](https://github.com/google/protobuf-gradle-plugin/blob/568b37351131222af1dea14c55eedfa963baaa63/src/main/groovy/com/google/protobuf/gradle/Utils.groovy#L131-L132) left in the code for migrating to `model.module.generatedSourceDirs`. Are you interested in contributing a PR?

**Comment by oehme** [comment]
Sure, I can do that.

**Comment by pan3793** [comment]
@oehme Sorry for reply on a closed issue, but I still encounter this issue with the patched version 0.8.16, see #493.

Further, I'm also using antlr in my project, which has a build-in gradle plugin, and I found some difference between antlr and protobuf plugins.

### -
For anltr, with the default configuration, such as
```
apply plugin: 'antlr'
dependencies {
    antlr "org.antlr:antlr4:$antlr_version"
}
```
put `g4` files into `src/main/antlr` and the generated code will at `build/generated-src/antlr/main`, which will auto-recognized by IDEA as `sources`.

### -
For protobuf, with the default configuration(I saw different demos in README, documents, example projects, etc. just pickup one of them), such as
```
apply plugin: "com.google.protobuf"
dependencies {
    implementation "io.grpc:grpc-netty-shaded:$grpc_version"
    // will transitive import the protobuf dependencies
    implementation "io.grpc:grpc-protobuf:$grpc_version"
    implementation "io.grpc:grpc-stub:$grpc_version"
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:$protoc_version" }
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:$grpc_version" }
    }
    generateProtoTasks {
        ofSourceSet('main')*.plugins { grpc {} }
    }
}
```
put `proto` files into `src/main/proto` and the generated code will at `build/generated/source/proto/main/grpc&java`, which will **NOT** recognized by IDEA as `sources`.

![image](https://user-images.githubusercontent.com/26535726/117142076-e10e7500-ade1-11eb-8bad-725083e7d68d.png)

Thus, I found a workaround but only works on gradle 6.8, will failed on gradle 7.0 (see #493, mentioned at the begin)
```
sourceSets.main.scala {
    srcDirs += file("${project.buildDir}/generated/source/proto/main/grpc")
    srcDirs += file("${project.buildDir}/generated/source/proto/main/java")
}
```

### -
I know little on gradle internal, but from an user perspective, as that `antlr` is an build-in gradle plugin which demonstrated how should a code generate plugin works and which folder the generated code should use in default, and it's works smoothly with IDEA. I really want a consistent experiences in code-gen gradle plugins.

**Comment by oehme** [comment]
Sorry, I can't reproduce that. I've created a minimal protobuf plugin and the source directories are set up automatically on IDEA import. No additional configuration required.

Please attach a reproducible example.

**Comment by pan3793** [comment]
@oehme thanks for the reply, it has been solved by https://github.com/google/protobuf-gradle-plugin/issues/493#issuecomment-833352993

**Comment by oehme** [comment]
Yes and I just realized that the problem is reproducible when I remove the `idea` plugin. That plugin should not be necessary, because IntelliJ already applies it upon import.

The problem is that the protobuf plugin [eagerly checks](https://github.com/google/protobuf-gradle-plugin/blob/568b37351131222af1dea14c55eedfa963baaa63/src/main/groovy/com/google/protobuf/gradle/Utils.groovy#L129) for the idea plugin instead of using a callback.
