### ISSUE TITLE
feature request: generate into a zipfile for python?

### ISSUE THREAD

**Issue by ckchow** [google/protobuf-gradle-plugin#478]
https://developers.google.com/protocol-buffers/docs/reference/python-generated#invocation

The default python plugin is able to generate code directly into a zipfile. It determines whether to do this by looking at the suffix of the output path (and if it sees a .zip, it assumes you want a zipped output). Could we add an option to the python plugin to support this behavior? I think currently the plugin makes all the output directories up to and including `outputSubdir`. So this behavior almost works without modification except at the last second it complains

`<...>.zip: Is a directory`

**Comment by voidzcy** [comment]
Looks we only need to _not create_ the destination directory before invoking `protoc`, things will be working out of the box as `protoc` [automatically creates the directory if necessary](https://developers.google.com/protocol-buffers/docs/reference/python-generated#invocation). But it requires the the parent directories to be already exist. Currently we use `File.mkdirs()` to [create the destination directory](https://github.com/google/protobuf-gradle-plugin/blob/0500ff355e4967b46d9a08b90f720007a6deb54f/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L557-L560) along with its parent directories if missing. So some minor change to that piece of code should be enough.

**Comment by cilki** [comment]
This works great the first time I run the task, but all subsequent runs fail because the plugin makes the output zip itself a source directory:
```
Caused by: org.gradle.api.InvalidUserDataException: Source directory '.../build/generated-proto/main/cpp.zip' is not a directory.
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSourceTrees(DefaultSourceDirectorySet.java:273)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirTrees(DefaultSourceDirectorySet.java:256)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirs(DefaultSourceDirectorySet.java:114)
...
```

Any way to avoid creating a new source directory or maybe just remove it before the task runs?
