### ISSUE TITLE
dllExport support as option

### ISSUE THREAD

**Issue by jferreira78** [google/protobuf-gradle-plugin#481]
Building a dll to be shared amongst other projects. I can add the option using protoc from the command line as follows:
--cpp_out=dllexport_decl=DLLX_API:$DST_DIR
However, this is does not seem to work when I add it as:
option  --cpp_out=dllexport_decl=DLLX_API
To the cpp{ } block of the generateProtoTasks block.

**Comment by ejona86** [comment]
You don't mention what happens when you try to add that option. I'd expect you to get a syntax error.

It should look more like:
```groovy
      task.builtins {
        cpp {
          option "dllexport_decl=DLLX_API"
        }
      }
```

**Comment by jferreira78** [comment]
Yep. My mistake. Thank you for the help.

John
