### ISSUE TITLE
Execution failed for task ':appdemo:generateProtos'.

### ISSUE THREAD

**Issue by w401634075** [google/protobuf-gradle-plugin#483]
error messge :   Execution failed for task ':app_tavcutdemo:generateProtos'.
> Collection contains no element matching the predicate.
```
protobuf {
    protoc {
        artifact = Deps.google.protobuf_compile
    }

    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.builtins {
                java {}
            }
        }
    }
}
```

how to solve it？ plz

**Comment by voidzcy** [comment]
I suspect the error comes from `Deps.google.protobuf_compile`, which is from your own code. Make sure it is used correctly.

Btw, what are you trying to do with `remove java` and then add it back again with `java {}`? It changes nothing. But that shouldn't give your error though.
