### ISSUE TITLE
0.8.15 plugin does not cause generated source code to compile in subprojects

### ISSUE THREAD

**Issue by kun-zhou** [google/protobuf-gradle-plugin#485]
I have a Java application project like this
```
// settings.gradle
rootProject.name = 'A'
include ('A', 'B')
```
Aside from the standard application plugin, I am also using the lombok plugin.
The proto files are in the subproject A and are referenced with the `sourceSets` closure. AFAIK, everything is configured correctly. So I run `./gradlew build` which causes the plugin to generate the Java code for the protos in `A/build/generated/source`. However, the compiled code in `A/build/classes` has no trace of the protobuf message classes. I am also unable to import the generated code.

I also checked with
```
task printDeps(dependsOn: build) {
	doLast {
		println tasks['compileJava'].source.each {
			println it
		}
	}
}
```
and no generated protobuf code is found there.

However, when I moved the proto files to the root project and copied the exact same config to root project, corresponding classes are now being generated. 

Thoughts?

**Comment by voidzcy** [comment]
A bit confused with your project structure based on your `settings.gradle`, as the root project is `A` while `A` is also a subproject.

Did you check if `A/build/generated/source` really contains generated `.java` files?

0.8.15 has been used in [gRPC-Java](https://github.com/grpc/grpc-java/blob/4896a0fee87789b0f8e844255356bef3a68010a8/settings.gradle#L8) for a while, and we've not seen such an issue there. I am suspecting you didn't locate your source protos correctly and no `.java` was generated.

**Comment by kun-zhou** [comment]
It does. Turns out the lombok gradle plugin is messing with the source for the compileJava task hence the issue. Thank you for the prompt reply.
