### ISSUE TITLE
Expose a way to query builtins/plugins at Gradle configuration time

### ISSUE THREAD

**Issue by JakePi3** [google/protobuf-gradle-plugin#49]
A bit of background first... I am trying to generate both Java and C++ bindings and then publish the Java classes as well as the C++ source files to a Maven repository.

I currently have: 

```gradle
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0-beta-1'
    }
    generateProtoTasks {
        all().each { t ->
            t.builtins {
                cpp {}
            }
        }
    }
}

task zipCpp(type: Zip, dependsOn: 'generateProto') {
    from "${buildDir}/generated/source/proto/main/cpp"
}
assemble.dependsOn zipCpp
```

It would be nice if the zip task could discover the outputs of a builtin with a given name.. Something like:

```gradle
task zipCpp(type: Zip, dependsOn: 'generateProto') {
    from tasks.getByName('generateProto') { t ->
        t.builtins.findAll { it.name == 'cpp' }.each { b->
            t.outputDir(b)
        }
    }
}
```

Or even better, move some of that complexity into the actual plugin.. At the moment the task is not available at configuration time and moving the creation of the zip task to inside the generateProtoTasks closure is even more complicated.  Suggestions/workarounds welcome.

**Comment by zhangkun83** [comment]
As documented, we suggest not assuming the names of the generate proto tasks, thus all configurations that are related to these tasks should be done in the `generateProtoTasks` closure.

This would get what you want:
```gradle
task zipCpp(type: Zip) {
}

protobuf {
  ...
  generateProtoTasks {
    ...
    zipCpp {
      dependsOn ofSourceSet('main')
      from ofSourceSet('main').collectMany { t ->
        t.builtins.findAll { it.name == 'java' }.collect { b->
          t.getOutputDir(b)
        }
      }
    }
  }
```

It's not working at current version because `t.builtins` is not a readable property. If the general solution sounds good to you, I can make the property readable.

**Comment by JakePi3** [comment]
Yes, this is great.  Maybe make t.plugins also readable for same reason...

Thanks.

**Comment by zhangkun83** [comment]
0.7.1 is now released. `builtins` and `plugins` are now readable.
