### ISSUE TITLE
Missing output directives error when executing Android build.gradle.kts 

### ISSUE THREAD

**Issue by pueffl** [google/protobuf-gradle-plugin#491]
I' trying to setup protobuf for Android, but I get "> protoc: stdout: . stderr: Missing output directives." I think that is just a configuration issue, but the message is not very helpful and I'm stuck at the moment. The gradle code looks as follows:

```
import com.eight.build.*
import com.google.protobuf.gradle.*

plugins {
    `android-base-lib`
}

apply(plugin = "com.google.protobuf")

dependencies {
...
    implementation("com.google.protobuf:protobuf-lite:3.0.0")
...
}

protobuf {
    generatedFilesBaseDir = "$projectDir/src/generated"
    protoc {
        artifact = "com.google.protobuf:protoc:3.15.8"
    }
    plugins {
        id("javalite") {
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}

```

**Comment by voidzcy** [comment]
If you are using protobuf version before 3.8, protoc-gen-javalite is provided as a protoc plugin. So you need to configure _the "javalite" plugin_ for GenerateProtoTask:

```gradle
protobuf {
    ...

    protoc {
        artifact = "com.google.protobuf:protoc:3.0.0"
    }
    plugins {
        id("javalite") {
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            task.builtins {
               remove java  // you probably do not need full java
            }
            it.plugins {
                id("javalite") { }
            }
        }
    }
}
```

If you are using protobuf 3.8+ (as 3.15.8 is used in your buildscript), the lite runtime is built into protoc's Java codegen. So you need to configure _the "java" builtin_ for GenerateProtoTask:

```gradle
protobuf {
    ...

    protoc {
        artifact = "com.google.protobuf:protoc:3.15.8"
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.builtins {
                id("java") {
                  option("lite")
                }
            }
        }
    }
}
```

You can see details in [Default outputs](https://github.com/google/protobuf-gradle-plugin#default-outputs) section of README for Android projects.

**Comment by pueffl** [comment]
You where right that there was a mixup with some artefacts, but unfortunately, correcting that doesn't change a thing:

apply(plugin = "com.google.protobuf")

dependencies {
    implementation("com.google.protobuf:protobuf-javalite:3.15.8")
}

protobuf {

    protoc {
        artifact = "com.google.protobuf:protoc:3.15.8"
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}

Same error:
Execution failed for task ':preferences_app:generateDebugProto'.
> protoc: stdout: . stderr: Missing output directives.

**Comment by voidzcy** [comment]
I forgot to notice this is for Android...

In Android build the minimum compilation unit is _variant_ (compared to _sourceSet_ in normal Java projects), so proto generation tasks are associated with each _variant_.

```gradle
protobuf {
    ...

    generateProtoTasks {
        // You probably just want to configure for all variants. Although we provide 
        // `ofFlavor()`/`ofBuildType()`/`ofVariant()`/`ofNonTest()`/etc API, in most
        // cases users do not have customized per buildType/flavor configurations (it
        // tends to be very use-case specific).
        all().forEach {
            it.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}
```
