### ISSUE TITLE
Support for Apple M1 processors

### ISSUE THREAD

**Issue by yuzawa-san** [google/protobuf-gradle-plugin#492]
Per the README, this plugin uses the osdetector.classfier which is normally correct:
```
The syntax for artifact follows Artifact Classifiers where the default classifier is project.osdetector.classifier (ie "${project.osdetector.os}-${project.osdetector.arch}") and the default extension is "exe".
```

On M1 macs, the classifier is `osx-aarch_64` which is correct, but according to some other threads it does not appear that this classifier will be published in the near future or later: 
* https://github.com/protocolbuffers/protobuf/issues/8062
* https://github.com/grpc/grpc-java/issues/7690

The latter thread has lots of solutions that mostly involve manually overriding the classifier. I propose adding the override logic into this plugin, so folks do not need to track down that latter issue and choose their own patchy solution.

The next version's release candidate does not have the classifier yet.

I am willing to open a PR which modifies [this logic](https://github.com/google/protobuf-gradle-plugin/blob/1ff7893d212511a8284b4d65d84e1a4ba02a0d7c/src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy#L106) to overwrite `osx-aarch_64` to `osx-x86_64` (which is compatible).

If/when the `osx-aarch_64` classifier is published, this logic can be removed.

**Comment by ejona86** [comment]
I don't think changing the logic in this plugin helps much, as that logic then has to be protobuf-version specific, forever. I was thinking about this earlier today. I wonder if the least-bad thing to do is to have protobuf and grpc publish the x86_64 binary _also_ with the aarch_64 name.

**Comment by yuzawa-san** [comment]
@ejona86 I took a stab at implementing your idea, since I do like your idea a lot more and the maintainers of the protoc can swap out to a real M1 version whenever they are ready.

**Comment by jjones-figure** [comment]
I don't like this idea. I would rather explicitly specify that I am using a non-native artifact as opposed to having it be hidden inside the plugin. Maybe all the issues will help increase priority for true aarch64 support?

**Comment by neakor** [comment]
Any updates on this issue?

**Comment by ejona86** [comment]
This is not an issue with the plugin, so closing. Protobuf is already (at least) copying the x86_64 binary to the proper name for m1. https://github.com/grpc/grpc-java/issues/7690 tracks support in grpc-java.
