### ISSUE TITLE
custom step before extractIncludeProto task

### ISSUE THREAD

**Issue by gerald732** [google/protobuf-gradle-plugin#494]
Hi,

First of all, thanks for the wonderful plugin. I wanted to check if there's a way to specify a dependsOn properties on extractIncludeProto task. This is the first task listed when I ran `./gradlew build --dry-run`. 

In `build.gradle`, I tried doing this:

```
extractIncludeProto.dependsOn myCustomTask
```
However, it's throwing:

`Could not get unknown property 'extractIncludeProto' for root project [...]`

The custom task is basically retrieving a .zip protobuf source and extracting them to a specific directory. This needs to be done before the protos are generated. I'm aware that there's only support for `.jar` archive now. I wonder if there are plans to include `.zip` as well in the near future.

Thanks in advance.

**Comment by voidzcy** [comment]
> `Could not get unknown property 'extractIncludeProto' for root project [...]`

You would need to configure your the ankles in `afterEvaluate {}` block.

> I'm aware that there's only support for `.jar` archive now. I wonder if there are plans to include `.zip` as well in the near future.

You should be able to specify `.zip` files as dependencies with `fileTree("path/to/file")`, which is natively supported by Gradle.

**Comment by gerald732** [comment]
Thanks @voidzcy. I think there's support for `.zip` as well. I managed to do that with:

```
dependencies {
    protobuf 'package:version:@zip'
}
```
