### ISSUE TITLE
Could not find any convention object of type ProtobufConvention

### ISSUE THREAD

**Issue by bellini-ea** [google/protobuf-gradle-plugin#496]
I have a new basic setup I'm working with for some prototyping using Gradle 6.8.3, Kotlin DSL, plugin 0.8.16.  
I have protobuf working in other projects however on this new project, I'm seeing the following error using cut and paste from my other projects.
`Could not find any convention object of type ProtobufConvention`

I'm unclear what I'm missing that is causing this so any thoughts or advice is appreciated.

**Comment by voidzcy** [comment]
We are not able to figure out what's happening just based on this error message. Please describe your build and post your buildscript.

**Comment by bellini-ea** [comment]
Thanks.  I started with a gradle init and so ended up with:

project
  -- build.gradle.kts
  -- buildSrc/build.gradle.kts
  -- buildSrc/src/main/kotlin/(convention files here)
  -- dto-common/dto-common.build.gradle.kts  <-- This has the protobuf reference in it (pasted below)

The buildSrc convention files are straight out of gradle init and just include the kotlin dsl, java-library, etc so not pasting them here for now.

### Project root build.gradle.kts
```
import com.google.protobuf.gradle.*

plugins {
    `java-library`
    id("org.jetbrains.kotlin.jvm")
    id("myproject.kotlin-common-conventions")
    id("com.google.protobuf") version "0.8.16" apply false
}

subprojects {
    apply(plugin="com.google.protobuf")

    repositories {
        mavenCentral()
    }

    tasks {
        protobuf {
            generatedFilesBaseDir = "${projectDir}/src/generated"
            clean { delete(generatedFilesBaseDir) }

            protoc {
                // The artifact spec for the Protobuf Compiler
                artifact = "com.google.protobuf:protoc:3.15.1"
            }

            plugins {
                id("grpc-java") {
                    artifact = "io.grpc:protoc-gen-grpc-java:1.35.0"
                }
                id("grpc-kotlin") {
                    artifact = "io.grpc:protoc-gen-grpc-kotlin:0.1.5"
                }
            }

            generateProtoTasks {
                all().forEach {
                    // Always delete existing generated code before generating again to avoid conflict
                    it.doFirst { delete(generatedFilesBaseDir) }
                    it.plugins {
                        id("grpc-java") {}
                        id("grpc-kotlin") {}
                    }
                }
            }
        }
    }
}
```
### dto-common.build.gradle.kts is as follows.
```
import com.google.protobuf.gradle.protobuf

plugins {
    id("myproject.kotlin-library-conventions")
}

dependencies {
    protobuf("com.ea.myproject:myproject-protos:0.20.0-SNAPSHOT:proto@zip")
    protobuf("com.google.api.grpc:proto-google-common-protos:2.1.0")

    implementation(platform("io.grpc:grpc-bom:1.35.0"))
    implementation("io.grpc:grpc-all")
    implementation("io.grpc:grpc-kotlin-stub:0.1.5")
    implementation("com.google.protobuf:protobuf-java:3.15.1")
}
```

**Comment by bellini-ea** [comment]
I moved it out of the tasks{} but no luck (same ProtobufConvention error).  I tried putting it into subprojects{} as well but no luck.

If I put all that code into dto-common.build.gradle.kts... its works fine but moving it to the root does not work.  I'm interested in having it in the root so I don't need to duplicate that code into many of the sub projects.

**Comment by voidzcy** [comment]
> I moved it out of the tasks{} but no luck (same ProtobufConvention error). I tried putting it into subprojects{} as well but no luck.

I was intended to mean putting the `protobuf{}` closure right in `subprojects{}`. The `apply(plugin="com.google.protobuf")` way of applying the plugin won't give you the Kotlin [type-safe accessors](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api).

You may want to try:

```gradle
subprojects {
  configure<ProtobufConvention> {
    generatedFilesBaseDir = "${projectDir}/src/generated"
    // all the others in protobuf{} closure
    ...
  }
}
```

**Comment by bellini-ea** [comment]
None of that worked.  I managed to get this going but moving the protobuf items to a convention and working through it like that.  I believe this is a better approach to my original plan which lead to this comment.  Thanks for the inputl.

**Comment by voidzcy** [comment]
How we manages this in gRPC-Java is that, in the [root project's buildscript](https://github.com/grpc/grpc-java/blob/413deb7f0ce3e7f040d9addb4ca9cc06d6a76102/build.gradle#L65-L141) we put the code for configuring the ProtobufConvention in a function, which is an extension/convention available for each subproject. Then each subproject that needs proto generation just [calls the function](https://github.com/grpc/grpc-java/blob/413deb7f0ce3e7f040d9addb4ca9cc06d6a76102/services/build.gradle#L41) to apply the configuration.

I guess that should be similar to what you want.

**Comment by voidzcy** [comment]
Btw, I really think the problem in your original approach is that you cannot apply the protobuf plugin to the subproject before Java/Android/Kotlin plugin is applied in the subproject. But I'd expect you should get a different error message indicating that. Other than that, issues can be related to the usage of Kotlin DSL, but I don't have much expertise dealing with Kotlin DSL.
