### ISSUE TITLE
protoc binaries are not resolved using Nexus private repo + inconsistent debug messages

### ISSUE THREAD

**Issue by pranasblk** [google/protobuf-gradle-plugin#50]
Environment:
 * The issue reproduced on v0.7.1
 
* Gradle fragment specify
```
protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:2.6.1'
  }
}
```

But getting errors:
```
A problem occurred configuring root project 'my-project-name'
Could not find protoc-windows-x86_64.exe (com.google.protobuf:protoc:2.6.1)
Searched in the following locations:
http://my-private-nexus-proxy:3000/artifacts/content/groups/PR_Group/com/google/protobuf/protoc/2.6.1/protoc-2.6.1-windows-x86_64.exe
```

The strange thing the path 'http://my-private-nexus-proxy:3000/artifacts/content/groups/PR_Group/com/google/protobuf/protoc/2.6.1/protoc-2.6.1-windows-x86_64.exe' is CORRECT.

Notes:
* The reference to 'protoc-windows-x86_64.exe' is not correct and should be 'protoc-2.6.1-windows-x86_64.exe'
* The path to my private Nexus repository is valid and it is not clear why it can not resolve existing artifact

**Comment by zhangkun83** [comment]
> ```
Could not find protoc-windows-x86_64.exe (com.google.protobuf:protoc:2.6.1)
```

This message is generated by Gradle, not the plugin. Strangely, I got a different message:
```
A problem occurred configuring project ':testProject'.
> Could not resolve all dependencies for configuration ':testProject:protobufToolsLocator_protoc'.
   > Could not find com.google.protobuf:protoc:2.6.3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/protobuf/protoc/2.6.3/protoc-2.6.3.pom
         https://repo1.maven.org/maven2/com/google/protobuf/protoc/2.6.3/protoc-2.6.3-linux-x86_64.exe
         https://jcenter.bintray.com/com/google/protobuf/protoc/2.6.3/protoc-2.6.3.pom
         https://jcenter.bintray.com/com/google/protobuf/protoc/2.6.3/protoc-2.6.3-linux-x86_64.exe
     Required by:
         protobuf-gradle-plugin:testProject:unspecified
```
I tested with Gradle 2.3 and 2.7. What's the Gradle version you are running?

**Comment by pranasblk** [comment]
Gradle 2.8

**Comment by zhangkun83** [comment]
Tried with Gradle 2.8, I still got the error I saw with 2.3 and 2.7. Are you able to resolve the artifact from Maven Central?

**Comment by pranasblk** [comment]
I tried with Gradle 2.8:
Mac OS: Maven Central & Private proxy of Maven Central - Works
Linux: Private deployment of protoc 2.6.1 in Nexus - FAILS due to dynamic libarary libc.so has different version (but able to retrieve binary artifact i.e. not directly related to the current version)
Windows: Private deployment of protoc 2.6.1 in Nexus - FAILS to retrieve binary artifact.

**Comment by testark** [comment]
It's happening with me too with Gradle 2.13 and version 0.7.7 of the plugin under Linux.

**Comment by testark** [comment]
In case anyone comes across this, I solved it by unchecking the `Validate that all content uploaded to this repository is of a MIME type appropriate for the repository format` checkbox under `Strict Content Type Validation` in my repository's configuration. After doing that, a `./gradlew build --refresh-dependencies` did the trick.

**Comment by zhangkun83** [comment]
@testark Thank you for sharing the solution.

**Comment by sluczak** [comment]
Hi,
It looks like I have encountered similar problem...

Gradle fetching of nexus repo states that the file (protoc-3.6.0-linux-x86_64.exe) is 404 on Nexus... But only on linux PC/server!) (both, via gradle, curl or Chrome browser)
I can freely download it with Windows (for example via Chrome browser).
I'm stumbled...

I've already tried the trick with Strict Content Type with no good

**Comment by imranrazakhan** [comment]
> In case anyone comes across this, I solved it by unchecking the `Validate that all content uploaded to this repository is of a MIME type appropriate for the repository format` checkbox under `Strict Content Type Validation` in my repository's configuration. After doing that, a `./gradlew build --refresh-dependencies` did the trick.

it didn't work for me so i have to do following

`mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.13.0 -Dclassifier=osx-x86_64 -Dpackaging=exe -Dfile=protoc-3.13.0-osx-x86_64.exe`
