### ISSUE TITLE
Collision when importing proto-from-dependency and protobuf-javalite

### ISSUE THREAD

**Issue by hb0** [google/protobuf-gradle-plugin#503]
### Setup

**Repository `protos`**

- contains `my.proto` file.
- pushlishes a `JAR`, containing my `proto` file, the `google` `proto` files and the compiled `java` classes.
- the compiled `java` classes are used by another project which is not further explained.

```
plugins {
  id 'java-library'
  id 'com.google.protobuf' version '0.8.16'
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:3.17.0"
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        java {}
      }
    }
  }
}
```

**Repository `android-lib`**

- wants to import the `my.proto` file from the JAR (see above)
- wants to compile the `java-lite` classes, and NOT use the pre-compiles `java` classes from the JAR

```
plugins {
    id 'com.android.library'
    id 'com.google.protobuf' version '0.8.16'
}
dependencies {
    // get the `my.proto` file from the JAR and compile the `java-lite`classes
    // BUT: this also includes the `google/*.proto` files which collide with ...
    protobuf "com.my:protos:1.0.0"
    // this also includes `google/*.proto` files and collides with the google proto files above
    implementation "com.google.protobuf:protobuf-javalite:3.17.0"
}
```

### Error

```
Execution failed for task ':synchronization:generateFullDebugProto'.
> protoc: stdout: . stderr: /home/user/workspace/android-backend/synchronization/build/extracted-protos/main/google/protobuf/any.proto: Input is shadowed in the --proto_path by "/home/user/workspace/android-backend/synchronization/build/extracted-include-protos/fullDebug/google/protobuf/any.proto".  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.
```

### Question

Is it possible to only import my own `proto` file from the generated `JAR` of my library `protos`?
To clearify: the `protos` repo compiles and publishes the `java` proto classes which the `android-lib` project does not want to use. It only wants to get my `proto` file and compile `lava-lite` classes instead.

### Workaround for `android-lib`

Instead of using **proto-from-dependency** I can also download, extract and include my `proto` file manually, which works perfectly. I just thought maybe it's possible to use **proto-from-dependency** for that.

```
plugins {
    id 'com.android.library'
    id 'com.google.protobuf' version '0.8.16'
    id "de.undercouch.download" version "4.1.1"
}
android {
    sourceSets {
        main {
            proto {
                srcDir 'build/protos-0.0.2/src/main/proto'
            }
        }
        test {
            proto {
                srcDir 'build/protos-0.0.2/src/main/proto'
            }
        }
    }
}
dependencies {
    //NOT IMPORTING protobuf "com.my:protos:0.0.2"
    implementation "com.google.protobuf:protobuf-javalite:$rootProject.ext.protobufVersion"
}
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}
// Download the `measurement.proto` file to generate the java-lite classes
task downloadProto(type: Download) {
    src 'https://github.com/my/protos/archive/refs/tags/0.0.2.zip'
    dest new File(buildDir, 'protos-0.0.2.zip')
}
task downloadAndUnzipProto(dependsOn: downloadProto, type: Copy) {
    from zipTree(downloadProto.dest)
    into buildDir
}
assemble.dependsOn downloadAndUnzipProto
```

**Comment by voidzcy** [comment]
Looks "com.my:protos:1.0.0" shouldn't have google protos packaged in it but just have protobuf-java/protobuf-javalite artifact as its compile/implementation dependency. That's unfortunate. 

There isn't an easy way to filter out google protos, as this basically requires modifying the content of `com.my:protos:1.0.0.jar` on the fly during dependency resolution. I can imagine something crazy that might make this happen (presumably something like `configurations.findByName("protobuf").incoming.afterResolve ...` that turns the JAR to a FileTree and filters out google protos), but I'd suspect that solution being much more complicated and errorprone than your current workaround.

So, my short answer is no, there isn't an easy way to do it. 😢

**Comment by hb0** [comment]
Thanks, I just thought I am missing something. I can currently live well with my workaround.
