### ISSUE TITLE
kotlin_out option for generating Kotlin DSL files

### ISSUE THREAD

**Issue by kolmant** [google/protobuf-gradle-plugin#504]
Hi,

I'm trying to find an option for setting the "kotlin_out" parameter for `protoc` since now it supports generating Kotlin DSL files. There is an option and I'm missing it? If there is, please let me know.

Thanks,

**Comment by koofree** [comment]
I think it doesn't support yet on this gradle plugin.

**Comment by hojongs** [comment]
We can add plugin named `kotlin`.

after that when I ran `generateProto` gradle task, I got generated protobuf-kotlin.

```
// build.gradle.kts
protobuf {
    plugins {
        id("kotlin")
    }
    generatedProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("kotlin")
            }
        }
    }
}

dependencies {
    implementation("com.google.protobuf:protobuf-kotlin:3.17.1")
}
```

**Comment by mcpiroman** [comment]
@hojongs 
There should be `generateProtoTasks`, not `generatedProtoTasks`

**Comment by hojongs** [comment]
I fixed it, thanks.
