### ISSUE TITLE
version 3.0.0 generate bad code from the attached 

### ISSUE THREAD

**Issue by mpatalberta** [google/protobuf-gradle-plugin#507]
syntax = "proto3";
option java_outer_classname = "InferenceOuterClass";
package endpoints.zebra.inference;

service Inference {
  rpc SubmitImage(stream SubmitImageRequest) returns (SubmitImageResponse) {}
}

message MessageDescriptor{
  int64 device_uuid = 1;
  repeated string image_meta = 3;
}

message SubmitImageRequest {
  oneof details {
    MessageDescriptor messageDescriptor = 1;
    bytes chunk = 2;
  }
}

message SubmitImageResponse {
  bool accepted = 1;
  string sequence_id = 2;
}

**Comment by mpatalberta** [comment]
I need a plugin for gradle

**Comment by voidzcy** [comment]
What is your question?
