### ISSUE TITLE
how to package proto files into aar

### ISSUE THREAD

**Issue by dengqu** [google/protobuf-gradle-plugin#510]
how to package proto files into aar,I build the aar not contains proto files

**Comment by voidzcy** [comment]
Are you using protobuf-gradle-plugin 0.8.14 or later? Packaging and extracting protos into/from AAR is only supported for 0.8.14+. You should be able to see the protos being packed _inside the classes.jar inside the AAR file_.

**Comment by dengqu** [comment]
my protobuf-gradle-plugin 0.8.8 ,my build.gradle configre like this:
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.0.0-pre2'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            javalite { }
        }
        ofNonTest()*.plugins {
            grpc {
                // Options added to --grpc_out
                option 'lite'
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.5.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    compile 'com.google.protobuf:protobuf-lite:3.0.0'
    compile 'io.grpc:grpc-core:1.0.0-pre2'
    compile 'io.grpc:grpc-stub:1.0.0-pre2'
    compile 'io.grpc:grpc-okhttp:1.0.0-pre2'
    compile('io.grpc:grpc-protobuf-lite:1.0.0-pre2') {
        // Otherwise Android compile will complain "Multiple dex files define ..."
        exclude module: "protobuf-lite"
    }

}


but I can't find .proto files in aar or in classess.jar

**Comment by dengqu** [comment]
I find I use com.google.protobuf:protobuf-gradle-plugin:0.8.15  has find protos in classess.jar

**Comment by voidzcy** [comment]
Yes, you need to upgrade to use 0.8.14+.
