### ISSUE TITLE
Incorrect warning

### ISSUE THREAD

**Issue by pvegh** [google/protobuf-gradle-plugin#516]
I'm seeing this in the console:
> Task :modulex:extractIncludeDebugUnitTestProto
proto file '/path/to/module/src/main/proto/foo.proto' directly specified in configuration. It's likely you specified files('path/to/foo.proto') or fileTree('path/to/directory') in protobuf or compile configuration. This makes you vulnerable to https://github.com/google/protobuf-gradle-plugin/issues/248. Please use files('path/to/directory') instead.

But I haven't specified neither a file nor a directory anywhere.

**Comment by ejona86** [comment]
See #357
