### ISSUE TITLE
How to extract proto files by given path?

### ISSUE THREAD

**Issue by ZhangX-Byte** [google/protobuf-gradle-plugin#517]
1. what i want to do?
    I got a jar that contains two directories.
    <img width="284" alt="截屏2021-08-06 下午4 05 12" src="https://user-images.githubusercontent.com/6357361/128477987-0ab9a079-71d3-4b9e-952c-99e425556d86.png">

   I reference this jar to my project like this.
   ```
    protobuf 'com.protos:proto-center:1.0'
   ```

2. `extractProto` is work good which extract all proto files and generate java classes.But what i want to do is specify a proto directory path to generate java classes. Specifically,i want the directory `proto/hlw` that contains `helloworld.proto` to generate classes,not the`simpleservice.proto`.How can i do that?

**Comment by ejona86** [comment]
I don't think that option is available. Instead, you'd need to extract the jar yourself and then point the plugin at the extracted directory.

**Comment by ZhangX-Byte** [comment]
But if we put proto files together that each team could maintain their files just package them and publish it to maven. As such,my teams don’t need add proto files to each project.

**Comment by meiskalt7** [comment]
It will be a great improvement to specify which proto files I need to compile from my proto files lib
Is it real to add such feature?
