### ISSUE TITLE
NamedDomainObjectContainer<T>.invoke(kotlin.Function1) has been deprecated

### ISSUE THREAD

**Issue by oehme** [google/protobuf-gradle-plugin#526]
Use ` NamedDomainObjectContainer<T>.invoke(Action)` instead. Otherwise the plugin triggers deprecation warnings on Gradle 7 and will fail on Gradle 8. The problematic call is [here](https://github.com/google/protobuf-gradle-plugin/blob/1ff7893d212511a8284b4d65d84e1a4ba02a0d7c/src/main/groovy/com/google/protobuf/gradle/KtDslCompatibilityUtils.java#L28).

**Comment by voidzcy** [comment]
This should have been resolved by #531.
