### ISSUE TITLE
Warning about configuration when everything appears to be set up correctly

### ISSUE THREAD

**Issue by liutikas** [google/protobuf-gradle-plugin#539]
Protobuf gradle plugin seems to warn incorrectly when running using seemingly valid build.gradle configuration
 
## Steps:

0. Check out https://github.com/liutikas/protobuf-gradle-plugin-warning-repro
1. `./gradlew extractIncludeDebugAndroidTestProto`

## Expected

No warnings since app/build.gradle is only setting
```groovy
android {
    sourceSets {
        main {
            proto.srcDir 'proto'
        }
    }
}
```

## Actual

```text
> Task :app:extractIncludeDebugAndroidTestProto
proto file '/ssd/ssd1/temp/ProtoProject/app/proto/icing/proto/status.proto' directly specified in configuration. It's likely you specified files('path/to/foo.proto') or fileTree('path/to/directory') in protobuf or compile configuration. This makes you vulnerable to https://github.com/google/protobuf-gradle-plugin/issues/248. Please use files('path/to/directory') instead.
```

This seems unexpected

**Comment by voidzcy** [comment]
Yeah, this is actually a bug. See https://github.com/google/protobuf-gradle-plugin/issues/357#issuecomment-713391370 for details.
