### ISSUE TITLE
Best way to create proto only packages?

### ISSUE THREAD

**Issue by jhspaybar** [google/protobuf-gradle-plugin#54]
In an effort to eliminate copy/pasting *.proto files into many projects across languages, I'd like to have a gradle project with only the proto files contained and published in the released artifact.  What is my best method for doing so?  I'd like to use a standard dependency like `compile "com.mypackage:my-service-definition:1.0"` and have it be available and used somehow within the project.  I saw ways to reference protobuf file(...) and others, but it wasn't clear how to modify this for what I'm after.  Thanks for any help you can provide!

**Comment by zhangkun83** [comment]
Once you have published the artifact that contains the proto files, you may reference it as a `protobuf` dependency, e.g., 
```gradle
dependencies {
  protobuf 'com.mypackage:my-service-definition:1.0'
}
```

**Comment by jhspaybar** [comment]
In the package that contains only protos I'd like to compile them, mostly to validate the syntax, but not distribute the compiled classes.  Your recommendation to use the protobuf declaration works, but the precompiled class files are still there from the plugin compiling them in the sub-project.  I did a jar{excludes} to keep them out, but maybe there's a better approach?

**Comment by zhangkun83** [comment]
If I read you correctly, you are asking about the project that publishes the protos, not that consumes.
The protobuf plugin facilitates only the consumption of the protos. For distribution, you would have to jar them by yourself.

**Comment by jhspaybar** [comment]
Thanks for your help!  That's kind of what it looked like but I wanted to make sure.
