### ISSUE TITLE
migrate from protoc to gradle plugin problems

### ISSUE THREAD

**Issue by BogdanCorpade** [google/protobuf-gradle-plugin#549]
I'm trying to use the gradle plugin instead of protoc compiler and I want to reproduce this command with it:
```
protoc-plugin/com_google_protobuf/protoc \
  --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
  --js_out=import_style=commonjs,binary:./js/gen \
  --ts_out=service=true:./js/gen \
  -I ./protos-module/src/main \
  -I ./protos-module/src/main/protos \
  protos-module/src/main/protos/transaction_sync.proto
```

the configuration of the gradle plugin is like this:
```
generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
        all().each { task ->
            task.builtins {
                js {
                    option "import_style=commonjs"
                    option "binary"
                }
            }
        }
    }

```
Can anyone help?(any documentation over this would be really helpful, I can't find anything related to this plugin)

**Comment by ejona86** [comment]
What problem are you having? It doesn't sound like you have an error. What specific things are you not understanding how to do? Have you read the README?

`ts` is missing from your configuration, but you already know how to do options. You'd need something like:
```
protobuf {
  plugins {
    ts {
      path = '../node_modules/.bin/protoc-gen-ts'
      option 'service=true'
    }
  }
```

`-I src/main` looks suspect; I don't know why you'd ever need that if you have `-I src/main/proto` (which is done by default by this plugin). You can [configure that with source sets](https://github.com/google/protobuf-gradle-plugin/#customizing-source-directories), but I don't think you should.

**Comment by BogdanCorpade** [comment]
it fails:
 problem occurred evaluating project ':protos-module'.
> Could not find method option() for arguments [service=true] on object of type com.google.protobuf.gradle.ExecutableLocator.

` plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
        ts {
            path = '../node_modules/.bin/protoc-gen-ts'
            option 'service=true'
        }
    }

    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
        all().each { task ->
            task.builtins {
                js {
                    option "import_style=commonjs"
                    option "binary"
                }
                ts {}
            }
        }
    }`

**Comment by ejona86** [comment]
In moving to the plugin, the base directory is different. The results of the plugin are roughly what I'd expect (even though I have no JS/TS knowledge). It is very strange to see a `..` in an import path, and for it to use a "proto" directory. I don't really know the JS/TS code generator enough to help more.

**Comment by BogdanCorpade** [comment]
the main problem has been solved
