### ISSUE TITLE
Custom source sets are not supported

### ISSUE THREAD

**Issue by pazderak** [google/protobuf-gradle-plugin#55]
Hi,
I have defined a custom source set for Java application:
`sourceSets {
  generated
}
`, but this source set is untouched when compilation is runned:
> 06:44:08.182 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':generateProto'
06:44:08.183 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/admin/workspace/travel-vendor-service-sncf/src/main/proto', not found
06:44:08.183 [INFO] [org.gradle.api.internal.file.collections.DirectoryFileTree] file or directory '/home/admin/workspace/travel-vendor-service-sncf/build/extracted-protos/main', not found
06:44:08.183 [INFO] [org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter] Skipping task ':generateProto' as it has no source files.
06:44:08.183 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':generateProto'

Is it possible to enhance plugin to support custom source sets?

**Comment by zhangkun83** [comment]
Have you tried adding brackets:
```gradle
sourcesSets { generated {} }
```

**Comment by pazderak** [comment]
Yes, and I event tried also
 `sourceSets {
   generated {srcPath "src/generated/proto"}
}`

**Comment by zhangkun83** [comment]
I think I know what's happening. Gradle by default only builds the `main` and the `test` source sets. You will need to explicitly run the `compileGenerated` task, or make either `main` or `test` depend on the output of `generated`, to get Gradle to compile the `generated` source set. `sourceSets { generated }` is sufficient.
