### ISSUE TITLE
extractIncludeProto plugin takes several minutes in gradle build, is there any solution around for it? 

### ISSUE THREAD

**Issue by nupurrajal-swiggy** [google/protobuf-gradle-plugin#551]

**Comment by rougsig** [comment]
Could you provide more details? A test project would be best.

**Comment by ejona86** [comment]
Several minutes is extreme, but if there are simply lots of dependencies it could take a while. Did the project that had this problem have lots of transitive dependencies?

**Comment by rapasoft** [comment]
I can second that this is an issue for me as well. Some details:

Project is micronaut + kotlin + gradle, there are just few protobuf schemas to generate. Gradle task configuration is as follows:
```
val protocVersion = "3.20.1"

protobuf {
    protoc { // The artifact spec for the Protobuf Compiler
        artifact = "com.google.protobuf:protoc:$protocVersion"
    }

    generateProtoTasks {
        all().forEach { task ->
            task.builtins {
                id("kotlin") {}
            }
        }
    }
}
```
Running single (simple) unit test in this case causes this delay:
```
12:43:56: Executing ':testClasses'...

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :kaptGenerateStubsKotlin UP-TO-DATE
> Task :kaptKotlin UP-TO-DATE
> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :extractIncludeTestProto UP-TO-DATE
> Task :extractTestProto UP-TO-DATE
> Task :generateTestProto NO-SOURCE
> Task :kaptGenerateStubsTestKotlin UP-TO-DATE
> Task :kaptTestKotlin UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE

BUILD SUCCESSFUL in 27s
14 actionable tasks: 14 up-to-date
12:44:23: Execution finished ':testClasses'.
```
where `:extractIncludeProto` takes 24sec, 417ms to execute.

**Comment by rougsig** [comment]
@rapasoft Could you please provide gradle scan? Log looks interesting in reason of all tasks UP-TO-DATE. 27 seconds for it is too long, if project small enought.

**Comment by rapasoft** [comment]
@rougsig Here's the link: https://scans.gradle.com/s/hfuvxduih6irk

**Comment by rougsig** [comment]
@rapasoft 
In scan i see a lot of time spent of download dependencies.
 `Time spent on downloadsSum of wall clock times spent downloading files	22.365s` ([see](https://scans.gradle.com/s/hfuvxduih6irk/performance/network-activity#download-time))

The Protobuf plugin has to resolve a lot of dependencies in order to find the included proto files. They can be inside any `implementation`, `compileOnly` configuration. But in this example it's not a problem, we need to resolve dependencies not only for protobuf plugin, we need to resolve for java/kotlin compilation.

The main problem for you is download speed.

**Comment by rapasoft** [comment]
Ah, I see! Thanks for the info so-far :)

**Comment by ejona86** [comment]
We didn't hear back from OP and the downloading is normal during the build. I have confirmed extractIncludeProtos is just scanning the compileClasspath, which should be the smallest set possible to scan and would be the same set used for java compilation. Seems there's nothing to do here.
