### ISSUE TITLE
Issue when upgrading gradle to 7+ with implicit dependencies resources <-> proto

### ISSUE THREAD

**Issue by waldirpires** [google/protobuf-gradle-plugin#553]
When I compile my project, I am getting new warnings after migrating to gradle version 7.3.3.

The warning:

`> Task :application:processTestResources
Execution optimizations have been disabled for task ':application:processTestResources' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/application/build/extracted-protos/test'. Reason: Task ':application:processTestResources' uses this output of task ':application:extractTestProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.`

I have tried defining these implicit dependencies explicitly in my build.gradle, but gradle does not seem to recognize any of these tasks (processResources, processTestResources, extractTestProto, extractProto) inside my build.gradle file. 

How could I define that these tasks (processResources, processTestResources) explicitly depend on these tasks (extractProto, extractTestProto)?

**Comment by ejona86** [comment]
This should have been resolved by #594.
