### ISSUE TITLE
`GenerateProtoTask` does not consider path-based `protoc` or plugins as task inputs

### ISSUE THREAD

**Issue by clayburn** [google/protobuf-gradle-plugin#557]
If you set `protoc` by `path` rather than by `artifact`, the `GenerateProtoTask` does not consider that to be a task input. For example this buildscript:

```
val protocPath: String? = System.getenv("PROTOC_PATH")
protobuf {
    protoc {
        path = protocPath
    }
}
```

results in the following:

```
> PROTOC_PATH=proto-3.19.3/bin/protoc ./gradlew generateProto
> Task :proj:generateProto

> PROTOC_PATH=proto-3.20.1/bin/protoc ./gradlew generateProto
> Task :proj:generateProto UP-TO-DATE
```

The same also holds true for plugins defined by a path instead of an artifact specification.

**Comment by ejona86** [comment]
Fixed by #560
