### ISSUE TITLE
python grpc client 

### ISSUE THREAD

**Issue by samarth-gupta-traceable** [google/protobuf-gradle-plugin#559]
i have a grpc  service defined via proto for  which we want to generate client in python client using gradle. 
We are able to successfully generate required proto messages but the actual  `*_grpc.py`  client stubs are not getting generated. 
Below is how relevant section of the gradle file looks like

```gradle
protobuf {
  protoc {
    artifact = if (osdetector.os == "osx") {
      "com.google.protobuf:protoc:${libs.versions.protoc.get()}:osx-x86_64"
    } else {
      "com.google.protobuf:protoc:${libs.versions.protoc.get()}"
    }
  }
  plugins {
    id("grpc") {
      artifact = if (osdetector.os == "osx") {
        "io.grpc:protoc-gen-grpc-java:${libs.versions.grpc.get()}:osx-x86_64"
      } else {
        "io.grpc:protoc-gen-grpc-java:${libs.versions.grpc.get()}"
      }
    }
  }
  generateProtoTasks {
    all().forEach { task ->
      task.builtins {
        id("python")
      }
    }
    ofSourceSet("main").forEach { task ->
      task.plugins {
        id("grpc")
      }
    }
  }
}
```

I have looked at https://github.com/google/protobuf-gradle-plugin/issues/52 , but could not find corresponding python plugin executables when going through https://grpc.io/docs/languages/python/quickstart/

Also in the proto messages we have dependent messages  which are coming from different project jars.  Wondering if I missed some simple task / plugin that will fix missing python grpc client code.

**Comment by ejona86** [comment]
The message configuration is using normal protoc and configuring python. That's all correct. But the gRPC configuratino is using io.grpc:protoc-gen-grpc-java. That's for Java, so obviously it won't generate Python.

You can specify `path` instead of `artifact`. With a shell script you could end up calling grpcio-tools potentially. But grpc_tools is a bit weird for this usage, so you may need to have it provide protoc itself and treat grpc_python as a builtin.

@lidizheng, is there an ordinary binary available for protoc-gen-grpc-python?

**Comment by lidizheng** [comment]
Nah, gRPC Python currently do not ship separate protoc-gen-grpc-python artifact. As mentioned above, it's encapsulated into `grpcio-tools` Python package. In it, we ship a protoc with ability to only compile Python and gRPC Python. See code:

https://github.com/grpc/grpc/blob/f9de7b0f1c9b8036c98a3f27750de0f59c9c9ed9/tools/distrib/python/grpcio_tools/grpc_tools/main.cc#L52-L56

With additional work, it's possible to split out a protoc-gen-grpc-python binary out from today's structure. But I'm not sure if we will have engineer resources to do it.

**Comment by ejona86** [comment]
Okay, with that in mind, I think this is the approach currently required:
```gradle
protobuf {
  protoc {
    path = 'protoc-python.sh'
  }
  generateProtoTasks {
    all().forEach { task ->
      task.builtins {
        id("python")
        id("grpc_python")
      }
    }
  }
}
```

protoc-python.sh would look something like:
```sh
#!/bin/sh
exec python -m grpc_tools.protoc "$@"
```

**Comment by samarth-gupta-traceable** [comment]
thanks @ejona86  and @lidizheng  for the inputs, will try above approach. 

Wondering will this work also for cases where we have transitive dependencies in proto files ? 
for example, we have dependency on proto messages which are part of different project. For java we include them using below

`dependencies {
  api(libs.bundles.grpc.api) 
  protobuf(libs.other.proto.messages) { isTransitive = false }
}`

and import them in proto files `import "other/proto/messages/remote.proto";`

this works for java and python when initiated via gradle plugins, not sure if same will be valid when we use exec `exec python -m grpc_tools.protoc "$@"`

**Comment by ejona86** [comment]
`protoc-python.sh` should have no impact on whether the .proto structure works. If it works for java and python, it should work for python_grpc.

**Comment by gfecher** [comment]
> Nah, gRPC Python currently do not ship separate protoc-gen-grpc-python artifact. As mentioned above, it's encapsulated into `grpcio-tools` Python package. In it, we ship a protoc with ability to only compile Python and gRPC Python. See code:
> 
> https://github.com/grpc/grpc/blob/f9de7b0f1c9b8036c98a3f27750de0f59c9c9ed9/tools/distrib/python/grpcio_tools/grpc_tools/main.cc#L52-L56
> 
> With additional work, it's possible to split out a protoc-gen-grpc-python binary out from today's structure. But I'm not sure if we will have engineer resources to do it.

A separate `protoc-gen-grpc-python` artifact (published to Maven Central) would be very useful for us.
We are a java-heavy shop and our build tools and processes are gradle-based. A separate artifact callable from gradle would help us with not having to maintain a python installation within our build environment.
