### ISSUE TITLE
docs opportunity? - Did not work out of the box in VS Code without adding source set

### ISSUE THREAD

**Issue by mattwelke** [google/protobuf-gradle-plugin#561]
I use VS Code for most Java work. Usually things work out of the box whether I'm using Maven, Gradle, or no build tool at all. For this plugin, running the Gradle commands after setting up worked fine. It generated Java source code under `build/...` and my code code was able to reference this generated source code to complete a build. However, it only worked if I was running Gradle commands.

VS Code itself didn't work right. It didn't seem to be aware of the generated source code. If I tried to import it, VS Code displayed error messages (even though the Gradle build worked fine). Example:

![image](https://user-images.githubusercontent.com/7719209/171314166-7ebed45c-7554-41c0-85cf-6768cb117625.png)

I describe the issue in detail here: https://stackoverflow.com/questions/72440517/how-do-i-configure-vs-code-and-gradle-to-use-generated-java-code-with-the-gradle

Here's what I want to know... Is this the way the plugin is supposed to work? That it supports Gradle, and nothing else? And it's up to other tools to add config to detect the source code? If this is the case, perhaps the solution is to add documentation to the plugin repo's README file to describe to VS Code users how to make VS Code aware of the generated source code. Or, if this is not the way the plugin is supposed to work, should there be some change to how it works to make tools like VS Code detect the generated source code and add it to their class path automatically (if that's even possible)?

**Comment by mattwelke** [comment]
Looks someone suggested a change that would fix this issue on the plugin side: https://github.com/google/protobuf-gradle-plugin/issues/109#issuecomment-339943285

**Comment by ejona86** [comment]
This should be resolved with #590. (#601 should have helped, but wasn't enough by itself.)

**Comment by mattwelke** [comment]
@ejona86 Cool. In order to test this, I'd want to keep an eye on releases for this repo to see when the PR you link to gets included in a release right? The fix wouldn't yet be in [v0.8.19](https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.8.19) (latest version right now)?

**Comment by ejona86** [comment]
Right. It'll be in v0.9.0, which I would ordinarily hope is this week, but may not end up being so (due to other busyness).
