### ISSUE TITLE
README - wrong classpath?

### ISSUE THREAD

**Issue by tomkcook** [google/protobuf-gradle-plugin#573]
The readme has this example:

```
buildscript {
  repositories {
    gradlePluginPortal()
  }
  dependencies {
    classpath 'gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.19'
  }
}
```

But this gives me an error including `Could not find gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.19.`  For this to work, I have to instead use `com.google.protobuf:protobuf-gradle-plugin:0.8.19`.

I'm using the plugin in a flutter project; I'm not sure if this makes a difference.

**Comment by ejona86** [comment]
See https://github.com/google/protobuf-gradle-plugin/pull/571
