### ISSUE TITLE
proto import of main proto from test fails by default

### ISSUE THREAD

**Issue by pcostell** [google/protobuf-gradle-plugin#58]
See https://github.com/pcostell/protobuf-gradle-plugin/pull/1 for an example test of where this fails.

For normal java imports, the test directory gets the main directory as a dependency. However, this doesn't happen for proto imports.

I was able to resolve this by updating my generateProtoTasks with:

```
  generateProtoTasks {
    ofSourceSet("test").each {task ->
      sourceSets.main.proto.srcDirs.each { srcDir ->
        task.include srcDir
      }
    }
  }
```

I would expect this to happen automatically for all test source sets to match the java rules.

**Comment by zhangkun83** [comment]
I did some research and here is the the results so far.

The plugin extracts protos from the __artifacts__ (typically `.jar`s) and __projects__ (which is basically a local artifact) that a configuration depends on. For example, through the `compile` configuration, the plugin gets the artifacts that the `main` source set depends on, which are a bunch of `.jar`s that contains the protos. Same story for the `testCompile` configuration which represents the `test` source set.

However, the `testCompile` configuration doesn't depend on any `.jar` from the `main` source set. If you query `testCompile` you will find all the inter-project dependencies but not the `main` source set from the same project: 

```
$ ./gradlew -q testProject:dependencies --configuration testCompile

testCompile - Compile classpath for source set 'test'.
+--- com.google.protobuf:protobuf-java:3.0.0-alpha-3
+--- junit:junit:4.7
\--- com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-3
```

Instead, `testCompile` _extends_ the `compile` configuration, which means it inherits its dependencies. This can be queried by
```gradle
println configurations['testCompile'].hierarchy
```
in `build.gradle`, which says
```
[configuration ':testProjectCustomProtoDir:testCompile', configuration ':testProjectCustomProtoDir:compile']
```

I think the proper fix would be including the proto source dirs from all super configurations.

**Comment by zhangkun83** [comment]
Seems I cannot get the source dir from a configuration. I made a PR that uses a different approach.
