### ISSUE TITLE
Task ':sourcesJar' uses this output of task ':generateProto' without declaring an explicit or implicit dependency

### ISSUE THREAD

**Issue by stillya** [google/protobuf-gradle-plugin#591]
**Bug:**

On Gradle 7.5 when running ```assemble``` which including ```sourcesJar``` if it's turn on in _java-plugin_  detects that this task uses outputs from ```generateProto``` without any implicit or explicit dependency between the two tasks.
```
> Task :sourcesJar
Execution optimizations have been disabled for task ':sourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/stillya/code/stilya/grpc-plugin-graph-bug/lib-commons/build/generated/source/proto/main/grpc'. Reason: Task ':sourcesJar' uses this output of task ':generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/stillya/code/stilya/grpc-plugin-graph-bug/lib-commons/build/generated/source/proto/main/grpckt'. Reason: Task ':sourcesJar' uses this output of task ':generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```
For reproducing this bug I created [repository](https://github.com/stillya/grpc-plugin-bug) with project and protobuf definitions, I hope this help.

**Environment:**
 - Gradle 7.5
 - Versions of dependencies you can see in  [repository](https://github.com/stillya/grpc-plugin-bug)

**Workaround:**
`
tasks.named("sourcesJar").configure {
    dependsOn("classes")
}
`

**Comment by oreid-zd** [comment]
We also get a similar error:

```
> Task :processResources
Execution optimizations have been disabled for task ':processResources' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'LOCATION_REDACTED'. Reason: Task ':processResources' uses this output of task ':generateProto' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

```

**Comment by ejona86** [comment]
After changing the `grpc-plugin-bug` repo to use gradle 7.5 I reproduced the problem. But the error isn't caused (directly) by the plugin. The error is caused by the project's `build.gradle.kts`:

```
sourceSets.main {
    java.srcDirs(
        "build/generated/source/proto/main/grpc",
        "build/generated/source/proto/main/grpckt",
        "build/generated/source/proto/main/java",
        "build/generated/source/proto/main/kotlin"
    )
}
```

That doesn't add the appropriate dependencies. But the fix is a bit hard with the latest release. We're currently reworking some of the internals to add the generated code to the sourceSets, which would avoid the need for those lines of code.

**Comment by toanle2022** [comment]
Please try with bellow source code in build.gradle (it worked in my project)
```
afterEvaluate {
     processResources.dependsOn generateProto
}
```
But I think this solution is not the best. if any body have other solutions, please share it in this issue.

**Comment by ejona86** [comment]
v0.9.x should resolve this, as the plugin now adds the srcdirs to the java sourcesets.
