### ISSUE TITLE
Support protoc plugin options

### ISSUE THREAD

**Issue by ejona86** [google/protobuf-gradle-plugin#6]
Plugins sometimes support parameters by passing semicolon-delimited options before the output file name of the out paramater passed to protoc.

Nano for Java [uses this heavily](https://github.com/google/protobuf/tree/master/javanano#to-use-nano-protobufs-outside-of-android-repo). To use Nano with gRPC you also need to add [nano=true](https://github.com/grpc/grpc-java/tree/master/compiler).

We need a way to provide such options.

**Comment by zhangkun83** [comment]
In the example parameters are coma-delimited. Is it the case?

There are two features to be added:

1. Allow generating nano messages by adding ``--javanano_out``. Potentially you may use ``-javanano_out`` and ``--java_out`` at the same time, but I don't know whether it's useful.
2. Allow adding parameters to any of the ``--*_out`` flag

**Comment by zhangkun83** [comment]
@madongfly

**Comment by ejona86** [comment]
@zsurocking

**Comment by zhangkun83** [comment]
Here is the interface in my mind:

1. Options are per-sourceSet, so you can configure a sourceSet to generate normal Java, and another sourceSet to generate nano.
2. It seems natural (and more flexible) to me to allow a sourceSet to specify the plugins it wants to apply. By default no plugin is applied. ``protobufCodeGenPlugins`` and ``protobufNativeCodeGenPluginDeps`` will define the plugin artifacts, but will no longer apply all plugins automatically.

```
sourceSets {
  main {
    proto {
    ...
    }
  }
  nano {
    proto {
      // Selects between --java_out and --javanano_out, default is 'java'
      mode 'javanano'
      // Options added to --java_out or --javanano_out
      option 'java_package=src/proto/simple-data.proto|my_package'
      option 'java_outer_classname=src/proto/simple-data.proto|OuterName'
      // Apply the 'grpc' plugin defined in protobufNativeCodeGenPluginDeps
      plugin 'grpc' {
        // Options added to --grpc_out
        option 'nano=true'
      }
    }
  }
}

protocDep = 'com.google.protobuf:protoc:3.0.0-alpha-2'
// This just defines the plugin artifacts, but will not automatically apply them.
protobufNativeCodeGenPluginDeps = ['grpc:io.grpc:protoc-gen-grpc-java:0.1.0-SNAPSHOT']
```
