### ISSUE TITLE
In version 0.9.0, plugin tries to parse .gitlab-ci.yml file 

### ISSUE THREAD

**Issue by stealthrabbi** [google/protobuf-gradle-plugin#622]
On version 0.8.19, the plugin generated source w\o issue. On 0.9.0, it is trying to parse ` .gitlab-ci.yml` as a proto file and failing. Perhaps it is ignoring source sets?

$ ./gradlew build
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
> Task :generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: [libprotobuf WARNING src/google/protobuf/compiler/parser.cc:646] No syntax specified for the proto file: .gitlab-ci.yml. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  .gitlab-ci.yml:1:1: Expected top-level statement (e.g. "message").
  .gitlab-ci.yml:6:58: Need space between identifier and decimal point.
  .gitlab-ci.yml:28:68: Expected top-level statement (e.g. "message").
  .gitlab-ci.yml:30:36: "/*" inside block comment.  Block comments cannot be nested.
  .gitlab-ci.yml:49:1: End-of-file inside block comment.
  .gitlab-ci.yml:29:97:   Comment started here.

**Comment by rougsig** [comment]
duplication of https://github.com/google/protobuf-gradle-plugin/issues/620
