### ISSUE TITLE
0.9.x adds generated proto files to main source set

### ISSUE THREAD

**Issue by tinder-dthomson** [google/protobuf-gradle-plugin#625]
This affects both `0.9.0` and `0.9.1`.

There appears to be a regression that causes the generated proto files to be added to the main source set.

When running a simple `checkstyleMain` task over a Gradle project that only includes `src/main/proto`, the task fails due to the generated code not conforming to the rules. This was previously not an issue.

I suspect this could be related to the motivation for `0.9.1`, but perhaps a slightly different cause.

**Comment by rougsig** [comment]
What linter are you using?

**Comment by tinder-dthomson** [comment]
@rougsig [Checkstyle](https://docs.gradle.org/current/userguide/checkstyle_plugin.html)

**Comment by ejona86** [comment]
Adding the generated proto files to the main source set is on purpose and working as expected. You will need to [exclude](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html#org.gradle.api.plugins.quality.Checkstyle:excludes) the generated code from Checkstyle.

**Comment by tinder-dthomson** [comment]
@ejona86 I was looking at that as a workaround option and we can certainly use excludes, but curious what the motivation of the change is?

**Comment by rougsig** [comment]
@tinder-dthomson The reason for the change was for a more natural Gradle experience. If sources are added to sourceSet, gradle does a lot automatically. IDE support, resource packaging, easily task configuration avoidance support, etc

https://github.com/google/protobuf-gradle-plugin/pull/601
