### ISSUE TITLE
GoBgp gRPC Java client is not working with Gradle protobuf plugin

### ISSUE THREAD

**Issue by Marty-Github** [google/protobuf-gradle-plugin#627]
Hello,

I'm trying to implement [gobgp grpc java client](https://github.com/Marty-Github/gobgp-grpc-java-client) by means of gradle build tool.  
Projects [grpc-java](https://github.com/grpc/grpc-java) and [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) are used as dependencies and plugin. It's building and running with error:

```
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service apipb.GobgpApi
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
at apipb.GobgpApiGrpc$GobgpApiBlockingStub.getBgp(GobgpApiGrpc.java:3033)
at grpc.Client.build_path(Client.java:80)
at grpc.Client.process(Client.java:123)
at grpc.Client.main(Client.java:136)
```

The **_*.proto_** files are taken from [gobgp/api](https://github.com/osrg/gobgp/tree/master/api) .

The only example [gobgp-grpc-java](https://github.com/ng-labo/gobgp-grpc-java) I've found uses Maven tool and can't be built.
I use java client's source code from that example in my project.

My environment:
OS: Windows 10 => WSL2 => Ubuntu 20.04
JDK: java-11-openjdk (linux)

```$>java -version```  
_openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)_

GoBgp service is installed under WSL2(Ubuntu 20.04) by command:  
```$>sudo apt-get -y install gobgpd```

GoBgp's version:  
```$>apt-cache policy gobgpd```  
_gobgpd:  
  Installed: 2.12.0-1  
  Candidate: 2.12.0-1  
  Version table:  
 *** 2.12.0-1 500  
    500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages  100 /var/lib/dpkg/status_  

GoBgp service is runnig with configuration file taken from your [Getting Started](https://github.com/osrg/gobgp/blob/master/docs/sources/getting-started.md).  
GoBgp CLI is working well. All commands are executed.  

Could you please clarify what's wrong with it.
Is there any working example of grpc java client for gobgp?

Thanks

= = = = = = = = = = = = = =  = = = = = = = = == = = = = =
   Gradle configuration
= = = = = = = = = = = = = =  = = = = = = = = == = = = = =

```
plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.1'
}

group 'com.gobgp.grpc'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.grpc:grpc-protobuf:1.49.2'
    implementation 'io.grpc:grpc-stub:1.49.2'
    implementation 'io.grpc:grpc-all:1.49.2'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    runtimeOnly 'io.grpc:grpc-netty-shaded:1.49.2'
}


protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.7"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.49.2'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
```

**Comment by rougsig** [comment]
Hi,

1. Here is an reproducible project https://github.com/Marty-Github/gobgp-grpc-java-client right?
2. What Gradle task are you running to get the error?

**Comment by Marty-Github** [comment]
Thank you for responce

1. This project is my attempt to implement GoBgp gRPC Java client.
   Yes, the error ("io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service apipb.GobgpApi") is reproduced.
   
2. I've just added Gradle task 'run'.
	Now it can be run from project's dir by command:

```gobgp-grpc-java-client$> ./gradlew run```

**Comment by rougsig** [comment]
Does `build` task completed successfully? Is it runtime exception or compile time?

Looks like runtime. And in that reason its not a problem from protobuf-gradle-plugin. Seems more like a gobgc or grpc missed some dependencies.

**Comment by Marty-Github** [comment]
Yes, ```build``` task completed successfully.
Yes, it's runtime exception.
Yes, it seems more like gobgc grpc api or gobgc's *.proto-files aren't correct.

But, may be protobuf-gradle-plugin doesn't generate gobgc grpc api implementations properly. E.g. It doesn't determine
gobgc grpc service's name correctly.  
And then, if grpc misses some dependencies what grpc-java dependencies are necessary for protobuf-gradle-plugin for proper generation? E.g. I've tried [grpc-all](https://mvnrepository.com/artifact/io.grpc/grpc-all)  

It seems to me the matter could be in incompatibility of grpc-java dependencies' versions.

**Comment by ejona86** [comment]
> UNIMPLEMENTED: unknown service apipb.GobgpApi

This is simply that the service isn't registered on the server. This is just a code problem; either the server needs some fixes, or the client is hitting the wrong server or wrong port. Generated code issues wouldn't cause anything like this.

**Comment by Marty-Github** [comment]
Thank you for response   

Both client and server are run on the same wsl--Ubuntu 20.04 localhost.   
Client tries to hit default gobgp grpc port 50051.   

```ManagedChannel channel = ManagedChannelBuilder.forTarget("localhost:50051").usePlaintext().build();```  

GoBgp CLI controls GoBgp demon by gRPC on 50051 port. GoBgp CLI, which is go grpc client, working properly under WSL.   
Could you please clarify how service should be registered on the server.

**Comment by ejona86** [comment]
In Go, there should be a method name something like `RegisterGobgpApiServer()`. See the Go basics tutorial. https://grpc.io/docs/languages/go/basics/

**Comment by Marty-Github** [comment]
As I understand, gRPC server must register itself on start up.
But my gRPC client should use existent and running gobgp grpc server. I suppose it's already registered.
I'm trying to implement grpc-java **client** connecting to **existent** grpc **server**.

**Comment by ejona86** [comment]
@Marty-Github, the other option is you aren't using the same `.proto` between Go and Java. If the package name is different, for example, the method won't be found. In any case this repo is not a good place to help. Honestly, I expect gobgp to be in the best position to tell you what proto to use and explain why the method may not be found.
