### ISSUE TITLE
osdetector-gradle-plugin:1.7.1 was missing from repo

### ISSUE THREAD

**Issue by DanielLiu1123** [google/protobuf-gradle-plugin#634]
see https://repo.gradle.org/ui/native/jcenter/com/google/gradle/osdetector-gradle-plugin

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/62151295/198981318-bda91985-833f-4b19-8d57-84cab1ff8b34.png">

**Comment by rougsig** [comment]
JCenter is down now https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by DanielLiu1123** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/62151295/198983531-d9703832-857e-47b7-a35a-e650d34d4fa5.png">

when I upgrade to 0.9.0, the above error occurs. And 7 hours ago, it still worked with 0.9.0  :)

**Comment by rougsig** [comment]
https://plugins.gradle.org/plugin/com.google.osdetector

Have 1.7.1 version. Do you modify pluginManagment block? Or buildScript?

**Comment by DanielLiu1123** [comment]
I don't modify `pluginManagment` or `buildScript` block.

I have tried multiple times in different project, and I think it's can be reproduced.

**Comment by rougsig** [comment]
Please wait until the https://status.gradle.com/ JCenter issue is fixed.

**Comment by ejona86** [comment]
status.gradle.com has improved. Closing, since this is almost certainly fixed. If not, comment and we can reopen.
