### ISSUE TITLE
Allow to specify "include" directory root

### ISSUE THREAD

**Issue by Alex-za1** [google/protobuf-gradle-plugin#638]
Consider the following repository:
```
<repo root>/projectA/src/mail/proto/A.proto
<repo root>/projectB/proto/<hundred of .proto files>
```

A.proto has a number of "import" statements like this:

`import "projectB/proto/some-proto-file.proto";`

To ensure successful build of Project A, one can add a sourceSets.main.proto.srcDir "../projectB/proto". The problem is, now we are trying to compile all the .proto files in Project B, and
- There are over a hundred of files there, so cold build time increases unnecessarily
- Some of those files are meant for C++ and don't even product compileable Java.

Proposed solution: to add a plugin setting which allows one to specify an "include" directory, which will be used to search for files included by those in the source sets.

I'll see if I can implement this, but also curious if there's a better way to solve this problem. Thanks!

**Comment by rougsig** [comment]
For now you can add includeDir via this code
```kotlin
protobuf {
  generateProtoTasks {
    ofSourceSet('main').configureEach { task ->
      task.addIncludeDir(files('path-to-my-dir'))
    }
  }
}
```

**Comment by Alex-za1** [comment]
Ah interesting! Thanks for the suggestion @rougsig .

With `addIncludeDir` the proto compilation phase seems to complete successfully, but Java files are only generated for A.proto, and not for .proto files that A.proto includes. As a result, the generated Java code does not compile.

**Comment by rougsig** [comment]
Yes. If you wanna compile proto files you should pass it as sources.

**Comment by Alex-za1** [comment]
Got it. Ran an experiment and found this is the way protoc is implemented. Thanks!
