### ISSUE TITLE
Unable to compile with errors

### ISSUE THREAD

**Issue by gokul2411s** [google/protobuf-gradle-plugin#65]
Hi team.

I am attaching a set of files representing a simple proto setup. There is a gradle build (with wrapper) and a single proto file. I have followed the instructions on  using the protobuf-gradle-plugin. However, I get the following errors when I run `gradlew build`.

[proto.zip](https://github.com/google/protobuf-gradle-plugin/files/207897/proto.zip)

:extractIncludeProto
:extractProto UP-TO-DATE
:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: /media/Data/projects/new/protos/mcq/build/extracted-protos/main: warning: directory does not exist.
  google/protobuf/any.proto:95:10: "google.protobuf.Any.type_url" is already defined in file "build/extracted-include-protos/main/google/protobuf/any.proto".
  google/protobuf/any.proto:98:9: "google.protobuf.Any.value" is already defined in file "build/extracted-include-protos/main/google/protobuf/any.proto".
  google/protobuf/any.proto:74:9: "google.protobuf.Any" is already defined in file "build/extracted-include-protos/main/google/protobuf/any.proto".
  google/protobuf/type.proto: Import "google/protobuf/any.proto" was not found or had errors.
  google/protobuf/type.proto:171:3: "google.protobuf.Any" seems to be defined in "build/extracted-include-protos/main/google/protobuf/any.proto", which is not imported by "google/protobuf/type.proto".  To use it here, please add the necessary import.
  build/extracted-include-protos/main/google/protobuf/api.proto: Import "google/protobuf/type.proto" was not found or had errors.
  build/extracted-include-protos/main/google/protobuf/api.proto:56:12: "Option" is not defined.
  build/extracted-include-protos/main/google/protobuf/api.proto:90:3: "Syntax" is not defined.
  build/extracted-include-protos/main/google/protobuf/api.proto:112:12: "Option" is not defined.
  build/extracted-include-protos/main/google/protobuf/api.proto:115:3: "Syntax" is not defined.

Another issue is that I am having to create an empty src/main/proto directory just because the plugin requires that. Is there a way to avoid this?

Ultimately, I want to be able to define a GRPC service in this proto file, and make it build with the grpc plugin to protoc.

Can someone kindly help?

**Comment by zhangkun83** [comment]
This is your project structure:
```
src/main/proto/
mcq.proto               
build.gradle            
settings.gradle
```
You should put `mcq.proto` under `src/main/proto`, and remove the following lines from your `build.gradle`, because what they do is to make all temporary files and output files into your source set, which is a very bad idea.
```
proto {                                                                                                                                                                                         
  srcDirs '.'                                                                                                                                                                                 
}
```

**Comment by gokul2411s** [comment]
That did work. Thanks for that.

But I wanted to create a project structure as follows.

```
codebase
--- protos
    --- project1
        --- something.proto

--- genfiles // generated files
    --- java
        --- Something.java // a class from the above proto file.

--- java // handcrafted Java code
    --- project1
        --- client
            --- ClientThatUsesSomething.java
        --- server
            --- ServerThatUsesSomething.java
```

How can I accomplish this? My main intention is to separate the protos from Java code, since the protos could be used by code from other languages as well.

Also, I do not want to maintain the rigid structure imposed by say src/main/proto or src/main/java.

Could you kindly guide me?

**Comment by zhangkun83** [comment]
This looks entirely different from Gradle's project structure, I don't know how you could manage subprojects like this in general.

protos are in `src/main/proto`, while (handcrafted) Java code are in `src/main/java`, so they are separate. Generated files are under `build`, which is not part of your source and in most cases you wouldn't need to care about their actual locations.
