### ISSUE TITLE
java files are not created in Android Studio

### ISSUE THREAD

**Issue by jeaimetu** [google/protobuf-gradle-plugin#650]
Hi, I tried to apply protobuf so I generated proto file and tried to use it. But any java or kotlin files were not created.
To localize the issue, I also tried to use Googling example, but it also failed.

Android studio version : Android Studio Dolphin | 2021.3.1 Patch 1

**build.gradle for the project**
```
`buildscript {
    ext.protobufVersion = '0.9.1'
    dependencies {
        classpath "com.google.protobuf:protobuf-gradle-plugin:$protobufVersion"
    }
}`
```

build gradle for the module

```
`plugins {
    id 'com.android.application'
    id 'com.google.protobuf'
    id 'org.jetbrains.kotlin.android'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.8.0'
    }
    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.8.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.plugins {
                javalite {}
            }
        }
    }
}`

```

**and this is the example proto file**
```
`syntax = "proto2";

package com.example.android.myapplication;

option java_package = "com.example.android.myapplication.proto";
option java_outer_classname = "UserInfo"; 

message Person { 
  required string name = 1; 
  required int32 id = 2;
  optional string email = 3;
  optional PhoneNumber phones = 4; 


  message PhoneNumber {
    required string number = 1;
    optional PhoneType type = 2 [default = HOME]; 
  }

  enum PhoneType { 
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }
}

message AddressBook {
  repeated Person people = 1;
}`

```
**and I tried to use this as follows**
```
`package com.example.android.myapplication;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;

import com.example.android.myapplication.proto.UserInfo.Person;
**// can not import this because there are no java file for UserInfo proto file.**

import com.example.android.myapplication.MyProtoBuf.*;
public class MyProtoBuf extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Integer mId = 1;
        String mUserName = "rick";
        String mAddress = "asdf1234@gmail.com";
        Person protoPerson = Person.newBuilder() `

```
Any Idea will be helpful. 

I have tried adding
- SrcSet
- Put "javalite" in the builtin sections
- Invlidate caches and restart..
but all failed.

and..these are screenshot for proto pakcage folder and generated folder
<img width="346" alt="Screen Shot 2022-12-26 at 9 55 50 PM" src="https://user-images.githubusercontent.com/32817067/209551532-0ae29c1a-c171-48c5-9776-326f0a3fc7f4.png">

<img width="399" alt="Screen Shot 2022-12-26 at 9 56 04 PM" src="https://user-images.githubusercontent.com/32817067/209551576-bfb9bb12-09cb-44f2-85c0-4bff1e8a34e9.png">

**Comment by rougsig** [comment]
Hello. Could you please upload your example project to github?

**Comment by jeaimetu** [comment]
> Hello. Could you please upload your example project to github?

Sure, wait for a minute.

**Comment by jeaimetu** [comment]
Hi Rougsig, please check this. https://github.com/jeaimetu/ProtobufTest

**Comment by rougsig** [comment]
I dont see any proto files in your project. If you havent proto files, no files will be generated.

Feel free to use our example https://github.com/google/protobuf-gradle-plugin/tree/master/examples%2FexampleProject

**Comment by jeaimetu** [comment]
Hi Rougsig, proto file is here. https://github.com/jeaimetu/ProtobufTest/tree/main/app/src/main/java/proto
Location is wrong?
Yes I also check your share example.

**Comment by rougsig** [comment]
Ou. Yes location is wrong. It should be on `src/main/proto/` (`src/SOURCESET_NAME/proto`)

**Comment by jeaimetu** [comment]
Oops..thanks for your guide!  I will try that and get back here.

**Comment by rougsig** [comment]
As you figure it out, please write what you lacked in the documentation for understanding.

**Comment by jeaimetu** [comment]
Moving the folder resolve shomething. However I faced another issue on Macbook M1, but I can handle this. After than I will update the my lack point in the document.

```
Execution failed for task ':app:generateDebugProto'.
> Could not resolve all files for configuration ':app:protobufToolsLocator_protoc'.
   > Could not find protoc-3.0.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.0.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-osx-aarch_64.exe

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html


```

**Comment by jeaimetu** [comment]
Hi @rougsig meanwhile, I have a questions on here.

```
sourceSets {
  main {
    proto {
      // In addition to the default 'src/main/proto'
      srcDir 'src/main/protobuf' 
```

what if I added srcDir  'src/main/java' 
then can this work also instead of moving proto folder under the SourceSet?

**Comment by rougsig** [comment]
Use the latest protoc version 3.21.12

https://search.maven.org/artifact/com.google.protobuf/protoc

**Comment by rougsig** [comment]
> what if I added srcDir 'src/main/java'
then can this work also instead of moving proto folder under the SourceSet?

Yes, but it is not recommended, because gradle will rerun tasks, even the sources was not changed.

**Comment by jeaimetu** [comment]
I have resolved this issue because you helped me.
1) changing the proto folder correctly as you mentioned.
2) After then, there are Mac M1 library issue, so that is resolved by as follows
`artifact = 'com.google.protobuf:protoc:3.21.12:osx-x86_64'`

Before finalizing this issue, I have one more question.

this is the result for the result of "gradlew sourceset"
```
Compile configuration: testReleaseCompile
build.gradle name: android.sourceSets.testRelease
Java sources: [app/src/testRelease/java]
Kotlin sources: [app/src/testRelease/kotlin, app/src/testRelease/java]
Java-style resources: [app/src/testRelease/resources]
```

In here, what is the exact part of "sourceSet" what you previously mentioned?

I think if there are trouble shooting or warning, then it will be really helpful.

**Comment by rougsig** [comment]
> In here, what is the exact part of "sourceSet" what you previously mentioned?

In your example, you have sourceSet with name `testRelease`. So path for that sourceset should be `src/testRelease/proto`.

**Comment by rougsig** [comment]
`src/testRelease/proto` its default path, what was automatically added. You can add extra dirs if you want. 
Like that:
```
android {
  sourceSets {
    <sourceSetName> {
      proto {
        srcDir 'my/custom/folder'
      }
    }
  }
}
```

**Comment by jeaimetu** [comment]
and I need to add some details. I marked proposed text to bold.

"Configuring Protobuf compilation
The Protobuf plugin assumes Protobuf files (*.proto) are organized in the same way as Java source files, in sourceSets. 

**For example, Java source files are in "src/main/java", then proto folder must be src/main/proto as the same level with Java folder. If not, proto files are not compiled during the build process. So you can not find any Java files. In here "proto" is example, so you can change the name what you want**

The Protobuf files of a sourceSet (or variant in an Android project) are compiled in a single protoc run, and the generated files are added to the input of the Java compilation run of that sourceSet (or variant)." **and You can find them in the generated folder(build/generated/source/proto)**

**For Macbook M1 users, you should use workaround to compile proto files. This ":osx-x86_64" prefix is need for artifact.**

**Comment by jeaimetu** [comment]
> `src/testRelease/proto` its default path, what was automatically added. You can add extra dirs if you want. Like that:
> 
> ```
> android {
>   sourceSets {
>     <sourceSetName> {
>       proto {
>         srcDir 'my/custom/folder'

>       }
>     }
>   }
> }
> ```

cool, then this project view screenshot will be very helpful.
<img width="186" alt="Screen Shot 2022-12-27 at 2 13 56 AM" src="https://user-images.githubusercontent.com/32817067/209570850-9146a5d0-c038-418f-a415-e87a95768809.png">

**Comment by jeaimetu** [comment]
Thanks! I really appreciate your support!

**Comment by rougsig** [comment]
> For example, Java source files are in "src/main/java", then proto folder must be src/main/proto as the same level with Java folder. If not, proto files are not compiled during the build process. So you can not find any Java files. In here "proto" is example, so you can change the name what you want

I did not understand the question.

> For Macbook M1 users, you should use workaround to compile proto files. This ":osx-x86_64" prefix is need for artifact.

That qualifier should automatically added by plugin. You as end user should write only `com.google.protobuf:protoc:<version>`

**Comment by jeaimetu** [comment]
> > In here, what is the exact part of "sourceSet" what you previously mentioned?
> 
> In your example, you have sourceSet with name `testRelease`. So path for that sourceset should be `src/testRelease/proto`.

Oh??? but I just move then to the same level as JAVA as you can see the above screenshot? Do you mean both path will work?

**Comment by jeaimetu** [comment]
> > For example, Java source files are in "src/main/java", then proto folder must be src/main/proto as the same level with Java folder. If not, proto files are not compiled during the build process. So you can not find any Java files. In here "proto" is example, so you can change the name what you want
> 
> I did not understand the question.
> 
> > For Macbook M1 users, you should use workaround to compile proto files. This ":osx-x86_64" prefix is need for artifact.
> 
> That qualifier should automatically added by plugin. You as end user should write only `com.google.protobuf:protoc:<version>`

For M1 case, it try to add arm architecture plugin, but as far as I knew, there are no arm architecture plugin.

**Comment by jeaimetu** [comment]
> 
I did not understand the question. --> Above paragraph is not the question but the comment what I want to add to README.
Thanks

**Comment by rougsig** [comment]
> For M1 case, it try to add arm architecture plugin, but as far as I knew, there are no arm architecture plugin.

Plugin works from java part. It's no need to be special for arm. But protoc need to be.

**Comment by rougsig** [comment]
> Oh??? but I just move then to the same level as JAVA as you can see the above screenshot? Do you mean both path will work?

Yes. For each sourceSet default path to find proto files is `src/<SOURCESET_NAME>/proto`.

**Comment by jeaimetu** [comment]
> > For M1 case, it try to add arm architecture plugin, but as far as I knew, there are no arm architecture plugin.
> 
> Plugin works from java part. It's no need to be special for arm. But protoc need to be.

Perfect. I found that this version have arm release, com.google.protobuf:protoc:3.21.7.
