### ISSUE TITLE
Gradle build failing with gradle 2.12

### ISSUE THREAD

**Issue by delakanda** [google/protobuf-gradle-plugin#66]
The gradle build is failing with this release.
i am using gradle 2.12.

Error Message : Error:(2, 0) Cause: org/gradle/api/internal/file/collections/DefaultDirectoryFileTreeFactory

When i switch back to the 0.7.5 release, it builds fine

**Comment by zhangkun83** [comment]
0.7.6 should work with Gradle 2.12, while 0.7.5 doesn't. I guess you are not using Gradle 2.12 actually. Can you build from the command line with `--stacktrace` and post the full output?
