### ISSUE TITLE
Proto sourceset not generated

### ISSUE THREAD

**Issue by delakanda** [google/protobuf-gradle-plugin#67]
after adding the proto to the source block, i dont see any proto directory.

Here is the definition as added in my build.gradle file

```
android {
    sourceSets {
        main {
            proto {
                srcDir 'src/main/proto'
                include '**/*.protodevel'
            }
        }
    }
}
```

**Comment by zhangkun83** [comment]
This doesn't create proto directory for you. If you have any proto files to compile, you will put them under `src/main/proto` as indicated in the sourceSets block.

**Comment by delakanda** [comment]
i see... i finally got something working..thanks
