### ISSUE TITLE
project does not build "peer not authenticated"

### ISSUE THREAD

**Issue by YifeiZhuang** [google/protobuf-gradle-plugin#695]
on branch `v0.9.x`, build failure with `peer not authenticated`

```
 > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar'
         > peer not authenticated
```

**Comment by YifeiZhuang** [comment]
this works for me:
https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse


need to import root certificate of `https://jcenter.bintray.com/`
`$ keytool -importcert -file _.bintray.com.cer -storepass changeit -keystore cacerts --alias jcenter`

**Comment by ejona86** [comment]
The CI has caching enabled (via gradle-build-action), and I also would have my local cache. So that's probably why we didn't notice.
