### ISSUE TITLE
Task generateProto is not executed during build in version 0.9.3

### ISSUE THREAD

**Issue by TorbenSp09** [google/protobuf-gradle-plugin#701]
Hey, i have a gradle-project using JDK v16.0.1. I just wanted to update the version of the protobuf plugin from v0.8.18 to v0.9.3. Added to that, i am using v3.22.2 of the protobuf compiler.
I have two .proto files that i need in my project. Since i updated from v0.8.18 -> v0.9.3 the generateProto task won't be executed during build. This causes some errors in my CI/CD pipeline and i don't know why this happens. These were the steps executed using v0.8.18:
![image](https://github.com/google/protobuf-gradle-plugin/assets/84403716/4c630698-71e4-421d-acae-9a25e5e4c5b1)

However, these are the steps executed after updating to v0.9.3:
![image](https://github.com/google/protobuf-gradle-plugin/assets/84403716/57bcd5ee-5e1b-482d-87d0-0058e7945c48)

As shown, the kotlinCompiler fails because the dependencies that are created by generateProto are missing now.
I have already tried several things, including manually setting the source set of the .proto files, but nothing has worked. I have also taken a look into the release notes but there i can't see anything that will cause this. I know that it is possible to add the generateProto task to the build task but i think this is not the right way to go is it?

Thank you!

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
