### ISSUE TITLE
task `extractIncludeProto` does not recognize dependency version

### ISSUE THREAD

**Issue by livk-cloud** [google/protobuf-gradle-plugin#706]
> io.netty:netty-all statement from springboot bom version
> The following is the gradle configuration

```groovy
plugins {
    id "com.google.protobuf" version("0.9.3")
}

dependencies {
    api "io.netty:netty-all"
    api "com.google.protobuf:protobuf-java:3.22.2"
}

compileJava {
    dependsOn("generateProto")
}

sourceSets {
    main {
        proto {
            srcDir "src/main/protobuf"
        }
        java {
            srcDirs "src/main/java/com/livk/protobuf"
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.22.2"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.53.0"
        }
    }

    generateProtoTasks {
        ofSourceSet("main").configureEach {
            plugins {
                grpc {}
            }
        }
    }
}
```

> Abnormal correlation
```shell
Could not determine the dependencies of task ':example:spring-netty:netty-commons:extractIncludeProto'.
> Could not resolve all files for configuration ':example:spring-netty:netty-commons:compileProtoPath'.
   > Could not find io.netty:netty-all:.
     Required by:
         project :example:spring-netty:netty-commons

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

> If I add the version to `api "io.netty:netty-all"`, there will be no problem. Is there a better way to use BOM version management

**Comment by livk-cloud** [comment]
> I tried to get the version successfully in the following way
```groovy
dependencies {
    api "io.netty:netty-all"
    api "com.google.protobuf:protobuf-java:3.22.2"
}

project.afterEvaluate {
    def dependencyResultMap = new HashMap<String, String>()
    List.of(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME, JavaPlugin.TEST_COMPILE_CLASSPATH_CONFIGURATION_NAME).forEach { configurationName ->
        project.configurations.named(configurationName).get().incoming.resolutionResult.allDependencies {
            def result= requested.displayName.split(":")
            if (result.length == 3) {
                dependencyResultMap.put(result[0] + ":" + result[1], result[2])
            }
        }
    }
    project.configurations.forEach { configuration ->
        configuration.dependencies.forEach { dependency ->
            def version = dependency.version
            if (version == null || version.isBlank()) {
                version = dependencyResultMap.get(dependency.group + ":" + dependency.name)
            }
            println dependency.group + ":" + dependency.name + ":" + version
        }
    }
}
```

```shell
> Task :buildSrc:extractPluginRequests NO-SOURCE
> Task :buildSrc:generatePluginAdapters NO-SOURCE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:compileGroovyPlugins NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

> Configure project :example:spring-netty:netty-commons
io.netty:netty-all:4.1.90.Final
com.google.protobuf:protobuf-java:3.22.2
org.projectlombok:lombok:1.18.26
org.springframework.boot:spring-boot-configuration-processor:3.0.5
org.springframework.boot:spring-boot-autoconfigure-processor:3.0.5
com.livk.boot:spring-extension-dependencies:1.0.7
io.grpc:protoc-gen-grpc-java:1.53.0
com.google.protobuf:protoc:3.22.2
org.springframework:spring-tx:6.0.7
org.springframework.boot:spring-boot-starter-test:3.0.5

> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Download https://maven.aliyun.com/repository/spring/net/minidev/json-smart/maven-metadata.xml, took 397 ms (158.72 kB)
Download https://maven.aliyun.com/repository/spring-plugin/net/minidev/json-smart/maven-metadata.xml, took 451 ms (158.72 kB)

BUILD SUCCESSFUL in 8s
4 actionable tasks: 4 up-to-date
```

How should I modify the task `extractIncludeProto` to adapt to BOM version management

**Comment by livk-cloud** [comment]
Get to use compileClasspath instead of implementation

![image](https://github.com/google/protobuf-gradle-plugin/assets/50291874/ef2516c9-433e-4eee-a0fd-7b1fb6d879ef)

**Comment by ejona86** [comment]
So looking at this, how would anything know what version to use?

```gradle
dependencies {
    api "io.netty:netty-all"
    api "com.google.protobuf:protobuf-java:3.22.2"
}
```

You say "BOM" multiple times, but I don't see any `platform()`. You might want to look [at the Gradle docs](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import).

**Comment by livk-cloud** [comment]
> 所以看看这个，怎么知道要使用哪个版本？
> 
> ```groovy-gradle
> dependencies {
>     api "io.netty:netty-all"
>     api "com.google.protobuf:protobuf-java:3.22.2"
> }
> ```
> 
> 你多次说“BOM”，但我没有看到任何`platform()`. 您可能想查看[Gradle 文档](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)。

![image](https://github.com/google/protobuf-gradle-plugin/assets/50291874/68ecb87d-b8d4-48ac-98bf-ce072c706dc6)

![image](https://github.com/google/protobuf-gradle-plugin/assets/50291874/77a47c9f-083d-45e6-9b9b-49138b1414a4)

![image](https://github.com/google/protobuf-gradle-plugin/assets/50291874/9f087c64-6517-410e-9f56-84a1a5b42f83)

> management is a custom plugin for adding BOM
> Netty's dependency control is hosted in SpringBoot BOM

**Comment by livk-cloud** [comment]
> > 所以看看这个，怎么知道要使用哪个版本？
> > ```
> > dependencies {
> >     api "io.netty:netty-all"
> >     api "com.google.protobuf:protobuf-java:3.22.2"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你多次说“BOM”，但我没有看到任何`platform()`. 您可能想查看[Gradle 文档]
> 
> This is dependent on custom BOM
> 
> ![image](https://user-images.githubusercontent.com/50291874/242137238-68ecb87d-b8d4-48ac-98bf-ce072c706dc6.png)
> 
> ![image](https://user-images.githubusercontent.com/50291874/242137073-77a47c9f-083d-45e6-9b9b-49138b1414a4.png)
> 
> ![image](https://user-images.githubusercontent.com/50291874/242137351-9f087c64-6517-410e-9f56-84a1a5b42f83.png)
> 
> > management is a custom plugin for adding BOM
> > Netty's dependency control is hosted in SpringBoot BOM
> > If you need a minimal example to reproduce, I'd be happy to provide it

Add the management code
```groovy
abstract class ManagementPlugin implements Plugin<Project> {

    public static final String MANAGEMENT = "management"

    public static final Set<String> DEPENDENCY_NAMES_SET = new HashSet<>()

    static {
        DEPENDENCY_NAMES_SET.addAll(
                Set.of(
                        JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME,
                        JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME,
                        JavaPlugin.ANNOTATION_PROCESSOR_CONFIGURATION_NAME,
                        JavaPlugin.TEST_COMPILE_CLASSPATH_CONFIGURATION_NAME,
                        JavaPlugin.TEST_RUNTIME_CLASSPATH_CONFIGURATION_NAME,
                        JavaPlugin.TEST_ANNOTATION_PROCESSOR_CONFIGURATION_NAME
                )
        )
    }

    @Override
    void apply(Project project) {
        def configurations = project.configurations
        project.pluginManager.apply(JavaPlugin.class)
        configurations.create(MANAGEMENT) { management ->
            management.visible = false
            management.canBeResolved = false
            management.canBeConsumed = false
            def plugins = project.plugins
            plugins.withType(JavaPlugin.class).every {
                DEPENDENCY_NAMES_SET.forEach { configurations.named(it).get().extendsFrom(management) }
            }
            plugins.withType(JavaTestFixturesPlugin.class).every {
                configurations.named("testFixturesCompileClasspath").get().extendsFrom(management)
                configurations.named("testFixturesRuntimeClasspath").get().extendsFrom(management)
            }
            plugins.withType(MavenPublishPlugin.class).every {
                project.extensions.getByType(PublishingExtension.class).publications
                        .withType(MavenPublication.class).every { mavenPublication ->
                    mavenPublication.versionMapping { versions ->
                        versions.allVariants {
                            it.fromResolutionResult()
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by ejona86** [comment]
I feel like the problem is probably in the ManagementPlugin.

There's a lot going on, and posting screenshots (instead of text) and snippets makes it hard to piece together. Taking the opposite approach and trying to reproduce from a simpler environment, I don't see any BOM issues if I adjust the example in this repository:

```diff
diff --git a/examples/exampleProject/build.gradle b/examples/exampleProject/build.gradle
index 4fd561f..9e38963 100644
--- a/examples/exampleProject/build.gradle
+++ b/examples/exampleProject/build.gradle
@@ -1,7 +1,7 @@
 plugins {
-  id('java')
+  id('java-library')
   id('idea')
-  id('com.google.protobuf') version '0.8.19'
+  id('com.google.protobuf') version '0.9.2'
 }
 
 repositories {
@@ -9,6 +9,8 @@ repositories {
 }
 
 dependencies {
+  api "io.netty:netty-all"
+  api platform("io.netty:netty-bom:4.1.92.Final")
   implementation 'com.google.protobuf:protobuf-java:3.6.1'
   implementation 'io.grpc:grpc-stub:1.15.1'
   implementation 'io.grpc:grpc-protobuf:1.15.1'
```

Since `ManagementPlugin` is directly modifying compile classpath, it isn't surprising that maybe it isn't working along with this plugin. Looking at the [gradle java-library configurations](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph), compileClasspath and runtimeClasspath are "internal to the component, for its own use." So they shouldn't be used unless really needed. As ManagementPlugin is currently written, it adjusts compileClasspath but not api/runtimeElements. That means that projects that depend on your current project won't know which version of Netty to use unless they also use ManagementPlugin, which is broken. Seems ManagementPlugin is using the wrong configurations, and if it is fixed to work for normal Java builds it would also be fixed for this plugin.

**Comment by livk-cloud** [comment]
> 我觉得问题可能出在 ManagementPlugin 中。
> 
> 发生了很多事情，并且发布屏幕截图（而不是文本）和片段使得很难拼凑在一起。采用相反的方法并尝试从更简单的环境中重现，如果我调整此存储库中的示例，我看不到任何 BOM 问题：
> 
> ```diff
> diff --git a/examples/exampleProject/build.gradle b/examples/exampleProject/build.gradle
> index 4fd561f..9e38963 100644
> --- a/examples/exampleProject/build.gradle
> +++ b/examples/exampleProject/build.gradle
> @@ -1,7 +1,7 @@
>  plugins {
> -  id('java')
> +  id('java-library')
>    id('idea')
> -  id('com.google.protobuf') version '0.8.19'
> +  id('com.google.protobuf') version '0.9.2'
>  }
>  
>  repositories {
> @@ -9,6 +9,8 @@ repositories {
>  }
>  
>  dependencies {
> +  api "io.netty:netty-all"
> +  api platform("io.netty:netty-bom:4.1.92.Final")
>    implementation 'com.google.protobuf:protobuf-java:3.6.1'
>    implementation 'io.grpc:grpc-stub:1.15.1'
>    implementation 'io.grpc:grpc-protobuf:1.15.1'
> ```
> 
> 由于`ManagementPlugin`是直接修改编译类路径，因此它可能无法与该插件一起工作也就不足为奇了。查看[gradle java-library 配置](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)，compileClasspath 和 runtimeClasspath 是“组件内部的，供其自己使用”。因此，除非确实需要，否则不应使用它们。正如 ManagementPlugin 当前编写的那样，它调整 compileClasspath 但不调整 api/runtimeElements。这意味着依赖于您当前项目的项目将不知道要使用哪个版本的 Netty，除非它们也使用已损坏的 ManagementPlugin。似乎 ManagementPlugin 使用了错误的配置，如果它被修复为适用于普通的 Java 构建，它也将被修复为这个插件。

> Thank for your answer, your answer made me understand a lot about the principles of gradle. I should need to make some changes from 'ManagementPlugin', thanks again
