### ISSUE TITLE
Protobuf nano and J2Objc translated classes in Swift

### ISSUE THREAD

**Issue by gchoza** [google/protobuf-gradle-plugin#71]
I have a J2Objc project using protobuf nano. The issue I'm having is that the instance variables in the generated Objective C code are iVars and Swift cannot access them directly. I have to use the "valueForKey("mResponseData_")" syntax and cast the result to the correct type which is not ideal. If I could annotate the generated protobuf Java classes with the J2Objc @Property annotation J2Ojbc would create properties but I have not found a way of annotating my .proto file to add @Property in the generated Java classes.

As a workaround I'm using " option 'optional_field_style=accessors'" to generate accessors for primitive data types. However, reference types do not have generated accessors so for those I'll have to use the "valueForKey" syntax.

Is there a better way of doing this?

Thanks,

Gabriel

**Comment by zhangkun83** [comment]
This is related to the protobuf compiler, not this plugin. Please file the issue against the [protobuf project](https://github.com/google/protobuf) instead.
