### ISSUE TITLE
ProtobufExtract after upgrading to Gradle 8.1 causes unexpected inputs to configuration cache

### ISSUE THREAD

**Issue by liutikas** [google/protobuf-gradle-plugin#711]
When we upgrade to Gradle 8.1 in github.com/androidx/androidx we found that `com.google.protobuf.gradle.ProtobufExtract$_instantiateFilteredProtos_closure4` causes `../../out/androidx/datastore/datastore-sampleapp/build/intermediates/compile_app_classes_jar/debug/classes.jar` to be an input to the configuration cache calculation.

![image](https://github.com/google/protobuf-gradle-plugin/assets/1418185/14d63525-eceb-4b54-8fe0-6ebe652b45e4)

What this means, if you run a build on a clean CI, then run a second build, then the second build will *not* hit configuration cache and will instead recalculate it from scratch again. This is very problematic for our CI usecase, but it is generally bad as it will cause a lot of invalidations of configuration cache when it is not expected.

In other similar issues with Gradle 8.1 new input to configuration cache, it has been usage of `File.exists()` that caused Gradle to consider it as an input to the configuration cache. I do not see usage of that in [ProtobufExtract.groovy](https://github.com/google/protobuf-gradle-plugin/blob/9d2a328a0d577bf4439d3b482a953715b3a03027/src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy#L118) so maybe it is the use of `isDirectory()` that is triggering it.

**Comment by liutikas** [comment]
@gavra0 👋

**Comment by gavra0** [comment]
IIUC this method does not need to run on `<init>` it can be lazy. I'll try that approach.

**Comment by gavra0** [comment]
I've uploaded a PR that fixes this issue (confirmed in a test).

**Comment by ejona86** [comment]
Fixed by #713.

And now I know the question is "when will we do a release?" We should probably fix https://github.com/google/protobuf-gradle-plugin/issues/708 as well; it seems quick. @YifeiZhuang, let's try to do a release in the next week or two.

**Comment by liutikas** [comment]
Any updates on a release of a fixed version?
