### ISSUE TITLE
Download protoc from custom repositories

### ISSUE THREAD

**Issue by rafan** [google/protobuf-gradle-plugin#712]
When configuring `protoc` using artifact like the following:
```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.21.12'
    }
}
```

It always downloads from the Maven Central (i.e., `repo.apache.maven.org`). However, it fails in a restricted environment where egress connections are regulated. 

Either the plugin honors the repositories setup in `build.gradle` or it allows customization on repositories.

**Comment by ejona86** [comment]
I don't think this is the case. We don't configure any repositories within the plugin. We only create configurations and then resolve them.
