### ISSUE TITLE
Plugin is not compatible with changes in Kotlin Gradle plugins 1.9.0 release

### ISSUE THREAD

**Issue by Tapchicoma** [google/protobuf-gradle-plugin#714]
In the Kotlin 1.9.0 release, kapt tasks should now be additionally [configured](https://youtrack.jetbrains.com/issue/KT-54468/KAPT-Gradle-plugin-causes-eager-task-creation) with the same custom configuration as `KotlinCompile` task.
[Here](https://github.com/google/protobuf-gradle-plugin/blob/9d2a328a0d577bf4439d3b482a953715b3a03027/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L349-L357) protobuf plugin configures `KotlinJvmCompile` tasks with additional generated sources. Now it should also configure `KaptGenerateStubs` task with this additional sources. Even better approach would be to configure releated `KotlinSourceSet` similar to this workaround:
```kt
androidComponents.beforeVariants {
    android.sourceSets.register(it.name) {
        java.srcDir(buildDir.resolve("generated/source/proto/${it.name}/java"))
        kotlin.srcDir(buildDir.resolve("generated/source/proto/${it.name}/kotlin"))
    }
}
```

**Comment by ejona86** [comment]
Fixed by #715
