### ISSUE TITLE
NullPointerException when building with Jack

### ISSUE THREAD

**Issue by twasilczyk** [google/protobuf-gradle-plugin#73]
Example Android project build fails after switching to Jack (new official Android toolchain). This results in inability to migrate to Jack for any project that uses protobuf-gradle-plugin.

To reproduce, apply the patch ([protobuf-gradle-plugin-jack.patch](https://github.com/google/protobuf-gradle-plugin/files/245588/protobuf-gradle-plugin-jack.patch.txt)) and run ```./gradlew test --stacktrace``` ([stack trace](http://pastebin.com/raw/Kiik1HEM)).

**Comment by zhangkun83** [comment]
I have contacted Jack developer. It's a known issue to them and hopefully will be fixed in their 2.2 release.

**Comment by mxk** [comment]
Do you know if there is an ETA on the 2.2 release? I just tried 2.2.0-alpha3 (assuming you are referring to com.android.tools.build:gradle) and the issue is still there.

**Comment by twasilczyk** [comment]
2.2.0-alpha4 works fine for me.

**Comment by mxk** [comment]
Thanks for the update. NullPointerException exception is gone, but now I'm getting `ClassNotFoundException: com.android.jack.api.v03.Api03Config` at the `:transformClassesWithPreJackPackagedLibrariesForDebug` step. Guess I'll just wait for the release.
