### ISSUE TITLE
Java keyword "public" not escaped during proto generation

### ISSUE THREAD

**Issue by wadriance** [google/protobuf-gradle-plugin#736]
See https://github.com/google/protobuf-gradle-plugin/issues/46 for the same issue with the keyword "interface". 

My protobuf files are in packages that include the word "public" like so: 
```
package example.example.public.proto;
```

When the java files are built from the protos by the Gradle plugin, the generated Java packages contain the word "public" without any escaping, which causes compilation errors since "public" is a keyword in Java.

I can submit the fix if you can point me to the right spot.

**Comment by ejona86** [comment]
This is not a plugin issue. https://github.com/protocolbuffers/protobuf is for the actual generated code. That other issue you mentioned was not for the plugin; it was fixed by a change in the protobuf repo.
