### ISSUE TITLE
doc improvement

### ISSUE THREAD

**Issue by yimingwangdell** [google/protobuf-gradle-plugin#737]
for beginner, it's very hard to find the rule:
 // In addition to the default 'src/main/proto'
it took me 2 hours to find out why file is not generated. User may think this plugin will scan all the .proto files in project.

for protoc, it's easy to understand where to find what's the input, what's the output:
./protoc -I=$SRC_DIR --java_out=$DST_DIR $SRC_DIR/AddressBook.protos

 please help to improve it by add the rule of generating java file in the beginning of document.

**Comment by ejona86** [comment]
> it took me 2 hours to find out why file is not generated.

So you read that comment and didn't understand it, or it took you two hours to find that comment? To my knowledge, no plugin scans all files within a project. Did you happen to take a look at the example?

No, we don't want to include the protoc invocation. Java users generally have no experience with the protoc command and seem to be afraid of it.
