### ISSUE TITLE
Support osdetector 1.4.0

### ISSUE THREAD

**Issue by ejona86** [google/protobuf-gradle-plugin#74]
Currently osdetector 1.2.1 is being used. osdetector 1.4.0 is incompatible because the "apply plugin" changed from "osdetector" to "com.google.osdetector". Users trying to use the newest version will thus get failures.

Changing the version protobuf-gradle-plugin uses will probably break any users running "apply plugin: 'osdetector'" themselves, but there seems little to be done to avoid that.

**Comment by jaredsburrows** [comment]
@ejona86 I have updated this in my last PR. We can close this issue now.
