### ISSUE TITLE
Feature Request: Allow configuration of java executable

### ISSUE THREAD

**Issue by wfhartford** [google/protobuf-gradle-plugin#742]
Currently the java executable used for protoc plugin JARs is inferred based on the JVM running gradle and it's `java.home` property. In most cases this means either the `java` executable on the system's `PATH` or the system's `JAVA_HOME` environment variable. While this is a great default, I have a protoc plugin JAR that is compiled for JDK 21 and some developers may not want to set their system wide JDK to 21.

It should be relatively straight forward to add a property to the `GenerateProtoTask` allowing a user to specify an arbitrary java executable in their build file.

Would a pull request adding this feature be accepted?

**Comment by ejona86** [comment]
Without looking much at how that would be plumbed, that sounds fine. Feel free to send a PR.

**Comment by ejona86** [comment]
Fixed by #750
