### ISSUE TITLE
Kotlin only generated classes

### ISSUE THREAD

**Issue by newmanw** [google/protobuf-gradle-plugin#743]
I am trying to generate koltin classes in an Android project and running into some issues.

```
generateProtoTasks {
      all().each { task ->
          task.builtins {
              java {  // Cannot remove this, leads to build issues
                  option 'lite'
              }
              kotlin {
                  option 'lite'
              }
          }
      }
  }
```

```
implementation 'com.google.protobuf:protobuf-javalite:3.25.2'
implementation("com.google.protobuf:protobuf-kotlin-lite:3.25.2")
```

This is generating kotlin DSL classes that only support a helper for the builder pattern.  If possible it would be nice to generate Kotlin only classes.  Is it possible to generate kotlin only classes?  Kotlin only class would also allow for kotlin extensions.

**Comment by ejona86** [comment]
Looks [like protobuf requires both](https://protobuf.dev/getting-started/kotlintutorial/#compiling-protocol-buffers). That's more of a protobuf and protoc thing than something about the plugin.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
