### ISSUE TITLE
Error:Unable to load class 'org.gradle.api.internal.file.collections.DefaultDirectoryFileTreeFactory'

### ISSUE THREAD

**Issue by noosxe** [google/protobuf-gradle-plugin#75]
When using "apply plugin: 'com.google.protobuf'" in build.gradle, build fails inside android studio, though using terminal gradle everything is fine. The error is:

Error:Unable to load class 'org.gradle.api.internal.file.collections.DefaultDirectoryFileTreeFactory'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by zhangkun83** [comment]
Trying to use the plugin with a Gradle older than 2.12 will cause this problem. Can you try upgrading Gradle?

**Comment by zhangkun83** [comment]
As this has been reported multiple times, I have updated the README to make the Gradle version requirement even more obvious.

**Comment by noosxe** [comment]
Thanks for your reply. I had to change gradle home from android studio settings and that finally worked, though I had already changed gradle to version 2.12 from module settings and that was not working.
