### ISSUE TITLE
Use plural form default output directory 'generated/sources'

### ISSUE THREAD

**Issue by holgerstolzenberg** [google/protobuf-gradle-plugin#754]
Currently the plugin per default generates the generated java code into "$project/$buildDir/generated/source".
This kinda breaks Gradle best practices, please see screenshot below:

<img width="267" alt="Screenshot 2024-05-02 at 21 49 26" src="https://github.com/google/protobuf-gradle-plugin/assets/282736/285fd9aa-45da-4809-b49f-9bc963f1f815">

As you can see, all other stuff in the build directory uses a plural based syntax. Even the protobuf plugin does that e.g. for "extracted-protoS" and so on. Also for that manner the generated code is not aggregated with the other generated sources in their respective  sourceSets under "generated/sourceS".

Please align the plugins output to the best practices.

Optionally:
What is the reasoning behind not having the configurable?

**Comment by NurramoX** [comment]
+1
I would also appreciate having this change released soon
