### ISSUE TITLE
False bool values are not written into message

### ISSUE THREAD

**Issue by ao-swarm** [google/protobuf-gradle-plugin#766]
Issue:
The value of the bool field in the generic `BoolValue` message is only set when the provided value is true. Attempting to set a false value skips writing to the message object.
 
Expected:
I should be able to explicitly send a false boolean value in a message.

Version 0.9.4

--

```kotlin
bool { value = true }  // creates message with value 'true'

bool { value = false }  // creates message with no value
```

```java
// from BoolValue.java
// not entirely sure if it's relevant, but logic here matches what I'm seeing

@java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != false) {
      output.writeBool(1, value_);
    }
    getUnknownFields().writeTo(output);
  }
```

**Comment by ejona86** [comment]
This repository is just for the Gradle integration of protoc. You should file an issue like that in https://github.com/protocolbuffers/protobuf

**Comment by ao-swarm** [comment]
Right yes, I realized shortly after that this was intended proto behavior and that this plugin simply reflects that. Hadn't come back to update. Apologies and thanks.
