### ISSUE TITLE
Specifying JavaScript compilation fails to build

### ISSUE THREAD

**Issue by cancio** [google/protobuf-gradle-plugin#77]
I am trying to compile proto files to JavaScript. As per your suggestion on [this](http://stackoverflow.com/questions/37324466/gradle-grpc-compilation-for-java-js-c-sharp#comment62817765_37329385) SO post, I added this:

```
protobuf {
  generateProtoTasks {
    all()*.builtins {
      js {}
    }
  }
}
```
When I try to build, I get:

```
  protoc-gen-js: program not found or is not executable
  --js_out: protoc-gen-js: Plugin failed with status code 1.
```

I am running 0.7.7.

**Comment by zhangkun83** [comment]
I confirmed the issue with protoc-3.0.0-alpha-3. @pherl when protoc is invoked with `--js_out` it fails with the above error. Could you take a look?

**Comment by pherl** [comment]
Hmm, which protoc binary are you using? It looks like the binary was actually not the latest one..

**Comment by cancio** [comment]
Was that directed at me or at @zhangkun83? How do I verify the protoc binary version that comes with the plugin?

**Comment by zhangkun83** [comment]
Upgrading to 3.0.0-beta-2 works:
```
protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc:3.0.0-beta-2'
  }
...
```
