### ISSUE TITLE
Add TravisCI support

### ISSUE THREAD

**Issue by jaredsburrows** [google/protobuf-gradle-plugin#78]
Add TravisCI support

Right after cloning the project, simply running `gradlew tasks` fails:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':testProject'.
> Could not resolve all dependencies for configuration ':testProject:classpath'.
   > Could not find com.google.protobuf:protobuf-gradle-plugin:0.7.8-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/protobuf-gradle-plugin-0.7.8-SNAPSHOT.pom
         https://jcenter.bintray.com/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/protobuf-gradle-plugin-0.7.8-SNAPSHOT.jar
         file:/Users/noname/.m2/repository/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/maven-metadata.xml
         file:/Users/noname/.m2/repository/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/protobuf-gradle-plugin-0.7.8-SNAPSHOT.pom
         file:/Users/noname/.m2/repository/com/google/protobuf/protobuf-gradle-plugin/0.7.8-SNAPSHOT/protobuf-gradle-plugin-0.7.8-SNAPSHOT.jar
     Required by:
         protobuf-gradle-plugin:testProject:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.575 secs
```

Adding CI will fix these issues.

**Comment by zhangkun83** [comment]
This issue is not actually CI-specific. `./gradlew tasks` fails because the test projects require `./gradlew install` first (see "Testing the plugin" in README.md). Hopefully #76 will fix this issue.

**Comment by jaredsburrows** [comment]
@zhangkun83 Yeah. There has just gotta be a better way. Normal maven/gradle projects do not require you to install the snapshot locally.

Normally the examples would use the "release". I am guessing you have the examples use the "latest snapshot" for CI integration testing.

**Comment by jaredsburrows** [comment]
@zhangkun83 Either way, I can help you add TravisCI support, we can run `gradlew install` and then `assemble test`. Let me know.

**Comment by zhangkun83** [comment]
That would be great. TravisCI is indeed useful, though installing Android SDK on Travis may be tricky.

**Comment by ejona86** [comment]
Android is actually not too bad on TravisCI. The only reason we don't do it with grpc is because it is incompatible with also testing on osx.

**Comment by jaredsburrows** [comment]
@zhangkun83 The SDK is easy to install on Travis. Please see: https://github.com/jaredsburrows/android-gradle-java-app-template

@ejona86 I see needs osx: https://github.com/grpc/grpc/blob/master/.travis.yml. But for this plugin, which is written in `groovy` we can add just the normal `android` CI for now?

**Comment by ejona86** [comment]
@jaredsburrows, I agree there's no need for OS X on this project. @zhangkun83 is familiar with grpc-java and I was mentioning why it is hard specifically for that project, but shouldn't be difficult for this one.

**Comment by jaredsburrows** [comment]
@zhangkun83 @ejona86 Sounds good. I'll make a PR as soon as TravisCI is turned on for this project.

**Comment by ejona86** [comment]
@zhangkun83, I can't enable Travis for this project. I think can do it at https://travis-ci.org/profile/google

**Comment by zhangkun83** [comment]
I just did it: https://travis-ci.org/google/protobuf-gradle-plugin

**Comment by jaredsburrows** [comment]
@zhangkun83 Thank you. All test projects run except the `testProjectAndroid` does not. Are you all able to run `gradlew assemble`?

**Comment by zhangkun83** [comment]
No, I never tried to do it. First I needed to run under JDK 7 to avoid the "bad class file magic (cafebabe) or version (0034.0000)" error. After that I got the "Duplicate files copied in APK io/grpc/testing/integration/messages.proto".

**Comment by jaredsburrows** [comment]
@zhangkun83 Yeah. Adding:
```
sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7
```
to `testProject` and adding:
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_7
        targetCompatibility = JavaVersion.VERSION_1_7
    }
```
to `testProjectAndroid` solves that issue.

I am still looking into it.

**Comment by jaredsburrows** [comment]
@zhangkun83 Now I am seeing:

```
:testProjectAndroid:transformResourcesWithMergeJavaResForArmFreeappDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testProjectAndroid:transformResourcesWithMergeJavaResForArmFreeappDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK io/grpc/testing/integration/empty.proto
  	File1: /Users/noname/repo/protobuf-gradle-plugin/testProject/build/libs/testProject.jar
  	File2: /Users/noname/repo/protobuf-gradle-plugin/testProject/build/libs/testProject.jar


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.725 secs
```

**Comment by ejona86** [comment]
You can use `packagingOptions` to workaround that (like [I used here](https://github.com/ejona86/grpc-java/commit/5d193ad30654fabfd2c31ab9fd81ebf9874fc1a2#diff-42685fd5e3a2a013ca4c3dd74400202bR16)). It is probably worth figuring out where the dups are coming from though (maybe make an issue to track it).

**Comment by jaredsburrows** [comment]
@ejona86 `packagingOptions` to remove duplicate `.proto` files? I am looking into the dupes now.

**Comment by ejona86** [comment]
@jaredsburrows, yeah, to exclude/pickfirst the dup'ed .proto files (they aren't used anyway). It looks like they are duped because testProject has a copy of the .proto to test normal proto vs nano proto.

**Comment by jaredsburrows** [comment]
@ejona86 Thanks.
This works:
```
    packagingOptions {
        exclude 'io/grpc/testing/integration/empty.proto'
        exclude 'io/grpc/testing/integration/test.proto'
        exclude 'io/grpc/testing/integration/messages.proto'
        exclude 'tmp/stuff.proto'
    }
```
This did not:
```
    packagingOptions {
        pickFirst 'io/grpc/testing/integration/empty.proto'
        pickFirst 'io/grpc/testing/integration/test.proto'
        pickFirst 'io/grpc/testing/integration/messages.proto'
        pickFirst 'tmp/stuff.proto'
    }
```

**Comment by jaredsburrows** [comment]
@zhangkun83 @ejona86 Thanks. I have solved the problem and the build passes.

**Comment by jaredsburrows** [comment]
Closing this because code was merged: https://github.com/google/protobuf-gradle-plugin/pull/79.
