### ISSUE TITLE
Use options like js_out?

### ISSUE THREAD

**Issue by jhspaybar** [google/protobuf-gradle-plugin#81]
I've seen how to reference plugins, but what is the proper way to use the standard protoc binary to generate other language artifacts?  In my case in particular, I'd like to generate with the arguments --js_out=import_style=commonjs,binary:node/ and then use a different gradle plugin to run an npm publish on the node subdirectory.  This lets me have a single project that publishes generated source for every language I need.

Did I miss the documentation on how to pull this off with the gradle plugin?

**Comment by zhangkun83** [comment]
Use `builtins` in the same way as `plugins`:
```
protobuf {
  generateProtoTasks {
    all()*.builtins {
      js {
        option 'import_style=commonjs"
        option 'binary'
      }
    }
  }
}
```

**Comment by jhspaybar** [comment]
Awesome, that worked!  This is what I have now.

```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0-beta-3'
    }

    generateProtoTasks {
        all()*.builtins {
            js {
                option 'import_style=commonjs'
                option 'binary'
                option "output_dir=node/"
            }
        }
    }
}
```

However, this is generating into ${protobuf.generatedFilesBaseDir}/node and I was hoping it'd generate to projectroot/node.  I can make it work regardless, but I was wondering if there was a way to change where the js code output to without affect java in any way?

**Comment by zhangkun83** [comment]
Unfortunately no. The only way to change the output directory is through `generatedFilesBaseDir`.

**Comment by jhspaybar** [comment]
Alright, thanks for all the help.  I got everything working now.
