### ISSUE TITLE
Provide a feature where a seperate FileDesc is generated per proto file

### ISSUE THREAD

**Issue by tabiul** [google/protobuf-gradle-plugin#88]
Currently in order to generate a file descriptor, I am doing the below
 

> ofSourceSet('main').each{task ->
>        task.generateDescriptorSet = true
>        task.descriptorSetOptions.includeImports = true
>        task.descriptorSetOptions.includeSourceInfo = true
>        task.descriptorSetOptions.path = "$projectDir\\src\\main\\desc\\msg.desc"
>   }

The problem with this is that all messages goes to one desc file. I want different desc file per message. Can this be done? Maybe an enhancement?

**Comment by tabiul** [comment]
I am not sure I think the reason for this is this line of code [https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L412] where all the *.proto is passed to the protoc command which results in a single desc file. Maybe some way to configure protoc to run per proto file would solve the issue?

**Comment by zhangkun83** [comment]
What's the issue with single desc file?

**Comment by tabiul** [comment]
There is no problem per say. I wanted to have a single desc file per proto file so that when I send a self descripting message then all I need to do is read that file only. With a single desc file I have to read the full file and then iterate it to find the right descriptor for the message. Please go ahead and close the issue and it is one of good to have thing :)
