### ISSUE TITLE
  Error:Execution failed for task ':app:generateDebugProto'.

### ISSUE THREAD

**Issue by qingdaofu1** [google/protobuf-gradle-plugin#89]
hi, i got this problem,the log like that.

Error:Execution failed for task ':app:generateDebugProto'.
> protoc: stdout: . stderr: D:\Android\google\GoogleSpeech2\app\build\extracted-protos\main: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\src\debug\proto: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\build\extracted-protos\debug: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\build\extracted-include-protos\debug: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\src\debug\proto: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\build\extracted-protos\debug: warning: directory does not exist.
D:\Android\google\GoogleSpeech2\app\build\extracted-include-protos\debug: warning: directory does not exist.
[libprotobuf WARNING google/protobuf/descriptor.cc:6117] Warning: Unused import: "google/logging/v2/logging.proto" imports "google/rpc/status.proto" which is not used.
[libprotobuf WARNING google/protobuf/descriptor.cc:6117] Warning: Unused import: "google/logging/v2/logging_config.proto" imports "google/protobuf/timestamp.proto" which is not used.
--java_out: google/api/annotations.proto: Unknown generator option: lite

I think i already set the protobuf is right, but when i test the google cloud speech api, i got this problem,how i can resolve this problem? please

**Comment by zhangkun83** [comment]
It seems you are using a recent version of protobuf, which has split the lite codegen to be a separate binary. Try this:
```gradle
protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:3.0.0"
  }
  plugins {
    lite {
      artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
    }
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        remove java
      }
      task.plugins {
        lite { }
      }
    }
  }
}
```

**Comment by Stypox** [comment]
I just spent 1 hour on this problem because I had:
```kotlin
protoc {
    libs.protobuf.protoc.get().toString()
}
```
instead of
```kotlin
protoc {
    artifact = libs.protobuf.protoc.get().toString()
}
```

(notice the missing `artifact =`). Leaving this here in case it can help anyone.
