### ISSUE TITLE
Add support java_multiple_files option

### ISSUE THREAD

**Issue by olegshulyakov** [google/protobuf-gradle-plugin#93]
Protoc supports java_multiple_files to generate separate files for separate classes.
This will prevent inner class generation.

Please add support this option into plugin.

**Comment by zhangkun83** [comment]
AFAIK `java_multiple_files` as a protoc command line option is [only supported in nano](https://github.com/google/protobuf/tree/master/javanano).  Please refer to [this example](https://github.com/google/protobuf-gradle-plugin/blob/dc85c957a7f17377a016042684edf0a57c9fe107/testProjectAndroid/build.gradle#L86) on for how to apply it.

If you are not using nano, add this line to your `.proto` file instead:
```
option java_multiple_files = true;
```
